### ISSUE TITLE
No attribute "device_on"

### ISSUE THREAD

**Issue by rasturies** [petretiandrea/home-assistant-tapo-p100#100]
Hello!

HA: 2021.12.5 
Tapo HACS: v1.2.1

I'm getting this error when I try to switch on from a Tapo Light Stripe (L900)

'NoneType' object has no attribute 'device_on'

The log:

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/tapo/light.py:62
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 21:33:51 (2 occurrences)
Last logged: 21:45:03

[140077253799552] 'NoneType' object has no attribute 'device_on'
[140077069589856] 'NoneType' object has no attribute 'device_on'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 209, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 663, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 896, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 700, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 367, in async_handle_light_on_service
    profiles.apply_default(light.entity_id, light.is_on, params)
  File "/config/custom_components/tapo/light.py", line 62, in is_on
    return self._tapo_coordinator.data.device_on
AttributeError: 'NoneType' object has no attribute 'device_on'

When I try to switch on from the Tapo APP all works fine.

**Comment by petretiandrea** [comment]
Have you set a static IP address for your Light Stripe?
