### ISSUE TITLE
L530e problemi

### ISSUE THREAD

**Issue by millenniumy2k** [petretiandrea/home-assistant-tapo-p100#113]
Ciao, non riesco a far funzionare bene le lampadine L530e dopo averle integrate.
Si accendono, poi non si riesce a cambiare la luminosità o colore: diventano poi non disponibili per qualche minuto.

LOG:

Error fetching tapo data:

Logger: custom_components.tapo.common_setup
Source: helpers/update_coordinator.py:219
Integration: Tapo Controller (documentation, issues)
First occurred: 06:34:48 (330 occurrences)
Last logged: 10:57:49

-----

Error doing job: Task exception was never retrieved

Logger: homeassistant
Source: custom_components/tapo/tapo_entity.py:33
Integration: Tapo Controller (documentation, issues)
First occurred: 10:56:58 (6 occurrences)
Last logged: 11:03:01

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 505, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 583, in _async_write_ha_state
    if (name := (entry and entry.name) or self.name) is not None:
  File "/config/custom_components/tapo/tapo_sensor_entity.py", line 47, in name
    return super().name + " " + self.sensor_config.name
  File "/config/custom_components/tapo/tapo_entity.py", line 33, in name
    return self.coordinator.data.nickname
AttributeError: 'NoneType' object has no attribute 'nickname'

**Comment by petretiandrea** [comment]
Which version of integration are you running?

**Comment by millenniumy2k** [comment]
1.2.2

**Comment by petretiandrea** [comment]
Prova ad aggiornare alla nuova versione 1.2.4

**Comment by millenniumy2k** [comment]
Con l'aggiornamento a 1.2.4 il cambio colore funziona, ma non funziona il cambio di luminosità:

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/tapo/tapo_entity.py:43
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 12:11:22 (2 occurrences)
Last logged: 12:11:47

[139796171055008] index out of range
Traceback (most recent call last):
  File "/config/custom_components/tapo/tapo_entity.py", line 41, in _execute_with_fallback
    return await function()
  File "/config/custom_components/tapo/light.py", line 122, in _set_brightness
    await self._tapo_coordinator.api.set_brightness(brightness_to_set)
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 132, in set_brightness
    return await self.set_device_info(LightParams(brightness=brightness))
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 93, in set_device_info
    await self._set_device_info(device_params.as_dict(), terminal_uuid)
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 116, in _set_device_info
    self.__validate_response(resp_dict)
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 256, in __validate_response
    raise TapoException.from_error_code(resp['error_code'])
plugp100.core.exceptions.TapoException.TapoException: Returned unknown error_code: 9999

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 209, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 663, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 896, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 700, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 494, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/config/custom_components/tapo/light.py", line 101, in async_turn_on
    await self._change_brightness(kwargs.get(ATTR_BRIGHTNESS, 255))
  File "/config/custom_components/tapo/light.py", line 124, in _change_brightness
    await self._execute_with_fallback(_set_brightness)
  File "/config/custom_components/tapo/tapo_entity.py", line 43, in _execute_with_fallback
    await self.coordinator.api.login()
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 83, in login
    await self._handshake()
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 163, in _handshake
    self.tp_link_cipher = self.encryption.decode_handshake_key(resp_dict['result']['key'], self.key_pair)
  File "/usr/local/lib/python3.9/site-packages/plugp100/core/encryption.py", line 46, in decode_handshake_key
    b_arr.insert(i, do_final[i])
IndexError: index out of range

**Comment by petretiandrea** [comment]
Which version of firmware do you have in your tapo device?

Also, if you have familiarity with python can you run this script and post here the output?
```python
import asyncio
from plugp100 import TapoApiClient


async def main():
    # create generic tapo api
    sw = TapoApiClient("<ip>", "<email>", "<passwd>")
    await sw.login()
    print(await sw.get_state())

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
loop.run_until_complete(asyncio.sleep(0.1))
loop.close()
```

**Comment by millenniumy2k** [comment]
Ultimo firmare su L530: 1.0.5 build 210928 rel. 180458

Non uso python... ho HA su windows con docker se può servire.
Grazie del supporto!

**Comment by petretiandrea** [comment]
Puoi aprire un terminale all'interno del container docker e utilizzare python con questo script

**Comment by millenniumy2k** [comment]
>>> import asyncio
>>> from plugp100 import TapoApiClient
>>>
>>>
>>> async def main():
...     # create generic tapo api
...     sw = TapoApiClient("<ip>", "<email>", "<passwd>")
...     await sw.login()
...     print(await sw.get_state())
...
>>> loop = asyncio.get_event_loop()
>>> loop.run_until_complete(main())
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1154, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 880, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "<stdin>", line 4, in main
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 83, in login
    await self._handshake()
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 155, in _handshake
    response = await self.http.async_make_post(self.url, json=request_body)
  File "/usr/local/lib/python3.9/site-packages/plugp100/core/http_client.py", line 14, in async_make_post
    async with self.session.post(url, json=json) as response:
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host <ip>:80 ssl:default [Name does not resolve]
>>> loop.run_until_complete(asyncio.sleep(0.1))
>>> loop.close()

**Comment by petretiandrea** [comment]
Questa linea in particolare `sw = TapoApiClient("", "", "")` al intero delle virgolette devi inserire IP del device tapo, email e password usate nella app tapo.

**Comment by millenniumy2k** [comment]
Sono inserite, infatti in HA riesco ad accenderla e spegnerla, non so perchè li non si veda...

**Comment by petretiandrea** [comment]
L'errore è chiaro `socket.gaierror: [Errno -2] Name does not resolve`. Cosa stai mettendo come indirizzo IP, un indirizzo o un nome?

**Comment by millenniumy2k** [comment]
>>> async def main():
...     # create generic tapo api
...     sw = TapoApiClient("192.168.1.38", "---------", "--------")
...     await sw.login()
...     print(await sw.get_state())
...
>>> loop = asyncio.get_event_loop()
>>> loop.run_until_complete(main())
146f4b1c79cbe7dac7c74adde0cf0c900b82d2f3
TapoDeviceState(device_id='802342E0406B24CB9FAA061C9F5767FC1EDFA524', mac='B------9', nickname='Lampadina Smart', model='L530', type='SMART.TAPOBULB', device_on=False, brightness=30, hue=343, saturation=98, color_temp=0, overheated=False, signal_level=2, rssi=-52, energy_info=None)
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f2e3f8ae310>
>>> loop.run_until_complete(asyncio.sleep(0.1))
>>> loop.close()
>>>

Ecco qua, ho tolto ovviamente i dati sensibili....

**Comment by petretiandrea** [comment]
Bene `TapoDeviceState(....` conferma che sta comunicando con il device e che quindi l'autenticazione è andata a buon fine. Prova a inserire gli stessi dati sulla UI durante la configurazione. (Ti consiglio anche di aggiornare l'integrazione all'ultima versione)

**Comment by petretiandrea** [comment]
@millenniumy2k Hai ancora problemi?
