### ISSUE TITLE
Error adding entities for domain light with platform tapo

### ISSUE THREAD

**Issue by Alexfarnstrom** [petretiandrea/home-assistant-tapo-p100#14]
Pulled from Hacs.

Updated today to latest 51ff857 update and it proke my light, cant connect to it, get following error from Hass logs.

Logger: homeassistant.components.light
Source: util/color.py:517
Integration: Lampor (documentation, issues)
First occurred: 14:48:31 (2 occurrences)
Last logged: 14:48:31

Error adding entities for domain light with platform tapo
Error while setting up tapo platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 317, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 509, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 295, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 321, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 481, in state_attributes
    data[ATTR_COLOR_TEMP] = self.color_temp
  File "/config/custom_components/tapo/light.py", line 66, in color_temp
    return kelvin_to_mired(color_temp)
  File "/usr/src/homeassistant/homeassistant/util/color.py", line 517, in color_temperature_kelvin_to_mired
    return math.floor(1000000 / kelvin_temperature)
ZeroDivisionError: division by zero

**Comment by Alexfarnstrom** [comment]
on line 66 and around i commented off (or what is called)
"
#    @property
#    def color_temp(self):
#       color_temp = self._tapo_coordinator.data.color_temp
#        if color_temp is not None:
#            return kelvin_to_mired(color_temp)
"

it removed the posibility to change color, but the light is reachable from home assistant.

**Comment by petretiandrea** [comment]
I've updated right now, I think that this issue is fixed in this new version. Try it

**Comment by Alexfarnstrom** [comment]
I can add the light without a problem now, color change doesnt work, but saw in another issue thread you will fix it in a few days, so closing the issue.
thanks and great work!
