### ISSUE TITLE
1.2.8 issue - Colour wheel "index out of range"

### ISSUE THREAD

**Issue by braymullo** [petretiandrea/home-assistant-tapo-p100#142]
## Issue

Version 1.2.8 gives "index out of range" error when changing colour wheel. Colour temperature works fine.
Version 1.2.7 works perfectly, in both colour wheel and temperature.

## Version of the custom_component

1.2.8

## Configuration

Set up via Integrations.

## Describe the bug

When changing the colour (not the temperature, which works), I am presented with the error "Index out of range"

## Debug log

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/tapo/tapo_entity.py:43 
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22)) 
First occurred: 12:25:34 PM (2 occurrences) 
Last logged: 12:25:36 PM

[140221645713616] index out of range
Traceback (most recent call last):
  File "/config/custom_components/tapo/tapo_entity.py", line 41, in _execute_with_fallback
    return await function()
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 135, in set_color_temperature
    return await self.set_device_info(LightParams(color_temperature=color_temperature))
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 93, in set_device_info
    await self._set_device_info(device_params.as_dict(), terminal_uuid)
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 123, in _set_device_info
    self.__validate_response(decrypted_inner_response)
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 256, in __validate_response
    raise TapoException.from_error_code(resp['error_code'])
plugp100.core.exceptions.TapoException.TapoException: Returned unknown error_code: -1008

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/tapo/tapo_entity.py", line 41, in _execute_with_fallback
    return await function()
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 135, in set_color_temperature
    return await self.set_device_info(LightParams(color_temperature=color_temperature))
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 93, in set_device_info
    await self._set_device_info(device_params.as_dict(), terminal_uuid)
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 123, in _set_device_info
    self.__validate_response(decrypted_inner_response)
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 256, in __validate_response
    raise TapoException.from_error_code(resp['error_code'])
plugp100.core.exceptions.TapoException.TapoException: Returned unknown error_code: -1008

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/tapo/tapo_entity.py", line 41, in _execute_with_fallback
    return await function()
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 135, in set_color_temperature
    return await self.set_device_info(LightParams(color_temperature=color_temperature))
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 93, in set_device_info
    await self._set_device_info(device_params.as_dict(), terminal_uuid)
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 123, in _set_device_info
    self.__validate_response(decrypted_inner_response)
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 256, in __validate_response
    raise TapoException.from_error_code(resp['error_code'])
plugp100.core.exceptions.TapoException.TapoException: Returned unknown error_code: -1008

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/tapo/tapo_entity.py", line 41, in _execute_with_fallback
    return await function()
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 135, in set_color_temperature
    return await self.set_device_info(LightParams(color_temperature=color_temperature))
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 93, in set_device_info
    await self._set_device_info(device_params.as_dict(), terminal_uuid)
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 123, in _set_device_info
    self.__validate_response(decrypted_inner_response)
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 256, in __validate_response
    raise TapoException.from_error_code(resp['error_code'])
plugp100.core.exceptions.TapoException.TapoException: Returned unknown error_code: -1008

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/tapo/tapo_entity.py", line 41, in _execute_with_fallback
    return await function()
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 135, in set_color_temperature
    return await self.set_device_info(LightParams(color_temperature=color_temperature))
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 93, in set_device_info
    await self._set_device_info(device_params.as_dict(), terminal_uuid)
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 123, in _set_device_info
    self.__validate_response(decrypted_inner_response)
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 256, in __validate_response
    raise TapoException.from_error_code(resp['error_code'])
plugp100.core.exceptions.TapoException.TapoException: Returned unknown error_code: -1008

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 190, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1630, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1667, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 668, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 921, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 705, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 504, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/config/custom_components/tapo/light.py", line 115, in async_turn_on
    await self._change_color([hue, saturation])
  File "/config/custom_components/tapo/light.py", line 154, in _change_color
    await self._execute_with_fallback(
  File "/config/custom_components/tapo/tapo_entity.py", line 44, in _execute_with_fallback
    return await self._execute_with_fallback(function, False)
  File "/config/custom_components/tapo/tapo_entity.py", line 44, in _execute_with_fallback
    return await self._execute_with_fallback(function, False)
  File "/config/custom_components/tapo/tapo_entity.py", line 44, in _execute_with_fallback
    return await self._execute_with_fallback(function, False)
  [Previous line repeated 1 more time]
  File "/config/custom_components/tapo/tapo_entity.py", line 43, in _execute_with_fallback
    await self.coordinator.api.login()
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 83, in login
    await self._handshake()
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 163, in _handshake
    self.tp_link_cipher = self.encryption.decode_handshake_key(resp_dict['result']['key'], self.key_pair)
  File "/usr/local/lib/python3.9/site-packages/plugp100/core/encryption.py", line 46, in decode_handshake_key
    b_arr.insert(i, do_final[i])
IndexError: index out of range

**Comment by sharpmindstudio** [comment]
Same issue here on L530, temperature works fine, but color change fails

**Comment by petretiandrea** [comment]
Can you check if in the log before the error are there strings like `Setting` brightness...`? If there can you post the full log?

**Comment by braymullo** [comment]
Tomorrow, I'll change logging level, and install 1.2.8 again and output those details for you :)

**Comment by braymullo** [comment]
Here you go: https://pastebin.com/18ZRxFzj

Hope fully something in there helps :)

**Comment by LAsound** [comment]
hello,
I found out that the bulb is HW version 1 and 2. for version 1.2.8 the colors do not work for HW version 1, for HW version 2 yes

HW version1:
1.2.7 only colors work, temperature is not displayed
1.2.8 temperature works but colors write out of range

**Comment by petretiandrea** [comment]
> hello, I found out that the bulb is HW version 1 and 2. -at 1.2.8 the colors do not work for HW version 1, for HW version 2 colors work
> 
> HW version1: 1.2.7 only colors work, temperature is not displayed 1.2.8 temperature works but colors write out of range

Thanks, so probably there is some regression after fixing bulb with hw2. I will fix asap

**Comment by petretiandrea** [comment]
Try with new 1.2.9 :)

**Comment by sharpmindstudio** [comment]
> Try with new 1.2.9 :)

L530 works fine now. You are great!
