### ISSUE TITLE
Unable to control P100

### ISSUE THREAD

**Issue by caraar12345** [petretiandrea/home-assistant-tapo-p100#158]
## Version of the custom_component

```
1.2.10
```

## Configuration

```yaml
Configured through web UI
```

## Describe the bug

Hello!

I have a Tapo P100 plug which has always worked fine with `tapo_p100_control`, but that component is broken on newer versions of Home Assistant. So I tried yours (with its lovely UI config!) but unfortunately it simply doesn't work. I get this error about `rssi`. I wonder if this is anything to do with the `sensor.signal_level` entity?

Let me know if you need any other info.

Any ideas? :blush:

## Debug log

```text
tapo: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 737, in async_device_update
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 336, in async_update
    await self.coordinator.async_request_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 141, in async_request_refresh
    await self._debounced_refresh.async_call()
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 78, in async_call
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 165, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 553, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 590, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 559, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 372, in state
    value = self.native_value
  File "/config/custom_components/tapo/tapo_sensor_entity.py", line 157, in native_value
    return data.rssi
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 56, in <lambda>
    rssi: int = property(lambda self: self.state["rssi"])
KeyError: 'rssi'
```

**Comment by caraar12345** [comment]
It seems as though Home Assistant Core 2022.3.7 fixed this! 🎉

**Comment by caraar12345** [comment]
Hm, not for the UI config though. Only the Yaml works.

**Comment by petretiandrea** [comment]
Have you tried to remove and re-add the device configured through UI? If with yaml works, there is no reason to not work with UI is the same code base.

**Comment by GoliathLabs** [comment]
@petretiandrea do you need any other information?

**Comment by petretiandrea** [comment]
These errors are really strange, without a step to reproduce it, it's hard to fix them. You can try to unplug and replug or dissociate a re-associate the device

**Comment by GoliathLabs** [comment]
@petretiandrea it did fix itself after a day or two. But thanks for your nice work on this, otherwise I wouldn't be able to use them with homeassistant at all 🚀
