### ISSUE TITLE
Error while setting up tapo platform for switch/light

### ISSUE THREAD

**Issue by Budaa** [petretiandrea/home-assistant-tapo-p100#162]
## Version of the custom_component
v1.2.10 installed with HACS

## Version of the Home Assitant
Home Assistant: core-2022.3.8
Home Assistant OS: 7.5
Python version: 3.9.9

I'm trying to set up 4 devices. 
2 lights: L510
2 switches: P100

## Configuration

```yaml
light:
  - platform: tapo
    host: 192.168.1.201
    username: xxx@gmail.com
    password: xxx
  - platform: tapo
    host: 192.168.1.202
    username: xxx@gmail.com
    password: xxx


switch:
  - platform: tapo
    host: 192.168.1.203
    username: xxx@gmail.com
    password: xxx
  - platform: tapo
    host: 192.168.1.204
    username: xxx@gmail.com
    password: xxx

```

## Describe the bug
Tapo integration fails to set up on my HA. 
I tried re-installing and re-doing the configuration

## Debug log

```text
Logger: homeassistant.components.switch
Source: /usr/local/lib/python3.9/asyncio/events.py:80
Integration: Switch ([documentation](https://www.home-assistant.io/integrations/switch), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+switch%22))
First occurred: 21:53:56 (2 occurrences)
Last logged: 21:53:56

Setup of switch platform tapo is taking over 10 seconds.
```

```text
Logger: homeassistant.components.light
Source: /usr/local/lib/python3.9/asyncio/events.py:80
Integration: Light ([documentation](https://www.home-assistant.io/integrations/light), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+light%22))
First occurred: 21:53:56 (2 occurrences)
Last logged: 21:53:56

Setup of light platform tapo is taking over 10 seconds.
```

```text
Log Details (ERROR)
Logger: homeassistant.components.switch
Source: helpers/update_coordinator.py:161
Integration: Switch ([documentation](https://www.home-assistant.io/integrations/switch), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+switch%22))
First occurred: 21:53:56 (2 occurrences)
Last logged: 21:53:57

Error while setting up tapo platform for switch
Traceback (most recent call last):
  File "/config/custom_components/tapo/common_setup.py", line 96, in _update_with_fallback
    return await self.api.get_state()
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 88, in get_state
    state=await self.get_state_as_dict(),
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 212, in get_state_as_dict
    return await self._execute_method_request(device_info_method)
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 224, in _execute_method_request
    dim_encrypted = self.tp_link_cipher.encrypt(jsons.dumps(method))
AttributeError: 'NoneType' object has no attribute 'encrypt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/tapo/common_setup.py", line 90, in _async_update_data
    return await self._update_with_fallback()
  File "/config/custom_components/tapo/common_setup.py", line 99, in _update_with_fallback
    await self.api.login()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/tapo/common_setup.py", line 90, in _async_update_data
    return await self._update_with_fallback()
  File "/usr/local/lib/python3.9/site-packages/async_timeout/__init__.py", line 129, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.9/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/tapo/common_setup.py", line 92, in _async_update_data
    raise UpdateFailed() from exception
homeassistant.helpers.update_coordinator.UpdateFailed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tapo/switch.py", line 28, in async_setup_platform
    coordinator = await setup_tapo_coordinator_from_dictionary(hass, config)
  File "/config/custom_components/tapo/common_setup.py", line 31, in setup_tapo_coordinator_from_dictionary
    return await setup_tapo_coordinator(
  File "/config/custom_components/tapo/common_setup.py", line 57, in setup_tapo_coordinator
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 161, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady
```

```text
Log Details (ERROR)
Logger: homeassistant.components.light
Source: helpers/update_coordinator.py:161
Integration: Light ([documentation](https://www.home-assistant.io/integrations/light), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+light%22))
First occurred: 21:54:04 (2 occurrences)
Last logged: 21:54:04

Error while setting up tapo platform for light
Traceback (most recent call last):
  File "/config/custom_components/tapo/common_setup.py", line 96, in _update_with_fallback
    return await self.api.get_state()
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 88, in get_state
    state=await self.get_state_as_dict(),
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 212, in get_state_as_dict
    return await self._execute_method_request(device_info_method)
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 224, in _execute_method_request
    dim_encrypted = self.tp_link_cipher.encrypt(jsons.dumps(method))
AttributeError: 'NoneType' object has no attribute 'encrypt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/tapo/common_setup.py", line 90, in _async_update_data
    return await self._update_with_fallback()
  File "/config/custom_components/tapo/common_setup.py", line 99, in _update_with_fallback
    await self.api.login()
  File "/usr/local/lib/python3.9/site-packages/plugp100/core/http_client.py", line 20, in async_make_post_cookie
    return await self._force_read_release(response)
  File "/usr/local/lib/python3.9/site-packages/plugp100/core/http_client.py", line 24, in _force_read_release
    await response.release()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/helpers.py", line 126, in __await__
    yield
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/tapo/common_setup.py", line 90, in _async_update_data
    return await self._update_with_fallback()
  File "/usr/local/lib/python3.9/site-packages/async_timeout/__init__.py", line 129, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.9/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/tapo/common_setup.py", line 92, in _async_update_data
    raise UpdateFailed() from exception
homeassistant.helpers.update_coordinator.UpdateFailed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tapo/light.py", line 43, in async_setup_platform
    coordinator = await setup_tapo_coordinator_from_dictionary(hass, config)
  File "/config/custom_components/tapo/common_setup.py", line 31, in setup_tapo_coordinator_from_dictionary
    return await setup_tapo_coordinator(
  File "/config/custom_components/tapo/common_setup.py", line 57, in setup_tapo_coordinator
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 161, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady
```

**Comment by petretiandrea** [comment]
If I remember how home assistant process the .yaml you need to separate your device declaration. Instead of doing this:
```yaml
light:
  - platform: tapo
    host: 192.168.1.201
    username: xxx@gmail.com
    password: xxx
  - platform: tapo
    host: 192.168.1.202
    username: xxx@gmail.com
    password: xxx
```
Do this:
```
light:
  - platform: tapo
    host: 192.168.1.201
    username: xxx@gmail.com
    password: xxx

light:
  - platform: tapo
    host: 192.168.1.202
    username: xxx@gmail.com
    password: xxx
```

Write again if doesn't work

**Comment by icicimov** [comment]
Confusing. The example given here https://github.com/petretiandrea/home-assistant-tapo-p100#configuration-by-configurationyaml is a map not a list.
