### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by wardy277** [petretiandrea/home-assistant-tapo-p100#171]
## Version of the custom_component

V1.2.10

## Describe the bug

Device: P100

Plug became unavailable so I deleted it and readded via the ui. I completed the form with the correct details and got an unexpected error. If I enter incorrect login details I get an invalid credentials error, so it's partially working and detects correct credentials 

## Debug log

```text


Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 57, in async_step_user
    entry_metadata = await self._validate_input(user_input)
  File "/config/custom_components/tapo/config_flow.py", line 94, in _validate_input
    state = await tapo_api.get_state()
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 88, in get_state
    state=await self.get_state_as_dict(),
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 212, in get_state_as_dict
    return await self._execute_method_request(device_info_method)
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 237, in _execute_method_request
    self.__validate_response(resp_dict)
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 256, in __validate_response
    raise TapoException.from_error_code(resp['error_code'])
plugp100.core.exceptions.TapoException.TapoException: Returned unknown error_code: 9999

```

**Comment by viciovb** [comment]
I have been the same issue for few hours now.

**Comment by viciovb** [comment]
I solved by unplugging and plugging all the socket back

**Comment by martinheavens** [comment]
Thanks @viciovb - that solved it for me too

**Comment by petretiandrea** [comment]
In general, I think that there are some synchronization problems between tapo device and tapo cloud. So when you insert your credentials, probably tapo device is out of sync or something else.
