### ISSUE TITLE
tapo p100 Error doing job: Task exception was never retrieved KeyError: 'rssi'

### ISSUE THREAD

**Issue by bjwo** [petretiandrea/home-assistant-tapo-p100#179]
![image](https://user-images.githubusercontent.com/18684154/167815889-0f74d610-221f-40dd-a6b7-a7856b1982a8.png)

I keep getting the following error in my Home Assistant 22.05 logs - but this error was already there in previous HA releases.
I have set up the repo via HACS; re-installing did not help.

Any clues? Many thanks in advance.

```
2022-05-11 11:21:43 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 137, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 270, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 330, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 388, in state
    value = self.native_value
  File "/config/custom_components/tapo/tapo_sensor_entity.py", line 176, in native_value
    return data.rssi
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 57, in 
    rssi: int = property(lambda self: self.state["rssi"])
KeyError: 'rssi'
```

**Comment by petretiandrea** [comment]
Release 1.2.12 should fix this issue :)

**Comment by bjwo** [comment]
Thank you! 🙏
