### ISSUE TITLE
Integration do not install in home-assistant-snap: Control flow could not be loaded

### ISSUE THREAD

**Issue by pasman1** [petretiandrea/home-assistant-tapo-p100#195]
## Version of the custom_component

[8b3d7c7](https://github.com/petretiandrea/home-assistant-tapo-p100/commit/8b3d7c7d507e6acf89ba0b49a4a042df97403c9d)
-->

## Configuration

```yaml

```

## Describe the bug

Integration do not install. Error message:

Config flow could not be loaded:  undefined.

## Debug log

```text
Logger: homeassistant.util.package
Source: util/package.py:99
First occurred: 6:58:10 AM (3 occurrences)
Last logged: 6:58:32 AM

Unable to install package plugp100==2.1.14: WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f30c42fa310>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/plugp100/ WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f30c42fabe0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/plugp100/ ERROR: Will not install to the user site because it will lack sys.path precedence to pycryptodome in /snap/home-assistant-snap/507/lib/python3.9/site-packages
Unable to install package plugp100==2.1.14: ERROR: Will not install to the user site because it will lack sys.path precedence to pycryptodome in /snap/home-assistant-snap/507/lib/python3.9/site-packages

Logger: aiohttp.server
Source: requirements.py:194
First occurred: 6:58:32 AM (1 occurrences)
Last logged: 6:58:32 AM

Error handling request
Traceback (most recent call last):
  File "/snap/home-assistant-snap/507/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/snap/home-assistant-snap/507/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/snap/home-assistant-snap/507/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/snap/home-assistant-snap/507/lib/python3.9/site-packages/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/snap/home-assistant-snap/507/lib/python3.9/site-packages/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/snap/home-assistant-snap/507/lib/python3.9/site-packages/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/snap/home-assistant-snap/507/lib/python3.9/site-packages/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/snap/home-assistant-snap/507/lib/python3.9/site-packages/homeassistant/components/http/auth.py", line 220, in auth_middleware
    return await handler(request)
  File "/snap/home-assistant-snap/507/lib/python3.9/site-packages/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/snap/home-assistant-snap/507/lib/python3.9/site-packages/homeassistant/components/config/config_entries.py", line 173, in post
    return await super().post(request)
  File "/snap/home-assistant-snap/507/lib/python3.9/site-packages/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/snap/home-assistant-snap/507/lib/python3.9/site-packages/homeassistant/helpers/data_entry_flow.py", line 70, in post
    result = await self._flow_mgr.async_init(
  File "/snap/home-assistant-snap/507/lib/python3.9/site-packages/homeassistant/data_entry_flow.py", line 205, in async_init
    flow, result = await task
  File "/snap/home-assistant-snap/507/lib/python3.9/site-packages/homeassistant/data_entry_flow.py", line 223, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/snap/home-assistant-snap/507/lib/python3.9/site-packages/homeassistant/config_entries.py", line 744, in async_create_flow
    await async_process_deps_reqs(self.hass, self._hass_config, integration)
  File "/snap/home-assistant-snap/507/lib/python3.9/site-packages/homeassistant/setup.py", line 360, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/snap/home-assistant-snap/507/lib/python3.9/site-packages/homeassistant/requirements.py", line 83, in async_get_integration_with_requirements
    await _async_process_integration(hass, integration, done)
  File "/snap/home-assistant-snap/507/lib/python3.9/site-packages/homeassistant/requirements.py", line 99, in _async_process_integration
    await async_process_requirements(
  File "/snap/home-assistant-snap/507/lib/python3.9/site-packages/homeassistant/requirements.py", line 162, in async_process_requirements
    await _async_process_requirements(
  File "/snap/home-assistant-snap/507/lib/python3.9/site-packages/homeassistant/requirements.py", line 194, in _async_process_requirements
    raise RequirementsNotFound(name, [req])
homeassistant.requirements.RequirementsNotFound: Requirements for tapo not found: ['plugp100==2.1.14'].


```

**Comment by mlfunston** [comment]
I had this same error in the container version of home assistant.
The base Alpine docker image didn't include gcc so it errored out compiling something per below (this was just before the error you show above:

>       copying lib/Crypto/Math/Numbers.pyi -> build/lib.linux-x86_64-cpython-39/Crypto/Math
>       running build_ext
>       building 'Crypto.Hash._MD2' extension
>       creating build/temp.linux-x86_64-cpython-39
>       creating build/temp.linux-x86_64-cpython-39/src
>       gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -fomit-frame-pointer -g -fno-semantic-interposition -DTHREAD_STACK_SIZE=0x100000 -fPIC -DPYCRYPTO_LITTLE_ENDIAN -DSYS_BITS=64 -DLTC_NO_ASM -Isrc/ -I/usr/include/python3.9 -c src/MD2.c -o build/temp.linux-x86_64-cpython-39/src/MD2.o
>       error: command 'gcc' failed: No such file or directory
>       [end of output]

      
Going to the console on the home assistant docker container and running:
`apk add build-base`
Then re-adding the integration through HACS fixed it for me and I added the integration and lights successfully. Hope this helps.

**Comment by pasman1** [comment]
Thank you for the answer. 
Solution is simpler: use `/snap/home-assistant-snap/current/pip` to install library plugp100

**Comment by pasman1** [comment]
solved
