### ISSUE TITLE
Missing Integration and Error when doing manual config

### ISSUE THREAD

**Issue by Brevhead** [petretiandrea/home-assistant-tapo-p100#229]
## Version of the custom_component

v1.2.14

## Describe the bug

I am currently running Supervisor 2022.08.3 on Ubuntu 20.04.4 LTS and its installed in a Docker container.  I was able to add the custom repository in HACS and then was able to download/install the Tapo Controller integration from within HACS.  I have restarted HA and also restarted the docker and rebooted the whole machine, but I am unable to see the Tapo Controller integration in the HA integrations section when I click on the button to add it.  I have watched and followed your installation steps and videos.  I then tried to add code to configuration.yaml directly for the light I am trying to connect, but I am seeing an error in the log.  I will paste this in the debug section.  This is the config I added:

light:
  - platform: tapo
    host: 192.168.1.195
    username: ***
    password: ***

the IP above is the IP of one of my bulbs.

## Debug log

Logger: homeassistant.components.light
Source: helpers/update_coordinator.py:178
Integration: Light ([documentation](https://www.home-assistant.io/integrations/light), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+light%22))
First occurred: 12:26:04 (1 occurrences)
Last logged: 12:26:04

Error while setting up tapo platform for light
Traceback (most recent call last):
  File "/config/custom_components/tapo/common_setup.py", line 96, in _update_with_fallback
    return await self.api.get_state()
  File "/usr/local/lib/python3.10/site-packages/plugp100/api.py", line 89, in get_state
    state=await self.get_state_as_dict(),
  File "/usr/local/lib/python3.10/site-packages/plugp100/api.py", line 213, in get_state_as_dict
    return await self._execute_method_request(device_info_method)
  File "/usr/local/lib/python3.10/site-packages/plugp100/api.py", line 225, in _execute_method_request
    dim_encrypted = self.tp_link_cipher.encrypt(jsons.dumps(method))
AttributeError: 'NoneType' object has no attribute 'encrypt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/tapo/common_setup.py", line 90, in _async_update_data
    return await self._update_with_fallback()
  File "/config/custom_components/tapo/common_setup.py", line 99, in _update_with_fallback
    await self.api.login()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/tapo/common_setup.py", line 89, in _async_update_data
    async with async_timeout.timeout(10):
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 129, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/tapo/common_setup.py", line 92, in _async_update_data
    raise UpdateFailed() from exception
homeassistant.helpers.update_coordinator.UpdateFailed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tapo/light.py", line 43, in async_setup_platform
    coordinator = await setup_tapo_coordinator_from_dictionary(hass, config)
  File "/config/custom_components/tapo/common_setup.py", line 31, in setup_tapo_coordinator_from_dictionary
    return await setup_tapo_coordinator(
  File "/config/custom_components/tapo/common_setup.py", line 57, in setup_tapo_coordinator
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 178, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady

```

**Comment by RestOp** [comment]
Same issuee

**Comment by Brevhead** [comment]
> Same issuee

I closed this as it turned out to be quite a simple fix for me. I updated Home Assistant to the most latest version and rebooted everything again... Seemed to sort it. I thought I was on the latest version but I think I was one release off
