### ISSUE TITLE
Tapo Plug p100 Entity doesn't show current status after UI switch pressed

### ISSUE THREAD

**Issue by maximilianneumann** [petretiandrea/home-assistant-tapo-p100#23]
## Version of the custom_component

v1.0

## Describe the bug

Pressing a switch in home assistant switches the plug, but also shows an error. Status of the switch in UI is not updated. Bug happens only sometimes, mostly after longer pause between last switch.

## Debug log

```text

[547844523968] 'NoneType' object has no attribute 'device_on'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 143, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1515, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 206, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 649, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 692, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 686, in _handle_entity_call
    await result
  File "/config/custom_components/tapo/switch.py", line 27, in async_turn_on
    await self._tapo_coordinator.async_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 161, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 235, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 295, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 310, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 334, in _async_write_ha_state
    sstate = self.state
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 704, in state
    return STATE_ON if self.is_on else STATE_OFF
  File "/config/custom_components/tapo/switch.py", line 23, in is_on
    return self._tapo_coordinator.data.device_on
AttributeError: 'NoneType' object has no attribute 'device_on'

```

**Comment by petretiandrea** [comment]
@maximilianneumann Here, I think that problem is related to DataUpdateCoordinator, the current implementation of integration doesn't poll the tapo devices. I will fix it tomorrow using the polling of DataUpdateCoordinator:  `_tapo_coordinator.data` is `None` this means no recent state of tapo device.

**Comment by petretiandrea** [comment]
@maximilianneumann I try to add polling and something about debouncer. You can try this solution? Install the integration manually by cloning from related pull request branch. I can't test it to physical bulbs, because I don't have it.

**Comment by maximilianneumann** [comment]
I installed the new version the manuell way, but now I can't find it in integrations.

When I installed your component the first time it was the same. Than after half an hour and multiple restarts it showed up.

I will write if it works later.

**Comment by petretiandrea** [comment]
Okay thank you

**Comment by maximilianneumann** [comment]
Now I am running the new version, so far there have been no errors :)

**Comment by maximilianneumann** [comment]
Thanks a lot for fixing it :)

**Comment by petretiandrea** [comment]
@maximilianneumann Can you confirm that's working?

**Comment by maximilianneumann** [comment]
Yes, I can confirm that it's working
