### ISSUE TITLE
Tapo L510 bulb gone offline

### ISSUE THREAD

**Issue by spongerobinson** [petretiandrea/home-assistant-tapo-p100#251]
Hi, have been using this integration for a few weeks without issue. Today my Tapo L510 bulb has gone offline. I tried removing it and adding it back but I get an error and the below from logs. Another plug I have (P100) is still working perfectly. Is this something I can sort myself do you know - sorry if this is not the correct place to be asking this. Thanks.

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 55, in async_step_user
    entry_metadata = await self._validate_input(user_input)
  File "/config/custom_components/tapo/config_flow.py", line 92, in _validate_input
    state = await tapo_api.get_state()
  File "/usr/local/lib/python3.10/site-packages/plugp100/api.py", line 89, in get_state
    state=await self.get_state_as_dict(),
  File "/usr/local/lib/python3.10/site-packages/plugp100/api.py", line 213, in get_state_as_dict
    return await self._execute_method_request(device_info_method)
  File "/usr/local/lib/python3.10/site-packages/plugp100/api.py", line 238, in _execute_method_request
    self.__validate_response(resp_dict)
  File "/usr/local/lib/python3.10/site-packages/plugp100/api.py", line 257, in __validate_response
    raise TapoException.from_error_code(resp['error_code'])
plugp100.core.exceptions.TapoException.TapoException: Returned unknown error_code: 9999

**Comment by spongerobinson** [comment]
I should have added:

Home Assistant 2022.10.1
Supervisor 2022.09.1
Operating System 9.0
Frontend 20221006.0 - latest

**Comment by spongerobinson** [comment]
Ok, so strange thing - I just updated the firmware on the plug and now it was possible to add it again. Maybe it just needed a reset. Will monitor over the coming days. Thanks for the integration - without it I wouldnt be able to use any of the Tapo stuff I have!
