### ISSUE TITLE
Crash on Tapo P110 integration

### ISSUE THREAD

**Issue by Karmak23** [petretiandrea/home-assistant-tapo-p100#266]
Versions: HA Core 2022.10.5, latest Supervisor to date
Tapo integration v1.2.15 via HACS
update: updated to v1.2.16 and same problem.

Today, all my P110 plugs report "the entity is no more provided by the integration, you can remove it etc".

Plugs appear OK in the Tapo Android App, and their IP adresses are fixed and controlled OK.

Obviously this does not affect the P100, which are still usable.

Backtrace:
```
Logger: homeassistant.components.sensor
Source: custom_components/tapo/tapo_sensor_entity.py:115
Integration: Capteur (documentation, issues)
First occurred: 16:56:56 (4 occurrences)
Last logged: 16:56:56

Error adding entities for domain sensor with platform tapo
Error while setting up tapo platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 691, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 777, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 571, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 539, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 404, in state
    value = self.native_value
  File "/config/custom_components/tapo/tapo_sensor_entity.py", line 115, in native_value
    return self.coordinator.data.energy_info.this_month_energy / 1000
  File "/usr/local/lib/python3.10/site-packages/plugp100/api.py", line 36, in <lambda>
    this_month_energy: float = property(lambda self: self.info['past1y'][11])
KeyError: 'past1y'
```

Any pointer of anything I could I have done wrong ?

**Comment by johnwilson456** [comment]
Yes this has broken for me too as of today

**Comment by Karmak23** [comment]
OK sorry, closing because it is a duplicate of https://github.com/petretiandrea/home-assistant-tapo-p100/issues/264
