### ISSUE TITLE
Add support for H200 hub

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [petretiandrea/home-assistant-tapo-p100#273]
Could you add H200 as a new hub (packaged with the new tapo c420s2 cameras)

**Device Info**
Does not work unfortunately

```shell
 ~/Desktop  python ./tapo.py
Traceback (most recent call last):
  File "/Users/user/.pyenv/versions/3.8.12/lib/python3.8/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/Users/user/.pyenv/versions/3.8.12/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/Users/user/.pyenv/versions/3.8.12/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/Users/user/.pyenv/versions/3.8.12/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/Users/user/.pyenv/versions/3.8.12/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect
    return await fut
  File "/Users/user/.pyenv/versions/3.8.12/lib/python3.8/asyncio/selector_events.py", line 528, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 60] Connect call failed ('192.168.0.139', 80)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./tapo.py", line 16, in <module>
    loop.run_until_complete(main())
  File "/Users/user/.pyenv/versions/3.8.12/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "./tapo.py", line 9, in main
    await sw.login()
  File "/Users/user/.pyenv/versions/3.8.12/lib/python3.8/site-packages/plugp100/api/tapo_api_client.py", line 41, in login
    await self.client.login()
  File "/Users/user/.pyenv/versions/3.8.12/lib/python3.8/site-packages/plugp100/tapo_protocol/tapo_protocol_client.py", line 36, in login
    await self._handshake()
  File "/Users/user/.pyenv/versions/3.8.12/lib/python3.8/site-packages/plugp100/tapo_protocol/tapo_protocol_client.py", line 87, in _handshake
    response = await self.http.async_make_post(self.url, json=request_body)
  File "/Users/user/.pyenv/versions/3.8.12/lib/python3.8/site-packages/plugp100/utils/http_client.py", line 13, in async_make_post
    async with self.session.post(url, json=json) as response:
  File "/Users/user/.pyenv/versions/3.8.12/lib/python3.8/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/Users/user/.pyenv/versions/3.8.12/lib/python3.8/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/Users/user/.pyenv/versions/3.8.12/lib/python3.8/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Users/user/.pyenv/versions/3.8.12/lib/python3.8/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/Users/user/.pyenv/versions/3.8.12/lib/python3.8/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/Users/user/.pyenv/versions/3.8.12/lib/python3.8/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/Users/user/.pyenv/versions/3.8.12/lib/python3.8/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.0.139:80 ssl:default [Connect call failed ('192.168.0.139', 80)]
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x10b827ac0>
```

But the hub is pingable:

```
 ping 192.168.0.139
PING 192.168.0.139 (192.168.0.139): 56 data bytes
64 bytes from 192.168.0.139: icmp_seq=0 ttl=64 time=3.821 ms
64 bytes from 192.168.0.139: icmp_seq=1 ttl=64 time=5.852 ms
64 bytes from 192.168.0.139: icmp_seq=2 ttl=64 time=4.223 ms
^C
--- 192.168.0.139 ping statistics ---
3 packets transmitted, 3 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 3.821/4.632/5.852/0.878 ms
```

**Comment by h0jeZvgoxFepBQ2C** [comment]
Details from the API:

```json

{
    "error_code": 0,
    "result": {
        "deviceList": [
            {
                "deviceType": "SMART.TAPOHUB",
                "role": 0,
                "fwVer": "1.1.1 Build 20220713 rel.56639",
                "appServerUrl": "https://eu-wap.tplinkcloud.com",
                "deviceRegion": "eu-west-1",
                "deviceId": "802D1C9E238D3730FCF2A81B6CAA766920358116",
                "deviceName": "H200",
                "deviceHwVer": "1.0",
                "alias": "VGFwb19IdWJfRDc5NQ==",
                "deviceMac": "1C61B4DAD795",
                "oemId": "20BDFF5DD35D9F82C31FC30217AA348D",
                "deviceModel": "H200(EU)",
                "hwId": "99A36151C79A3A5D72823C98BC0FDA5F",
                "fwId": "BD6A2A57605B151F2ADBC71AC4839310",
                "isSameRegion": true,
                "status": 0
            }
        ]
    }
}
```

**Comment by petretiandrea** [comment]
This Integration doesn't manage tapo cameras, but other devices like light, switch and led strip

**Comment by h0jeZvgoxFepBQ2C** [comment]
Ah sorry, I mixed up the P with H :D (P100 vs H200)
