### ISSUE TITLE
L900 light strip cannot be added

### ISSUE THREAD

**Issue by j1104c** [petretiandrea/home-assistant-tapo-p100#274]
Hello
  Now I'm using Tapo integration v1.2.16 homeassistant core2022.7.6 supervisorOS9.2 and the L900 is not connected to the Tapo controller, so what should I do now?
  show log
  Installing the integration on its own produces an error.

  Logger: custom_components.tapo.config_flow
  Source: custom_components/tapo/config_flow.py:92
  Integration: Tapo Controller (documentation, issues)
  First occurrence: 03:27:51 (1 time)
  Last login time: 03:27:51

  unexpected exception
  Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py" in async_step_user, line 55
  entry_metadata = wait for self._validate_input(user_input)
  File "/config/custom_components/tapo/config_flow.py" in _validate_input, line 92
  state = waiting for tapo_api.get_state()
  File "/usr/local/lib/python3.10/site-packages/plugp100/api.py", line 89, in get_state
  state=await self.get_state_as_dict(),
  File "/usr/local/lib/python3.10/site-packages/plugp100/api.py", line 213, in get_state_as_dict
  return await self._execute_method_request(device_info_method)
  File "/usr/local/lib/python3.10/site-packages/plugp100/api.py" in _execute_method_request, line 241
  self.tp_link_cipher.decrypt(
  File "/usr/local/lib/python3.10/site-packages/plugp100/core/tp_link_cipher.py", line 23, decrypted
  return PKCS7Encoder().decode(pad_text)
  File "/usr/local/lib/python3.10/site-packages/plugp100/core/pkcs7/init.py" in decode, line 37
  raise Exception('text not %d align'%(self.__klen))
  Exception: Text is not 16-aligned

**Comment by osk2** [comment]
I have the same error with my L900.

My account and password are lower-cased. But still can't get it working.

```
Home Assistant 2022.12.2
Supervisor 2022.12.dev0901

Tapo Controller v1.2.18
```

```
Logger: custom_components.tapo.config_flow
Source: custom_components/tapo/config_flow.py:91
Integration: tapo_p100 ([documentation](https://github.com/petretiandrea/home-assistant-tapo-p100), [issues](https://github.com/petretiandrea/home-assistant-tapo-p100/issues/))
First occurred: 11:23:58 AM (4 occurrences)
Last logged: 11:33:10 AM

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 54, in async_step_user
    entry_metadata = await self._validate_input(user_input)
  File "/config/custom_components/tapo/config_flow.py", line 91, in _validate_input
    state = await tapo_api.get_state()
  File "/usr/local/lib/python3.10/site-packages/plugp100/api/tapo_api_client.py", line 45, in get_state
    state_dict = await self.client.send_tapo_request(GetDeviceInfoMethod(None))
  File "/usr/local/lib/python3.10/site-packages/plugp100/tapo_protocol/tapo_protocol_client.py", line 64, in send_tapo_request
    self.tp_link_cipher.decrypt(
  File "/usr/local/lib/python3.10/site-packages/plugp100/tapo_protocol/encryption/tp_link_cipher.py", line 48, in decrypt
    return PKCS7Encoder().decode(pad_text)
  File "/usr/local/lib/python3.10/site-packages/plugp100/tapo_protocol/encryption/pkcs7/__init__.py", line 37, in decode
    raise Exception('text not %d align'%(self.__klen))
Exception: text not 16 align
```

**Comment by xenonshop** [comment]
Same here:
Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 54, in async_step_user
    entry_metadata = await self._validate_input(user_input)
  File "/config/custom_components/tapo/config_flow.py", line 91, in _validate_input
    state = await tapo_api.get_state()
  File "/usr/local/lib/python3.10/site-packages/plugp100/api/tapo_api_client.py", line 45, in get_state
    state_dict = await self.client.send_tapo_request(GetDeviceInfoMethod(None))
  File "/usr/local/lib/python3.10/site-packages/plugp100/tapo_protocol/tapo_protocol_client.py", line 64, in send_tapo_request
    self.tp_link_cipher.decrypt(
  File "/usr/local/lib/python3.10/site-packages/plugp100/tapo_protocol/encryption/tp_link_cipher.py", line 48, in decrypt
    return PKCS7Encoder().decode(pad_text)
  File "/usr/local/lib/python3.10/site-packages/plugp100/tapo_protocol/encryption/pkcs7/__init__.py", line 37, in decode
    raise Exception('text not %d align'%(self.__klen))
Exception: text not 16 align

**Comment by petretiandrea** [comment]
Please provide the home-assistant version, os and cpu architecture then the integration version

**Comment by xenonshop** [comment]
Home Assistant 2022.12.7 Supervisor 2022.11.2 Operating System 9.4 Frontend 20221213.1 - latest
OVA VM under VMWare ESXI

Tapo controller 1.2.18


Marian Titieni
Edelweiss srl

**Comment by petretiandrea** [comment]
A new version has been released, try it now
