### ISSUE TITLE
HA integration does not start when connection to one of the P100 switches fails

### ISSUE THREAD

**Issue by lassi-niemisto** [petretiandrea/home-assistant-tapo-p100#279]
## Version of the integration

* Tapo integration 1.2.17 installed with HACS couple of versions earlier and updated once
* Home Assistant 2022.9.4  / Frontend 20220907.2 - latest

## Configuration

* 3x TAPO P100 1.20.0 / 1.4.10 build 20211104 rel 35882 
* All units configured in the UI, not in yaml

## Describe the bug

When one of my P100 devices is unplugged/outside-network/ip-changed during HA restart, the Tapo integration seems to not start properly, giving the following symptoms:
* Unable to control those P100 devices that should be reachable (they work fine from Tapo mobile app)
* Unable to see any tapo devices in the HA "integrations" or "devices" menu
* As the devices were added with UI, unable to remove the problematic devices
* As integration remains in "missing/unloaded" state, there is no other option than to restart whole HA

Logically the connectability of any individual device should not affect the access to other devices or the integration user interface. 

## Debug log

The logs when a device is actually unconnectable with its configured IP:

```text

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1064, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.1.29', 80)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/tapo/common_setup.py", line 91, in _async_update_data
    return await self._update_with_fallback()
  File "/config/custom_components/tapo/common_setup.py", line 100, in _update_with_fallback
    await self.api.login()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.1.29:80 ssl:default [Connect call failed ('192.168.1.29', 80)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/tapo/common_setup.py", line 93, in _async_update_data
    raise UpdateFailed() from exception
homeassistant.helpers.update_coordinator.UpdateFailed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tapo/switch.py", line 28, in async_setup_platform
    coordinator = await setup_tapo_coordinator_from_dictionary(hass, config)
  File "/config/custom_components/tapo/common_setup.py", line 31, in setup_tapo_coordinator_from_dictionary
    return await setup_tapo_coordinator(
  File "/config/custom_components/tapo/common_setup.py", line 58, in setup_tapo_coordinator
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 178, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady
```

The log that happens randomly even if all devices are in network (but maybe the network quality is not 100% to some devices):

```text

Error while setting up tapo platform for switch
Traceback (most recent call last):
  File "/config/custom_components/tapo/common_setup.py", line 97, in _update_with_fallback
    return await self.api.get_state()
  File "/usr/local/lib/python3.10/site-packages/plugp100/api/tapo_api_client.py", line 45, in get_state
    state_dict = await self.client.send_tapo_request(GetDeviceInfoMethod(None))
  File "/usr/local/lib/python3.10/site-packages/plugp100/tapo_protocol/tapo_protocol_client.py", line 48, in send_tapo_request
    dim_encrypted = self.tp_link_cipher.encrypt(jsons.dumps(method))
AttributeError: 'NoneType' object has no attribute 'encrypt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/tapo/common_setup.py", line 91, in _async_update_data
    return await self._update_with_fallback()
  File "/config/custom_components/tapo/common_setup.py", line 100, in _update_with_fallback
    await self.api.login()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/tapo/common_setup.py", line 90, in _async_update_data
    async with async_timeout.timeout(10):
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 129, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/tapo/common_setup.py", line 93, in _async_update_data
    raise UpdateFailed() from exception
homeassistant.helpers.update_coordinator.UpdateFailed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tapo/switch.py", line 28, in async_setup_platform
    coordinator = await setup_tapo_coordinator_from_dictionary(hass, config)
  File "/config/custom_components/tapo/common_setup.py", line 31, in setup_tapo_coordinator_from_dictionary
    return await setup_tapo_coordinator(
  File "/config/custom_components/tapo/common_setup.py", line 58, in setup_tapo_coordinator
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 178, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady
```

## Questions to author
* Considering this is a bug and the startup sequence should skip any missing/problematic devices to succeed with others, is there any existing functionality to retry connecting to those skipped devices later or are they doomed to unavailability until next HA restart?
* Can you think of a scenario where (e.g. days after a successful HA start) this behavior would also result in connection failure with device X causing paralyzed connectivity to devices Y, Z, ... (as I suspect I have might seen this as well)

**Comment by Karmak23** [comment]
I think I’m also affected by this issue. One of my P100 is not reachable anymore via HA, while it works via Tapo Android app.

This behaviour started more or less when I cut some P100/P110 from the network (I need the energy source to be completely off, thus the full electricity backbone is off, making 4 plugs out of reach from the wifi because they are not powered anymore).

This seemed to work when the "main" P110 was powered (3 P100 are "slaves" of it; they are reachable only when the P110 is on).

**Comment by petretiandrea** [comment]
Try new version 1.3.2

**Comment by lassi-niemisto** [comment]
Thanks @petretiandrea, I have had no issues after updating to 1.3.3 and updating my home assistant at the same time.
