### ISSUE TITLE
P300 support

### ISSUE THREAD

**Issue by NadeoGolf** [petretiandrea/home-assistant-tapo-p100#288]
Hello, can you add support for the P300 power strip?

My logs when i add it:

Logger: homeassistant.components.binary_sensor
Source: custom_components/tapo/tapo_sensor_entity.py:155
Integration: Capteur binaire (documentation, issues)
First occurred: 4 décembre 2022 à 16:52:18 (10 occurrences)
Last logged: 09:54:02

Error adding entities for domain binary_sensor with platform tapo
Error while setting up tapo platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 692, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 789, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 583, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 551, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 669, in state
    value = self.native_value
  File "/config/custom_components/tapo/tapo_sensor_entity.py", line 155, in native_value
    return data.overheated
  File "/usr/local/lib/python3.10/site-packages/plugp100/domain/tapo_state.py", line 22, in <lambda>
    overheated: bool = property(lambda self: self.state["overheated"])
KeyError: 'overheated'

Logger: homeassistant.components.sensor
Source: custom_components/tapo/tapo_sensor_entity.py:155
Integration: Capteur (documentation, issues)
First occurred: 4 décembre 2022 à 16:52:24 (5 occurrences)
Last logged: 09:54:02

tapo: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 493, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 715, in async_device_update
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 359, in async_update
    await self.coordinator.async_request_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 158, in async_request_refresh
    await self._debounced_refresh.async_call()
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 82, in async_call
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 110, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 348, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 545, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 583, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 551, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 669, in state
    value = self.native_value
  File "/config/custom_components/tapo/tapo_sensor_entity.py", line 155, in native_value
    return data.overheated
  File "/usr/local/lib/python3.10/site-packages/plugp100/domain/tapo_state.py", line 22, in <lambda>
    overheated: bool = property(lambda self: self.state["overheated"])
KeyError: 'overheated'

**Comment by petretiandrea** [comment]
Please open new Issue and use "New Device Support Request" issue template and follow the steps
