### ISSUE TITLE
P100 suddenly gone

### ISSUE THREAD

**Issue by hcm183** [petretiandrea/home-assistant-tapo-p100#289]
Suddenly without any impact, two P100 of nine  P100 and P110 are not reachable. Even in a complete new installation they are called even configured or unexpected error or invalid authentification is declared when I was trying to add them.  Any solution?

**Comment by Jamackey** [comment]
#171

**Comment by petretiandrea** [comment]
Can you post here your logs?

**Comment by nifroidl** [comment]
I have the same issue. In the Logfile it only says „Smart Device is not available any more“. First I thought I have an issue with my internet connection but I still can control the Tapo plug with the Tapo App so probably, there is not internet issue. Can you help me?

**Comment by petretiandrea** [comment]
Probably there is sync problem between your tapo device and tapo cloud. So you can try to remove tapo device from App and home assistant and re-add it to app first and then to home assistant. Please post your home assistant version

**Comment by amibumping** [comment]
Hi, happens to me too today, here is the log, on the app it shows and runs ok.

`Traceback (most recent call last):
  File "/home/homeassistant/.pyenv/versions/3.9.13/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/mnt/dietpi_userdata/homeassistant/custom_components/tapo/sensor.py", line 30, in async_setup_entry
    if coordinator.data.model.lower() in SUPPORTED_DEVICE_AS_SWITCH_POWER_MONITOR:
AttributeError: 'NoneType' object has no attribute 'model'`

Using latest HA version 2022.12.7

**Comment by tkgafs** [comment]
this has now happened to me as well 2 specific switches affected out of a total of 8 P100 switches

Both the tapo app on my phone and Alexa can still control the 2 switches in question, its only the tapo integration in homeassisant that is failing

From My logs

2022-12-26 11:34:57.425 ERROR (MainThread) [homeassistant.components.switch] Error while setting up tapo platform for switch
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/tapo/switch.py", line 19, in async_setup_entry
_setup_from_coordinator(coordinator, async_add_devices)
File "/config/custom_components/tapo/switch.py", line 33, in _setup_from_coordinator
if coordinator.data.model.lower() in SUPPORTED_DEVICE_AS_SWITCH:
AttributeError: 'NoneType' object has no attribute 'model'
2022-12-26 11:34:57.436 ERROR (MainThread) [homeassistant.components.light] Error while setting up tapo platform for light
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/tapo/light.py", line 34, in async_setup_entry
_setup_from_coordinator(coordinator, async_add_devices)
File "/config/custom_components/tapo/light.py", line 49, in _setup_from_coordinator
if model.lower() in coordinator.data.model.lower():
AttributeError: 'NoneType' object has no attribute 'model'
2022-12-26 11:34:57.442 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up tapo platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/tapo/sensor.py", line 30, in async_setup_entry
if coordinator.data.model.lower() in SUPPORTED_DEVICE_AS_SWITCH_POWER_MONITOR:
AttributeError: 'NoneType' object has no attribute 'model'
2022-12-26 11:34:57.460 ERROR (MainThread) [homeassistant.components.binary_sensor] Error adding entities for domain binary_sensor with platform tapo
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 484, in _async_add_entity
entity.add_to_platform_start(
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 479, in add_to_platform_start
if self.unique_id is None:
File "/config/custom_components/tapo/tapo_sensor_entity.py", line 43, in unique_id
return super().unique_id + "_" + self.sensor_config.name.replace(" ", "_")
File "/config/custom_components/tapo/tapo_entity.py", line 29, in unique_id
return self.coordinator.data.device_id
AttributeError: 'NoneType' object has no attribute 'device_id'
2022-12-26 11:34:57.475 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up tapo platform for binary_sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 289, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 484, in _async_add_entity
entity.add_to_platform_start(
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 479, in add_to_platform_start
if self.unique_id is None:
File "/config/custom_components/tapo/tapo_sensor_entity.py", line 43, in unique_id
return super().unique_id + "_" + self.sensor_config.name.replace(" ", "_")
File "/config/custom_components/tapo/tapo_entity.py", line 29, in unique_id
return self.coordinator.data.device_id
AttributeError: 'NoneType' object has no attribute 'device_id'
2022-12-26 11:34:57.509 ERROR (MainThread) [homeassistant.components.switch] Error while setting up tapo platform for switch
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/tapo/switch.py", line 19, in async_setup_entry
_setup_from_coordinator(coordinator, async_add_devices)
File "/config/custom_components/tapo/switch.py", line 33, in _setup_from_coordinator
if coordinator.data.model.lower() in SUPPORTED_DEVICE_AS_SWITCH:
AttributeError: 'NoneType' object has no attribute 'model'
2022-12-26 11:34:57.510 ERROR (MainThread) [homeassistant.components.light] Error while setting up tapo platform for light
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/tapo/light.py", line 34, in async_setup_entry
_setup_from_coordinator(coordinator, async_add_devices)
File "/config/custom_components/tapo/light.py", line 49, in _setup_from_coordinator
if model.lower() in coordinator.data.model.lower():
AttributeError: 'NoneType' object has no attribute 'model'

**Comment by tkgafs** [comment]
As suggested above Deleting the two failing plugs in Home Assistant then the android App then powering them off and on re-adding in the android app and then in home assistant has fixed the issue, but I'm puzzld why the worked in the android app and in Alexa but didnt in home assistant

**Comment by petretiandrea** [comment]
> As suggested above Deleting the two failing plugs in Home Assistant then the android App then powering them off and on re-adding in the android app and then in home assistant has fixed the issue, but I'm puzzld why the worked in the android app and in Alexa but didnt in home assistant

There are some sync issue between Tapo device and cloud. Even this integration doesn't use cloud, it need to perform a login to tapo device by using username and password. Username and password still cause error, I suppose due to a sync issue between cloud's username and password and tapo device
