### ISSUE TITLE
Unexpected exception when starting HA or trying to integrate Tapo device again

### ISSUE THREAD

**Issue by vincemue** [petretiandrea/home-assistant-tapo-p100#298]
Hi,

the integration worked fine for some days but suddenly a few switches became unavailable.
I deleted them and tried to integrate them again using the UI setup, but failed with an unexpected exception.

Using google home or the Tapo app is still working.

Just started with HA some days ago, so this could totally be my fault as well.

If you need anything else, let me know.

<details><summary>Error while setting up tapo platform for switch
</summary>
<p>

`Logger: homeassistant.components.switch
Source: helpers/update_coordinator.py:197
Integration: Switch ([documentation](https://www.home-assistant.io/integrations/switch), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+switch%22))
First occurred: 10:32:27 AM (1 occurrences)
Last logged: 10:32:27 AM

Error while setting up tapo platform for switch
Traceback (most recent call last):
  File "/config/custom_components/tapo/common_setup.py", line 97, in _update_with_fallback
    return await self.api.get_state()
  File "/usr/local/lib/python3.10/site-packages/plugp100/api/tapo_api_client.py", line 45, in get_state
    state_dict = await self.client.send_tapo_request(GetDeviceInfoMethod(None))
  File "/usr/local/lib/python3.10/site-packages/plugp100/tapo_protocol/tapo_protocol_client.py", line 48, in send_tapo_request
    dim_encrypted = self.tp_link_cipher.encrypt(jsons.dumps(method))
AttributeError: 'NoneType' object has no attribute 'encrypt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/tapo/common_setup.py", line 91, in _async_update_data
    return await self._update_with_fallback()
  File "/config/custom_components/tapo/common_setup.py", line 100, in _update_with_fallback
    await self.api.login()
  File "/usr/local/lib/python3.10/site-packages/plugp100/api/tapo_api_client.py", line 41, in login
    await self.client.login()
  File "/usr/local/lib/python3.10/site-packages/plugp100/tapo_protocol/tapo_protocol_client.py", line 37, in login
    await self._login_request(self.username, self.password)
  File "/usr/local/lib/python3.10/site-packages/plugp100/tapo_protocol/tapo_protocol_client.py", line 141, in _login_request
    self.token = decrypted_inner_response['result']['token']
KeyError: 'result'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/tapo/common_setup.py", line 93, in _async_update_data
    raise UpdateFailed() from exception
homeassistant.helpers.update_coordinator.UpdateFailed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tapo/switch.py", line 28, in async_setup_platform
    coordinator = await setup_tapo_coordinator_from_dictionary(hass, config)
  File "/config/custom_components/tapo/common_setup.py", line 31, in setup_tapo_coordinator_from_dictionary
    return await setup_tapo_coordinator(
  File "/config/custom_components/tapo/common_setup.py", line 58, in setup_tapo_coordinator
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 197, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady`

</p>
</details>

<details><summary>Unexpected exception</summary>
<p>

Logger: custom_components.tapo.config_flow
Source: custom_components/tapo/config_flow.py:91
Integration: tapo_p100 ([documentation](https://github.com/petretiandrea/home-assistant-tapo-p100), [issues](https://github.com/petretiandrea/home-assistant-tapo-p100/issues/))
First occurred: 10:37:46 AM (1 occurrences)
Last logged: 10:37:46 AM

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 54, in async_step_user
    entry_metadata = await self._validate_input(user_input)
  File "/config/custom_components/tapo/config_flow.py", line 91, in _validate_input
    state = await tapo_api.get_state()
  File "/usr/local/lib/python3.10/site-packages/plugp100/api/tapo_api_client.py", line 45, in get_state
    state_dict = await self.client.send_tapo_request(GetDeviceInfoMethod(None))
  File "/usr/local/lib/python3.10/site-packages/plugp100/tapo_protocol/tapo_protocol_client.py", line 61, in send_tapo_request
    self._validate_response(resp_dict)
  File "/usr/local/lib/python3.10/site-packages/plugp100/tapo_protocol/tapo_protocol_client.py", line 148, in _validate_response
    raise TapoException.from_error_code(resp['error_code'])
plugp100.domain.tapo_exception.TapoException: Returned unknown error_code: 9999

</p>
</details>

**Comment by Viderek** [comment]
I was having the same issue. All Tapo plugs stopped working with the latest HA core update due to a similar error as above. In my case it was:

```
File "/config/custom_components/tapo/switch.py", line 33, in _setup_from_coordinator
    if coordinator.data.model.lower() in SUPPORTED_DEVICE_AS_SWITCH:
AttributeError: 'NoneType' object has no attribute 'model'
```

I removed the devices from HA and added them back again one by one. Now everything works as normal.

In my case, I also had some type change helpers that disappeared automaticaly when I removed the devices. So I had to recreate the helpers too.

**Comment by petretiandrea** [comment]
A new version has been released, try it now

**Comment by jove01** [comment]
Hi, i am a newbie and try some things. So I integreated 4 Tapo Devices. It looks, all works fine. But in the log I find this message:
`Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.tapo.common_setup
Source: custom_components/tapo/common_setup.py:46
Integration: Tapo Controller (documentation, issues)
First occurred: 13:50:14 (8 occurrences)
Last logged: 13:50:37

Failed to setup Unexpected exception:`

I hope, you can find the reason

Thanks
Jürgen
