### ISSUE TITLE
After a reboot I have this error: Setup failed for custom integration tapo: Requirements for tapo not found: ['plugp100==2.2.1'].

### ISSUE THREAD

**Issue by razvanu** [petretiandrea/home-assistant-tapo-p100#311]
![image](https://user-images.githubusercontent.com/15201014/210136572-a1d143cd-bc1a-4e02-a050-9cda9fa84cd7.png)

Hello, please tell what's missing ?

![image](https://user-images.githubusercontent.com/15201014/210136591-067a6b85-85ff-4cf8-b54a-be422d98fede.png)

Thank you

**Comment by razvanu** [comment]
`Logger: aiohttp.server
Source: custom_components/tapo/common_setup.py:6
Integration: tapo_p100 ([documentation](https://github.com/petretiandrea/home-assistant-tapo-p100), [issues](https://github.com/petretiandrea/home-assistant-tapo-p100/issues/))
First occurred: 2:23:42 PM (4 occurrences)
Last logged: 2:24:00 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 81, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 86, in delete
    result = await hass.config_entries.async_remove(entry_id)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 950, in async_remove
    await entry.async_remove(self.hass)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 551, in async_remove
    component = integration.get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 709, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/tapo/__init__.py", line 8, in <module>
    from custom_components.tapo.common_setup import (
  File "/config/custom_components/tapo/common_setup.py", line 6, in <module>
    from plugp100 import (
ImportError: cannot import name 'TapoError' from 'plugp100' (/usr/local/lib/python3.10/site-packages/plugp100/__init__.py)`

**Comment by petretiandrea** [comment]
> `Logger: aiohttp.server
> Source: custom_components/tapo/common_setup.py:6
> Integration: tapo_p100 ([documentation](https://github.com/petretiandrea/home-assistant-tapo-p100), [issues](https://github.com/petretiandrea/home-assistant-tapo-p100/issues/))
> First occurred: 2:23:42 PM (4 occurrences)
> Last logged: 2:24:00 PM
> 
> Error handling request
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
>     resp = await request_handler(request)
>   File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
>     resp = await handler(request)
>   File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 81, in ban_middleware
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
>     return await handler(request)
>   File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
>     result = await result
>   File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 86, in delete
>     result = await hass.config_entries.async_remove(entry_id)
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 950, in async_remove
>     await entry.async_remove(self.hass)
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 551, in async_remove
>     component = integration.get_component()
>   File "/usr/src/homeassistant/homeassistant/loader.py", line 709, in get_component
>     cache[self.domain] = importlib.import_module(self.pkg_path)
>   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "/config/custom_components/tapo/__init__.py", line 8, in <module>
>     from custom_components.tapo.common_setup import (
>   File "/config/custom_components/tapo/common_setup.py", line 6, in <module>
>     from plugp100 import (
> ImportError: cannot import name 'TapoError' from 'plugp100' (/usr/local/lib/python3.10/site-packages/plugp100/__init__.py)`

Please update to 1.3.2

**Comment by razvanu** [comment]
How to update ? it's blocked in HA

![image](https://user-images.githubusercontent.com/15201014/210136938-c2a31ff9-1e7d-4fff-a0a8-fe5758cfc4d3.png)

**Comment by razvanu** [comment]
![image](https://user-images.githubusercontent.com/15201014/210137277-a9e020a5-1a28-4222-8251-8967f84d27de.png)
