### ISSUE TITLE
Integration crashes with python 3.9

### ISSUE THREAD

**Issue by mpinello** [petretiandrea/home-assistant-tapo-p100#318]
Hi @petretiandrea 

the integration is crashing on my homeassistant 2022.12.8 right after the upgrade, with the following error logs

```
2023-01-01 19:44:12.669 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.tapo.config_flow
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 728, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/loader.py", line 745, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/homeassistant/.homeassistant/custom_components/tapo/config_flow.py", line 38, in <module>
    class TapoConfigFlow(config_entries.ConfigFlow, domain=DOMAIN):
  File "/home/homeassistant/.homeassistant/custom_components/tapo/config_flow.py", line 45, in TapoConfigFlow
    self, user_input: dict[str, Any] | None = None
TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'NoneType'
2023-01-01 19:44:12.671 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading configuration flow for integration tapo: Exception importing custom_components.tapo.config_flow
```

I tried to uninstall / reinstall the integration from hacs, but without any luck.
No issues before upgrade to last hass version

**Comment by petretiandrea** [comment]
Try with v1.3.3

**Comment by mpinello** [comment]
I'm using 1.3.3
![image](https://user-images.githubusercontent.com/78625710/210187120-b0d49bbd-6d7c-43d7-a756-5b0556dc1fad.png)

**Comment by petretiandrea** [comment]
The problem seems to be related to python3.9

**Comment by avnovikov** [comment]
As we discussed a couple of days ago it is still there

**Comment by petretiandrea** [comment]
New version should fix. Anyway, I suggest you to upgrade to 3.10 due to deprecation around 3.9

**Comment by mpinello** [comment]
I confirm.
With 1.3.4 it’s working again 
Thanks mate!
