### ISSUE TITLE
switch P100 AttributeError: 'NoneType' object has no attribute 'model'

### ISSUE THREAD

**Issue by Ludy87** [petretiandrea/home-assistant-tapo-p100#333]
## Version of the integration
https://github.com/petretiandrea/home-assistant-tapo-p100/releases/tag/v1.3.7

## Configuration
```
P100
von TP-Link
Firmware: 1.4.10 Build 20211104 Rel. 35882
Hardware: 1.20.0
```

## Debug log

```text
Logger: homeassistant.components.light
Source: custom_components/tapo/light.py:45
Integration: Licht ([documentation](https://www.home-assistant.io/integrations/light), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+light%22))
First occurred: 15:52:20 (1 occurrences)
Last logged: 15:52:20

Error while setting up tapo platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 289, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tapo/light.py", line 30, in async_setup_entry
    _setup_from_coordinator(coordinator, async_add_devices)
  File "/config/custom_components/tapo/light.py", line 45, in _setup_from_coordinator
    if model.lower() in coordinator.data.model.lower():
AttributeError: 'NoneType' object has no attribute 'model'
```

```text
Logger: homeassistant.components.binary_sensor
Source: custom_components/tapo/sensor.py:61
Integration: Binärsensor ([documentation](https://www.home-assistant.io/integrations/binary_sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+binary_sensor%22))
First occurred: 15:52:20 (2 occurrences)
Last logged: 15:52:20

Error adding entities for domain binary_sensor with platform tapo
Error while setting up tapo platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 438, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 494, in _async_add_entity
    entity.add_to_platform_start(
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 633, in add_to_platform_start
    if self.unique_id is None or self.device_class is None:
  File "/config/custom_components/tapo/sensor.py", line 61, in unique_id
    return super().unique_id + "_" + self._sensor_config.name.replace(" ", "_")
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

```text

Logger: homeassistant.components.sensor
Source: custom_components/tapo/sensor.py:61
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 15:52:20 (2 occurrences)
Last logged: 15:52:20

Error adding entities for domain sensor with platform tapo
Error while setting up tapo platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 438, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 494, in _async_add_entity
    entity.add_to_platform_start(
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 633, in add_to_platform_start
    if self.unique_id is None or self.device_class is None:
  File "/config/custom_components/tapo/sensor.py", line 61, in unique_id
    return super().unique_id + "_" + self._sensor_config.name.replace(" ", "_")
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

```

**Comment by iciubotarasu** [comment]
i have the same issue

**Comment by petretiandrea** [comment]
Version 1.6.1 should fix this issue or log more detailed error
