### ISSUE TITLE
Error while setting up tapo

### ISSUE THREAD

**Issue by iciubotarasu** [petretiandrea/home-assistant-tapo-p100#355]
Hi, I am getting this in logs:
Logger: homeassistant.components.switch
Source: custom_components/tapo/switch.py:40
Integration: Switch (documentation, issues)
First occurred: 4:52:27 AM (2 occurrences)
Last logged: 4:52:27 AM

Error while setting up tapo platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 289, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tapo/switch.py", line 24, in async_setup_entry
    _setup_from_coordinator(coordinator, async_add_devices)
  File "/config/custom_components/tapo/switch.py", line 40, in _setup_from_coordinator
    if coordinator.data.model.lower() in SUPPORTED_DEVICE_AS_SWITCH:
AttributeError: 'NoneType' object has no attribute 'model'

**Comment by petretiandrea** [comment]
Version 1.6.1 should fix this issue or log more detailed error
