### ISSUE TITLE
Tapo L900 LED strip disconnected and cannot be connected 

### ISSUE THREAD

**Issue by MihaiKrieger** [petretiandrea/home-assistant-tapo-p100#375]
## Version of the integration

v1.6.0

## Configuration

Model: Tapo L900
hardware version: 1.0
Firmware Version: 1.0.16 Build 220902 Rel. 151030

```yaml
This error originated from a custom integration.

Logger: custom_components.tapo.config_flow
Source: custom_components/tapo/config_flow.py:72
Integration: Tapo Controller (documentation, issues)
First occurred: 11:07:21 (5 occurrences)
Last logged: 12:19:04

Failed to setup cannot connect
```

## Describe the bug

I have two identical devices connected to the same network. Both have been working correctly. 
One of them has stopped working and disconnected, although it is connected to the network and nothing has changed.
When trying to re-configure the LED strip, HA cannot connect to it, even though it is reachable on the network

## Debug log

```
2023-02-14 12:29:41.425 DEBUG (MainThread) [custom_components.tapo.common_setup] Finished fetching tapo data in 0.200 seconds (success: True)
2023-02-14 12:29:42.045 ERROR (MainThread) [homeassistant.components.androidtv.media_player] Failed to execute an ADB command. ADB connection re-establishing attempt in the next update. Error: Reading from 192.168.1.6:5555 timed out (9.0 seconds)
2023-02-14 12:29:44.042 WARNING (MainThread) [androidtv.adb_manager.adb_manager_async] Couldn't connect to 192.168.1.6:5555.  TcpTimeoutException: Connecting to 192.168.1.6:5555 timed out (1.0 seconds)
2023-02-14 12:30:11.348 DEBUG (MainThread) [custom_components.tapo.common_setup] Finished fetching tapo data in 0.124 seconds (success: True)
2023-02-14 12:30:22.055 ERROR (MainThread) [homeassistant.components.androidtv.media_player] Failed to execute an ADB command. ADB connection re-establishing attempt in the next update. Error: Reading from 192.168.1.6:5555 timed out (9.0 seconds)
2023-02-14 12:30:24.053 WARNING (MainThread) [androidtv.adb_manager.adb_manager_async] Couldn't connect to 192.168.1.6:5555.  TcpTimeoutException: Connecting to 192.168.1.6:5555 timed out (1.0 seconds)
2023-02-14 12:30:41.406 DEBUG (MainThread) [custom_components.tapo.common_setup] Finished fetching tapo data in 0.181 seconds (success: True)
2023-02-14 12:30:59.999 ERROR (MainThread) [frontend.js.latest.202302010] http://192.168.1.2:8123/lovelace-dashy/home-wellness:0:0 Uncaught 
2023-02-14 12:31:04.442 ERROR (MainThread) [frontend.js.latest.202302010] http://192.168.1.2:8123/lovelace-dashy/home-wellness:0:0 Uncaught 
2023-02-14 12:31:11.370 DEBUG (MainThread) [custom_components.tapo.common_setup] Finished fetching tapo data in 0.145 seconds (success: True)
2023-02-14 12:31:32.068 ERROR (MainThread) [homeassistant.components.androidtv.media_player] Failed to execute an ADB command. ADB connection re-establishing attempt in the next update. Error: Reading from 192.168.1.6:5555 timed out (9.0 seconds)
2023-02-14 12:31:34.096 WARNING (MainThread) [androidtv.adb_manager.adb_manager_async] Couldn't connect to 192.168.1.6:5555.  TcpTimeoutException: Connecting to 192.168.1.6:5555 timed out (1.0 seconds)
2023-02-14 12:31:41.094 INFO (MainThread) [googleapiclient.discovery_cache] file_cache is only supported with oauth2client<4.0.0
2023-02-14 12:31:41.380 DEBUG (MainThread) [custom_components.tapo.common_setup] Finished fetching tapo data in 0.156 seconds (success: True)
2023-02-14 12:31:43.223 ERROR (MainThread) [custom_components.tapo.config_flow] Failed to setup cannot connect 
2023-02-14 12:32:11.406 DEBUG (MainThread) [custom_components.tapo.common_setup] Finished fetching tapo data in 0.181 seconds (success: True)
2023-02-14 12:32:32.937 ERROR (MainThread) [homeassistant.components.androidtv.media_player] Failed to execute an ADB command. ADB connection re-establishing attempt in the next update. Error: Reading from 192.168.1.6:5555 timed out (9.0 seconds)
2023-02-14 12:32:34.103 WARNING (MainThread) [androidtv.adb_manager.adb_manager_async] Couldn't connect to 192.168.1.6:5555.  TcpTimeoutException: Connecting to 192.168.1.6:5555 timed out (1.0 seconds)
2023-02-14 12:32:41.470 DEBUG (MainThread) [custom_components.tapo.common_setup] Finished fetching tapo data in 0.246 seconds (success: True)
2023-02-14 12:33:11.386 DEBUG (MainThread) [custom_components.tapo.common_setup] Finished fetching tapo data in 0.160 seconds (success: True)
2023-02-14 12:33:12.120 ERROR (MainThread) [homeassistant.components.androidtv.media_player] Failed to execute an ADB command. ADB connection re-establishing attempt in the next update. Error: Reading from 192.168.1.6:5555 timed out (9.0 seconds)
2023-02-14 12:33:14.108 WARNING (MainThread) [androidtv.adb_manager.adb_manager_async] Couldn't connect to 192.168.1.6:5555.  TcpTimeoutException: Connecting to 192.168.1.6:5555 timed out (1.0 seconds)
2023-02-14 12:33:20.767 ERROR (MainThread) [frontend.js.latest.202302010] http://192.168.1.2:8123/lovelace-dashy/home-wellness:0:0 Uncaught 
2023-02-14 12:33:41.408 DEBUG (MainThread) [custom_components.tapo.common_setup] Finished fetching tapo data in 0.184 seconds (success: True)
2023-02-14 12:33:42.127 ERROR (MainThread) [homeassistant.components.androidtv.media_player] Failed to execute an ADB command. ADB connection re-establishing attempt in the next update. Error: Reading from 192.168.1.6:5555 timed out (9.0 seconds)
2023-02-14 12:33:44.114 WARNING (MainThread) [androidtv.adb_manager.adb_manager_async] Couldn't connect to 192.168.1.6:5555.  TcpTimeoutException: Connecting to 192.168.1.6:5555 timed out (1.0 seconds)
2023-02-14 12:33:54.587 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Running websocket_api script
2023-02-14 12:33:54.589 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Executing step call service
2023-02-14 12:34:52.215 ERROR (MainThread) [homeassistant.components.androidtv.media_player] Failed to execute an ADB command. ADB connection re-establishing attempt in the next update. Error: Reading from 192.168.1.6:5555 timed out (9.0 seconds)
2023-02-14 12:34:54.171 WARNING (MainThread) [androidtv.adb_manager.adb_manager_async] Couldn't connect to 192.168.1.6:5555.  TcpTimeoutException: Connecting to 192.168.1.6:5555 timed out (1.0 seconds)


```

**Comment by petretiandrea** [comment]
Logs releate to this integration seems to be ok, like this one:
`2023-02-14 12:31:11.370 DEBUG (MainThread) [custom_components.tapo.common_setup] Finished fetching tapo data in 0.145 seconds (success: True)`

**Comment by contrasenda** [comment]
Same problem here with only one of my two L900 LED stripes. Going back to 1.3.7.

```
Logger: homeassistant.components.switch
Source: custom_components/tapo/switch.py:40
Integration: Interruptor (documentation, issues)
First occurred: 20:49:09 (1 occurrences)
Last logged: 20:49:09

Error while setting up tapo platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tapo/switch.py", line 24, in async_setup_entry
    _setup_from_coordinator(coordinator, async_add_devices)
  File "/config/custom_components/tapo/switch.py", line 40, in _setup_from_coordinator
    if coordinator.data.model.lower() in SUPPORTED_DEVICE_AS_SWITCH:
AttributeError: 'NoneType' object has no attribute 'model'
```

```
Logger: homeassistant.components.light
Source: custom_components/tapo/light.py:52
Integration: Luz (documentation, issues)
First occurred: 20:49:09 (1 occurrences)
Last logged: 20:49:09

Error while setting up tapo platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tapo/light.py", line 37, in async_setup_entry
    _setup_from_coordinator(coordinator, async_add_devices)
  File "/config/custom_components/tapo/light.py", line 52, in _setup_from_coordinator
    if model.lower() in coordinator.data.model.lower():
AttributeError: 'NoneType' object has no attribute 'model
```

```
Logger: homeassistant.components.sensor
Source: custom_components/tapo/sensor.py:39
Integration: Sensor (documentation, issues)
First occurred: 20:49:09 (1 occurrences)
Last logged: 20:49:09

Error while setting up tapo platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tapo/sensor.py", line 39, in async_setup_entry
    if coordinator.data.model.lower() in SUPPORTED_DEVICE_AS_SWITCH_POWER_MONITOR:
AttributeError: 'NoneType' object has no attribute 'model'
```

```
Logger: homeassistant.components.binary_sensor
Source: custom_components/tapo/sensor.py:59
Integration: Sensor binario (documentation, issues)
First occurred: 20:49:09 (2 occurrences)
Last logged: 20:49:09

Error adding entities for domain binary_sensor with platform tapo
Error while setting up tapo platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 442, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 498, in _async_add_entity
    entity.add_to_platform_start(
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 190, in add_to_platform_start
    if self.unique_id is None or self.device_class is None:
  File "/config/custom_components/tapo/sensor.py", line 59, in unique_id
    return super().unique_id + "_" + self._sensor_config.name.replace(" ", "_")
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

**Comment by MihaiKrieger** [comment]
I could just re-add it normally without any error after I have reset the L900 to factory settings, by holding the button of the controller pressed for 10 seconds. Nor the perfect solution, but it is what it is.
I suspect a caching issue, although I cannot prove it.
