### ISSUE TITLE
Tapo plugs failed to connect after working fine for weeks

### ISSUE THREAD

**Issue by nickbuhling** [petretiandrea/home-assistant-tapo-p100#392]
Dear developer,

First of all let me thank you for providing this piece of software for free. It has been working flawlessly for weeks.

However, recently it stopped working and I don't really know why. I updated Home Assistant to 2023.3.1 and updated the integration to 1.6.1 and since the plugs don't connect anymore.

I have tried:
- Deleting the devices, deleting the integration from HACS, rebooting the whole system (also RPi), installing the integration from HACS, rebooting, adding plugs. I know my credentials are correct and the fixed IP is correct. I can also still control the plugs via the Tapo app. However I always get this message after a few seconds of loading:
![image](https://user-images.githubusercontent.com/36450606/224133268-d700977e-69fb-4c86-b124-5f4a1d4a004c.png)
- Reverting to an earlier backup (HA 2023.1 I think);
- Going back to integration version 1.5.0 which worked fine in the past;
- Adding a plug with YAML in configuration.yaml, which then also would not connect

Do you have any idea what could be the problem?

Here is a log message that I am getting, but since I deleted all the devices I don't really understand what is causing the log message:

> Logger: custom_components.tapo.config_flow
> Source: custom_components/tapo/config_flow.py:114
> Integration: tapo_p100 ([documentation](https://github.com/petretiandrea/home-assistant-tapo-p100), [issues](https://github.com/petretiandrea/home-assistant-tapo-p100/issues/))
> First occurred: 20:34:36 (1 occurrences)
> Last logged: 20:34:36
> Failed to setup cannot connect
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
>     return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
>   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
>     raise exceptions[0]
>   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
>     sock = await self._connect_sock(
>   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
>     await self.sock_connect(sock, address)
>   File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
>     return await fut
>   File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
>     raise OSError(err, f'Connect call failed {address}')
> OSError: [Errno 113] Connect call failed ('192.168.178.115', 80)
> The above exception was the direct cause of the following exception:
> Traceback (most recent call last):
>   File "/config/custom_components/tapo/config_flow.py", line 109, in _try_setup_api
>     await client.login()
>   File "/usr/local/lib/python3.10/site-packages/plugp100/api/tapo_api_client.py", line 41, in login
>     await self.client.login()
>   File "/usr/local/lib/python3.10/site-packages/plugp100/tapo_protocol/tapo_protocol_client.py", line 36, in login
>     await self._handshake()
>   File "/usr/local/lib/python3.10/site-packages/plugp100/tapo_protocol/tapo_protocol_client.py", line 94, in _handshake
>     response = await self.http.async_make_post(self.url, json=request_body)
>   File "/usr/local/lib/python3.10/site-packages/plugp100/utils/http_client.py", line 18, in async_make_post
>     async with self.session.post(url, json=json, headers=self.common_headers) as response:
>   File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
>     self._resp = await self._coro
>   File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 536, in _request
>     conn = await self._connector.connect(
>   File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 540, in connect
>     proto = await self._create_connection(req, traces, timeout)
>   File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 901, in _create_connection
>     _, proto = await self._create_direct_connection(req, traces, timeout)
>   File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
>     raise last_exc
>   File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
>     transp, proto = await self._wrap_create_connection(
>   File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
>     raise client_error(req.connection_key, exc) from exc
> aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.178.115:80 ssl:default [Connect call failed ('192.168.178.115', 80)]
> The above exception was the direct cause of the following exception:
> Traceback (most recent call last):
>   File "/config/custom_components/tapo/config_flow.py", line 60, in async_step_user
>     api = await self._try_setup_api(user_input)
>   File "/config/custom_components/tapo/config_flow.py", line 114, in _try_setup_api
>     raise CannotConnect from error
> custom_components.tapo.config_flow.CannotConnect

**Comment by nickbuhling** [comment]
update since I dont seem to be able to delete this issue:

The issue where my Tapo plugs would not connect was fixed after rebooting my wifi router twice.. Why? No idea, but everything is working now
