### ISSUE TITLE
Unexpected exception

### ISSUE THREAD

**Issue by Psytoshgen** [petretiandrea/home-assistant-tapo-p100#397]
Integration version - latest 
configured via master
Home assistant supervised in docker, raspberry pi 400
Device - p100

Logger: custom_components.tapo.common_setup
Source: helpers/update_coordinator.py:211 
Integration: Tapo Controller (documentation, issues) 
First occurred: 09:32:01 (2 occurrences) 
Last logged: 09:32:50

Failed to setup Unexpected exception:
Traceback (most recent call last):
  File "/config/custom_components/tapo/common_setup.py", line 123, in _update_with_fallback
    return await self.api.get_state(
  File "/usr/local/lib/python3.10/site-packages/plugp100/api/tapo_api_client.py", line 45, in get_state
    state_dict = await self.client.send_tapo_request(GetDeviceInfoMethod(None))
  File "/usr/local/lib/python3.10/site-packages/plugp100/tapo_protocol/tapo_protocol_client.py", line 55, in send_tapo_request
    dim_encrypted = self.tp_link_cipher.encrypt(jsons.dumps(method))
AttributeError: 'NoneType' object has no attribute 'encrypt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/tapo/common_setup.py", line 113, in _async_update_data
    return await self._update_with_fallback()
  File "/config/custom_components/tapo/common_setup.py", line 129, in _update_with_fallback
    return await self._update_with_fallback(False)
  File "/config/custom_components/tapo/common_setup.py", line 123, in _update_with_fallback
    return await self.api.get_state(
  File "/usr/local/lib/python3.10/site-packages/plugp100/api/tapo_api_client.py", line 45, in get_state
    state_dict = await self.client.send_tapo_request(GetDeviceInfoMethod(None))
  File "/usr/local/lib/python3.10/site-packages/plugp100/tapo_protocol/tapo_protocol_client.py", line 63, in send_tapo_request
    response = await self.http.async_make_post_cookie(f"{self.url}?token={self.token}", request_body,
  File "/usr/local/lib/python3.10/site-packages/plugp100/utils/http_client.py", line 23, in async_make_post_cookie
    async with self.session.post(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/tapo/common_setup.py", line 112, in _async_update_data
    async with async_timeout.timeout(10):
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 129, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 239, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/tapo/common_setup.py", line 119, in _async_update_data
    raise UpdateFailed(f"Unexpected exception: {str(exception)}") from exception
homeassistant.helpers.update_coordinator.UpdateFailed: Unexpected exception: 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/tapo/common_setup.py", line 74, in setup_tapo_coordinator
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 211, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady: Unexpected exception:

**Comment by novotnej** [comment]
I am also experiencing the same issue, this happened immediately after upgrading HA, and subsequently upgrading all plugins

Home Assistant 2023.3.6
Frontend 20230309.1 - latest

**Comment by github4www** [comment]
Same for me.

**Comment by mfabiani53** [comment]
+1 for me

**Comment by Danifly80** [comment]
+1 same

**Comment by RyanTunstall** [comment]
Same for me.

**Comment by mfabiani53** [comment]
Nothing from the developer?

**Comment by xteaun** [comment]
Same here!

**Comment by Takabrycheri** [comment]
Still no answer?

**Comment by KentuckyMC** [comment]
Same issue

**Comment by KentuckyMC** [comment]
Still have the unavailable devices under this integration. I can see the p110 plug working in the Tapo app itself. Not in Home Assistant unfortunately. Any change to figure out what's goin on?

**Comment by petretiandrea** [comment]
Try with v2.0.0

**Comment by RyanTunstall** [comment]
Hi petreiandrea. Thanks for looking at this. Unfortunately, I still seem to have Tapo devices frequently going unavailable unexpectedly in 2.0.0 and 2.0.1
