### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by Dividing6043** [petretiandrea/home-assistant-tapo-p100#411]
I have 4x P100 Tapo smart plugs. 3 of these will no longer work using this integration. I get the following error when trying to set them up:

Failed to Connect

Here are the logs:

Failed to setup cannot connect

Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 90, in _get_unique_data_from_api
    state = await api.get_state()
  File "/usr/local/lib/python3.10/site-packages/plugp100/api/tapo_api_client.py", line 45, in get_state
    state_dict = await self.client.send_tapo_request(GetDeviceInfoMethod(None))
  File "/usr/local/lib/python3.10/site-packages/plugp100/tapo_protocol/tapo_protocol_client.py", line 68, in send_tapo_request
    self._validate_response(resp_dict)
  File "/usr/local/lib/python3.10/site-packages/plugp100/tapo_protocol/tapo_protocol_client.py", line 154, in _validate_response
    raise TapoException.from_error_code(resp['error_code'])
plugp100.domain.tapo_exception.TapoException: Returned unknown error_code: 9999

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 61, in async_step_user
    unique_data = await self._get_unique_data_from_api(api)
  File "/config/custom_components/tapo/config_flow.py", line 93, in _get_unique_data_from_api
    self._raise_from_tapo_exception(error)
  File "/config/custom_components/tapo/config_flow.py", line 121, in _raise_from_tapo_exception
    raise CannotConnect from exception
custom_components.tapo.config_flow.CannotConnect

I have tried removing all devices, removing the HACS integration and then re-adding with the same error.
I am using v1.6.1
Home Assistant 2023.5.4 
Supervisor 2023.04.1 
Operating System 10.1 
Frontend 20230503.3 - latest

The one device I am able to add is a newer P100 running firmware 1.1.5 (hardware 2.0)
The devices that no longer work are running firmware 1.4.16 (hardware 1.20.0)

All devices work fine in the Tapo app, so this is not a connectivity issue.

Any ideas?

**Comment by Dividing6043** [comment]
And today it is working... Weird!
