### ISSUE TITLE
New firmware for P100 plugs stopped working

### ISSUE THREAD

**Issue by Kiksemanden** [petretiandrea/home-assistant-tapo-p100#415]
## Configuration
 Tapo P100 firmware 1.4.16 Build 20230224 rel. 59299

```yaml
Add your logs here.
```

## Describe the bug

The plugs cannot be controlled by Home Assistant after the plugs have auto-updated to the above mentioned firmware version

## Debug log

```text

2023-06-20 11:40:18.409 WARNING (SyncWorker_0) [homeassistant.util.yaml.loader] YAML file /config/configuration.yaml contains duplicate key "script". Check lines 30 and 33
2023-06-20 11:40:18.816 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-20 11:40:18.819 WARNING (SyncWorker_4) [homeassistant.loader] We found a custom integration tapo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-20 11:40:29.205 WARNING (MainThread) [hass_nabucasa.cloud_api] Fetched https://alexa-api.nabucasa.com/access_token (400)
2023-06-20 11:40:40.684 WARNING (MainThread) [homeassistant.components.systemmonitor.sensor] Cannot read CPU / processor temperature information
2023-06-20 11:40:49.803 ERROR (MainThread) [homeassistant.components.switch] Error while setting up tapo platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 320, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tapo/switch.py", line 24, in async_setup_entry
    _setup_from_coordinator(coordinator, async_add_devices)
  File "/config/custom_components/tapo/switch.py", line 40, in _setup_from_coordinator
    if coordinator.data.model.lower() in SUPPORTED_DEVICE_AS_SWITCH:
       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'model'
2023-06-20 11:40:49.817 ERROR (MainThread) [homeassistant.components.light] Error while setting up tapo platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 320, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tapo/light.py", line 37, in async_setup_entry
    _setup_from_coordinator(coordinator, async_add_devices)
  File "/config/custom_components/tapo/light.py", line 52, in _setup_from_coordinator
    if model.lower() in coordinator.data.model.lower():
                        ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'model'
2023-06-20 11:40:49.832 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up tapo platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 320, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tapo/sensor.py", line 40, in async_setup_entry
    _setup_from_coordinator(coordinator, async_add_devices)
  File "/config/custom_components/tapo/sensor.py", line 56, in _setup_from_coordinator
    if coordinator.data.model.lower() in SUPPORTED_DEVICE_AS_SWITCH_POWER_MONITOR:
       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'model'
2023-06-20 11:40:49.848 ERROR (MainThread) [homeassistant.components.switch] Error while setting up tapo platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 320, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tapo/switch.py", line 24, in async_setup_entry
    _setup_from_coordinator(coordinator, async_add_devices)
  File "/config/custom_components/tapo/switch.py", line 40, in _setup_from_coordinator
    if coordinator.data.model.lower() in SUPPORTED_DEVICE_AS_SWITCH:
       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'model'
2023-06-20 11:40:49.858 ERROR (MainThread) [homeassistant.components.light] Error while setting up tapo platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 320, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tapo/light.py", line 37, in async_setup_entry
    _setup_from_coordinator(coordinator, async_add_devices)
  File "/config/custom_components/tapo/light.py", line 52, in _setup_from_coordinator
    if model.lower() in coordinator.data.model.lower():
                        ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'model'
2023-06-20 11:40:49.865 ERROR (MainThread) [homeassistant.components.binary_sensor] Error adding entities for domain binary_sensor with platform tapo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 471, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 528, in _async_add_entity
    entity.add_to_platform_start(
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 195, in add_to_platform_start
    if self.unique_id is None or self.device_class is None:
       ^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/sensor.py", line 77, in unique_id
    return super().unique_id + "_" + self._sensor_config.name.replace(" ", "_")
           ~~~~~~~~~~~~~~~~~~^~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
2023-06-20 11:40:49.880 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up tapo platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 320, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tapo/sensor.py", line 40, in async_setup_entry
    _setup_from_coordinator(coordinator, async_add_devices)
  File "/config/custom_components/tapo/sensor.py", line 56, in _setup_from_coordinator
    if coordinator.data.model.lower() in SUPPORTED_DEVICE_AS_SWITCH_POWER_MONITOR:
       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'model'
2023-06-20 11:40:49.894 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up tapo platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 328, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 471, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 528, in _async_add_entity
    entity.add_to_platform_start(
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 195, in add_to_platform_start
    if self.unique_id is None or self.device_class is None:
       ^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/sensor.py", line 77, in unique_id
    return super().unique_id + "_" + self._sensor_config.name.replace(" ", "_")
           ~~~~~~~~~~~~~~~~~~^~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
2023-06-20 11:40:49.917 ERROR (MainThread) [homeassistant.components.binary_sensor] Error adding entities for domain binary_sensor with platform tapo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 471, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 528, in _async_add_entity
    entity.add_to_platform_start(
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 195, in add_to_platform_start
    if self.unique_id is None or self.device_class is None:
       ^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/sensor.py", line 77, in unique_id
    return super().unique_id + "_" + self._sensor_config.name.replace(" ", "_")
           ~~~~~~~~~~~~~~~~~~^~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
2023-06-20 11:40:50.045 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up tapo platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 328, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 471, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 528, in _async_add_entity
    entity.add_to_platform_start(
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 195, in add_to_platform_start
    if self.unique_id is None or self.device_class is None:
       ^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/sensor.py", line 77, in unique_id
    return super().unique_id + "_" + self._sensor_config.name.replace(" ", "_")
           ~~~~~~~~~~~~~~~~~~^~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
2023-06-20 11:40:50.056 ERROR (MainThread) [homeassistant.components.switch] Error while setting up tapo platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 320, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tapo/switch.py", line 24, in async_setup_entry
    _setup_from_coordinator(coordinator, async_add_devices)
  File "/config/custom_components/tapo/switch.py", line 40, in _setup_from_coordinator
    if coordinator.data.model.lower() in SUPPORTED_DEVICE_AS_SWITCH:
       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'model'
2023-06-20 11:40:50.072 ERROR (MainThread) [homeassistant.components.light] Error while setting up tapo platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 320, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tapo/light.py", line 37, in async_setup_entry
    _setup_from_coordinator(coordinator, async_add_devices)
  File "/config/custom_components/tapo/light.py", line 52, in _setup_from_coordinator
    if model.lower() in coordinator.data.model.lower():
                        ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'model'
2023-06-20 11:40:50.082 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up tapo platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 320, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tapo/sensor.py", line 40, in async_setup_entry
    _setup_from_coordinator(coordinator, async_add_devices)
  File "/config/custom_components/tapo/sensor.py", line 56, in _setup_from_coordinator
    if coordinator.data.model.lower() in SUPPORTED_DEVICE_AS_SWITCH_POWER_MONITOR:
       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'model'
2023-06-20 11:40:50.106 ERROR (MainThread) [homeassistant.components.binary_sensor] Error adding entities for domain binary_sensor with platform tapo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 471, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 528, in _async_add_entity
    entity.add_to_platform_start(
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 195, in add_to_platform_start
    if self.unique_id is None or self.device_class is None:
       ^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/sensor.py", line 77, in unique_id
    return super().unique_id + "_" + self._sensor_config.name.replace(" ", "_")
           ~~~~~~~~~~~~~~~~~~^~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
2023-06-20 11:40:50.118 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up tapo platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 328, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 471, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 528, in _async_add_entity
    entity.add_to_platform_start(
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 195, in add_to_platform_start
    if self.unique_id is None or self.device_class is None:
       ^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/sensor.py", line 77, in unique_id
    return super().unique_id + "_" + self._sensor_config.name.replace(" ", "_")
           ~~~~~~~~~~~~~~~~~~^~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
2023-06-20 11:40:52.206 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Controller RGB/WW/CW DE3513' for flux_led integration not ready yet: [Errno 113] Connect call failed ('192.168.1.171', 5577); Retrying in background
2023-06-20 11:40:52.213 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Controller RGB/WW/CW DE2007' for flux_led integration not ready yet: [Errno 113] Connect call failed ('192.168.1.80', 5577); Retrying in background
2023-06-20 11:40:53.231 WARNING (MainThread) [homeassistant.config_entries] Config entry 'WLED lille' for wled integration not ready yet: Invalid response from API: Error occurred while communicating with WLED device at 192.168.1.187; Retrying in background
2023-06-20 11:40:53.235 WARNING (MainThread) [homeassistant.config_entries] Config entry 'WLED pc' for wled integration not ready yet: Invalid response from API: Error occurred while communicating with WLED device at 192.168.1.69; Retrying in background
2023-06-20 11:43:00.749 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.stromforsyning or it is/they are currently not available
2023-06-20 11:43:01.567 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.stromforsyning or it is/they are currently not available
2023-06-20 11:48:39.119 ERROR (MainThread) [custom_components.tapo.config_flow] Tapo exception 9999
2023-06-20 11:48:39.135 ERROR (MainThread) [custom_components.tapo.config_flow] Failed to setup cannot connect 
Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 90, in _get_unique_data_from_api
    state = await api.get_state()
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_api_client.py", line 45, in get_state
    state_dict = await self.client.send_tapo_request(GetDeviceInfoMethod(None))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/tapo_protocol/tapo_protocol_client.py", line 68, in send_tapo_request
    self._validate_response(resp_dict)
  File "/usr/local/lib/python3.11/site-packages/plugp100/tapo_protocol/tapo_protocol_client.py", line 154, in _validate_response
    raise TapoException.from_error_code(resp['error_code'])
plugp100.domain.tapo_exception.TapoException: Returned unknown error_code: 9999

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 61, in async_step_user
    unique_data = await self._get_unique_data_from_api(api)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/config_flow.py", line 93, in _get_unique_data_from_api
    self._raise_from_tapo_exception(error)
  File "/config/custom_components/tapo/config_flow.py", line 121, in _raise_from_tapo_exception
    raise CannotConnect from exception
custom_components.tapo.config_flow.CannotConnect
2023-06-20 11:55:27.202 WARNING (Thread-7) [pychromecast.socket_client] [MiTV-AESP0(192.168.1.135):8009] Heartbeat timeout, resetting connection
2023-06-20 11:56:26.184 WARNING (Thread-7) [pychromecast.socket_client] [MiTV-AESP0(192.168.1.135):8009] Heartbeat timeout, resetting connection
2023-06-20 11:56:53.461 WARNING (Thread-7) [pychromecast.socket_client] [MiTV-AESP0(192.168.1.135):8009] Heartbeat timeout, resetting connection
2023-06-20 11:57:23.492 ERROR (Thread-7) [pychromecast.socket_client] [MiTV-AESP0(192.168.1.135):8009] Failed to connect to service ServiceInfo(type='mdns', data='MiTV-AESP0-f5ff8d44ad5c5118f4973cfa62290ac5._googlecast._tcp.local.'), retrying in 5.0s
2023-06-20 12:01:12.398 WARNING (Thread-7) [pychromecast.socket_client] [MiTV-AESP0(192.168.1.135):8009] Heartbeat timeout, resetting connection
2023-06-20 12:01:42.436 ERROR (Thread-7) [pychromecast.socket_client] [MiTV-AESP0(192.168.1.135):8009] Failed to connect to service ServiceInfo(type='mdns', data='MiTV-AESP0-f5ff8d44ad5c5118f4973cfa62290ac5._googlecast._tcp.local.'), retrying in 5.0s


```

**Comment by alesc** [comment]
Same error here, but my plugs are not in latest firmware : 

```
P100
par TP-Link
Firmware: 1.4.10 Build 20211104 Rel. 35882
Matériel : 1.20.0
```

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 320, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tapo/sensor.py", line 40, in async_setup_entry
    _setup_from_coordinator(coordinator, async_add_devices)
  File "/config/custom_components/tapo/sensor.py", line 56, in _setup_from_coordinator
    if coordinator.data.model.lower() in SUPPORTED_DEVICE_AS_SWITCH_POWER_MONITOR:
       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'model'
```

**Comment by Kiksemanden** [comment]
I have 4 P100 plugs 3 of them does not work on HA and has the latest firmware. The last one is not updated and works fine.

**Comment by petretiandrea** [comment]
To fix this I need someone runs a plugp100 python scripts -> https://github.com/petretiandrea/plugp100.

So install plugp100 `pip install plugp100==2.5.1`

Now runs:
```python
import asyncio

from plugp100 import TapoApiClient, TapoApiClientConfig
from plugp100.domain.light_effect import LightEffectPreset


async def main():
    # create generic tapo api
    config = TapoApiClientConfig("<ip>", "<email>", "<passwd>")
    sw = TapoApiClient.from_config(config)
    await sw.login()
    state = await sw.get_state()
    print(state.get_unmapped_state())
```

**Comment by Kiksemanden** [comment]
My p100 came online again on HA and worked fine the past day. I didn't make any changes.

**Comment by r4yzs** [comment]
Hello the same here.

`TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'`
