### ISSUE TITLE
Tapo L920 can't be integrated: connection failed

### ISSUE THREAD

**Issue by alp82** [petretiandrea/home-assistant-tapo-p100#421]
## Version of the integration

Version 1.7.1

## Configuration

Device: Tapo L920
Firmware Version: 1.0.9 Build 220422 Rel. 150004

```yaml
2023-07-03 10:11:18.101 ERROR (MainThread) [custom_components.tapo.config_flow] Failed to setup cannot connect 
Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 162, in _try_setup_api
    await client.login()
  File "/config/deps/lib/python3.11/site-packages/plugp100/api/tapo_api_client.py", line 41, in login
    await self.client.login()
  File "/config/deps/lib/python3.11/site-packages/plugp100/tapo_protocol/tapo_protocol_client.py", line 36, in login
    await self._handshake()
  File "/config/deps/lib/python3.11/site-packages/plugp100/tapo_protocol/tapo_protocol_client.py", line 94, in _handshake
    response = await self.http.async_make_post(self.url, json=request_body)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/deps/lib/python3.11/site-packages/plugp100/utils/http_client.py", line 18, in async_make_post
    async with self.session.post(url, json=json, headers=self.common_headers) as response:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 899, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 88, in async_step_user
    api = await self._try_setup_api(user_input)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/config_flow.py", line 167, in _try_setup_api
    raise CannotConnect from error
custom_components.tapo.config_flow.CannotConnect
```

## Describe the bug

I downloaded the Tapo integration in HACS and restarted my HA. When I try to add a new Tapo Integration and enter the correct IP, email and password, I get an error saying "cannot connect".

## Debug log

```text

```

**Comment by alp82** [comment]
After reading https://github.com/petretiandrea/home-assistant-tapo-p100/issues/122#issuecomment-1117589613 I figured it might not like the "#" character in my password.

I went to my Tapo app and changed my password to only container lowercase chars and numbers. After a while, when I tried it again, it worked.
