### ISSUE TITLE
H100 not working

### ISSUE THREAD

**Issue by tuliuliucroman** [petretiandrea/home-assistant-tapo-p100#432]
After updating the Tapo Controller app, the H100 connected to it does not work

**Comment by hamzahjamad** [comment]
There are issue created here #431 , 
the maintainer still working on H100 integration.
Link [here](https://github.com/petretiandrea/home-assistant-tapo-p100/issues/354#issuecomment-1612502388)

**Comment by tuliuliucroman** [comment]
Logger: homeassistant.config_entries
Source: custom_components/tapo/utils.py:15
Integration: Tapo Controller ([documentation](https://github.com/petretiandrea/home-assistant-tapo-p100), [issues](https://github.com/petretiandrea/home-assistant-tapo-p100/issues/))
First occurred: 10:20:00 (2 occurrences)
Last logged: 10:27:57

Error setting up entry Умный центр управления for tapo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/__init__.py", line 48, in async_setup_entry
    raise error
  File "/config/custom_components/tapo/__init__.py", line 37, in async_setup_entry
    coordinator = value_or_raise(
                  ^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/utils.py", line 15, in value_or_raise
    raise value_or_error
custom_components.tapo.common_setup.DeviceNotSupported: Device 192.168.0.95 not supported!

**Comment by petretiandrea** [comment]
With 2.2.0 you can add hub with a limited supports
