### ISSUE TITLE
P105: `error_code: -1012  msg: No message` after update to 2.0.1

### ISSUE THREAD

**Issue by hldh214** [petretiandrea/home-assistant-tapo-p100#433]
## Version of the integration
2.0.1

## Configuration
1.3.5 Build 20230113 Rel. 66585

## Describe the bug

I am experiencing an issue with the "on/off" switch for `P105` after updating to version 2.0.1. The error log indicates that it's not functioning properly. I have attempted to resolve the issue by fully deleting the tapo folder and re-installing the app, but the problem persists. As a temporary solution, I have downgraded to version 1.7.1.

## Debug log

```text
2023-07-11 20:40:30.841 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139634166409040] Returned unknown error_code: -1012  msg: No message
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 205, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1957, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1997, in _execute_service
    return await cast(
           ^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 845, in entity_service_call
    response_data = task.result()  # pop exception if have
                    ^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1192, in async_request_call
    return await coro
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 889, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/tapo/switch.py", line 61, in async_turn_on
    value_or_raise(await self.device.on())
  File "/config/custom_components/tapo/utils.py", line 15, in value_or_raise
    raise value_or_error
plugp100.responses.tapo_exception.TapoException: Returned unknown error_code: -1012  msg: No message
```

https://github.com/petretiandrea/home-assistant-tapo-p100/blob/0d5827c305cf43fef8c958ae18b41944776d80b4/custom_components/tapo/switch.py#L59-L63

**Comment by koshisan** [comment]
I have the same problem. Unfortunately 1.7.1 is not available through HACS anymore, so no work around currently...

**Comment by koshisan** [comment]
I did a manual downgrade to 1.7.1 and now it doesn't even detect the switch anymore after re-adding the device. Only the sensors for wifi strength and overheat. I decided to buy sonoff zigbee switches instead, since it just doesn't seem to worth the hassle...

**Comment by hldh214** [comment]
> it doesn't even detect the switch anymore after re-adding the device

Yes, I've also encountered this and resolved it by searching for the switch in the HA's `entities` page. I tried interacting with it a little bit, and then it appeared on the Tapo integrations page.

**Comment by koshisan** [comment]
@hldh214 Indeed, there it is! Thank you!

**Comment by Tatooiner** [comment]
I have the same issue.

**Version of the integration**
2.12.2

**Configuration**
1.3.6 Build 20230308 Rel. 52591
