### ISSUE TITLE
Failed to set up 

### ISSUE THREAD

**Issue by ckortenhorst** [petretiandrea/home-assistant-tapo-p100#439]
## Configuration

```yaml
**2023-07-14 22:26:28.750 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-07-14 22:26:28.751 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration emporia_vue which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-07-14 22:26:28.752 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tapo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-07-14 22:26:28.752 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration midea_dehumidifier_lan which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-07-14 22:26:28.754 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration solis which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-07-14 22:26:42.400 ERROR (MainThread) [homeassistant.config_entries] Error importing platform config_flow from integration tapo to set up tapo configuration entry: No module named 'custom_components.tapo.options_flow_handler'
2023-07-14 22:26:42.426 ERROR (MainThread) [homeassistant.config_entries] Error importing platform config_flow from integration tapo to set up tapo configuration entry: No module named 'custom_components.tapo.options_flow_handler'
2023-07-14 22:26:42.429 ERROR (MainThread) [homeassistant.config_entries] Error importing platform config_flow from integration tapo to set up tapo configuration entry: No module named 'custom_components.tapo.options_flow_handler'
2023-07-14 22:26:42.432 ERROR (MainThread) [homeassistant.config_entries] Error importing platform config_flow from integration tapo to set up tapo configuration entry: No module named 'custom_components.tapo.options_flow_handler'
2023-07-14 22:26:42.436 ERROR (MainThread) [homeassistant.config_entries] Error importing platform config_flow from integration tapo to set up tapo configuration entry: No module named 'custom_components.tapo.options_flow_handler'
2023-07-14 22:26:42.439 ERROR (MainThread) [homeassistant.config_entries] Error importing platform config_flow from integration tapo to set up tapo configuration entry: No module named 'custom_components.tapo.options_flow_handler'
2023-07-14 22:26:42.442 ERROR (MainThread) [homeassistant.config_entries] Error importing platform config_flow from integration tapo to set up tapo configuration entry: No module named 'custom_components.tapo.options_flow_handler'
2023-07-14 22:26:42.445 ERROR (MainThread) [homeassistant.config_entries] Error importing platform config_flow from integration tapo to set up tapo configuration entry: No module named 'custom_components.tapo.options_flow_handler'
2023-07-14 22:26:55.516 WARNING (SyncWorker_0) [midea_beautiful.lan] Error getting device capabilities for sn=000000P0000000Q1C43960BC******** id=15283211631**** address=192.168***** version=3, cause Unable to send data after 5 retries, last error timed out for 000000P0000000Q1C43960BC******** (15283211631****)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/midea_beautiful/lan.py", line 809, in identify
    responses = self._status(cmd, cloud if use_cloud else None)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/midea_beautiful/lan.py", line 540, in _status
    responses = self.appliance_send(data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/midea_beautiful/lan.py", line 685, in appliance_send
    return self._appliance_send_8370(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/midea_beautiful/lan.py", line 590, in _appliance_send_8370
    if packets := self._retry_send(original_data, response_buf):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/midea_beautiful/lan.py", line 670, in _retry_send
    packets = self.appliance_send(data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/midea_beautiful/lan.py", line 685, in appliance_send
    return self._appliance_send_8370(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/midea_beautiful/lan.py", line 590, in _appliance_send_8370
    if packets := self._retry_send(original_data, response_buf):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/midea_beautiful/lan.py", line 670, in _retry_send
    packets = self.appliance_send(data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/midea_beautiful/lan.py", line 685, in appliance_send
    return self._appliance_send_8370(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/midea_beautiful/lan.py", line 590, in _appliance_send_8370
    if packets := self._retry_send(original_data, response_buf):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/midea_beautiful/lan.py", line 675, in _retry_send
    raise MideaNetworkError(
midea_beautiful.exceptions.MideaNetworkError: Unable to send data after 5 retries, last error timed out for 000000P0000000Q1C43960BC******** (15283211631****)
2023-07-14 22:27:14.030 WARNING (SyncWorker_6) [midea_beautiful.lan] Error getting device capabilities for sn=000000P0000000Q1C43960BC******** id=15393162794**** address=192.168***** version=3, cause Unable to send data after 5 retries, last error timed out for 000000P0000000Q1C43960BC******** (15393162794****)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/midea_beautiful/lan.py", line 809, in identify
    responses = self._status(cmd, cloud if use_cloud else None)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/midea_beautiful/lan.py", line 540, in _status
    responses = self.appliance_send(data)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/midea_beautiful/lan.py", line 685, in appliance_send
    return self._appliance_send_8370(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/midea_beautiful/lan.py", line 590, in _appliance_send_8370
    if packets := self._retry_send(original_data, response_buf):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/midea_beautiful/lan.py", line 670, in _retry_send
    packets = self.appliance_send(data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/midea_beautiful/lan.py", line 685, in appliance_send
    return self._appliance_send_8370(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/midea_beautiful/lan.py", line 590, in _appliance_send_8370
    if packets := self._retry_send(original_data, response_buf):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/midea_beautiful/lan.py", line 670, in _retry_send
    packets = self.appliance_send(data)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/midea_beautiful/lan.py", line 685, in appliance_send
    return self._appliance_send_8370(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/midea_beautiful/lan.py", line 590, in _appliance_send_8370
    if packets := self._retry_send(original_data, response_buf):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/midea_beautiful/lan.py", line 675, in _retry_send
    raise MideaNetworkError(
midea_beautiful.exceptions.MideaNetworkError: Unable to send data after 5 retries, last error timed out for 000000P0000000Q1C43960BC******** (15393162794****)
2023-07-14 22:27:19.373 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({{ ([ states('sensor.totale_channel_a_energy'),
      states('sensor.totale_channel_b_energy'),
      states('sensor.totale_channel_c_energy') ]
      | map('float') | sum) | round(2) }}) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1908, in forgiving_float_filter
    return float(value)
           ^^^^^^^^^^^^
ValueError: could not convert string to float: 'unknown'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 563, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2179, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 4, in top-level template code
  File "/usr/local/lib/python3.11/site-packages/jinja2/async_utils.py", line 45, in wrapper
    return normal_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/filters.py", line 1295, in sync_do_sum
    return sum(iterable, start)  # type: ignore[no-any-return, call-overload]
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/filters.py", line 1468, in sync_do_map
    yield func(item)
          ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/filters.py", line 1712, in func
    return context.environment.call_filter(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 564, in call_filter
    return self._filter_test_common(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 545, in _filter_test_common
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1911, in forgiving_float_filter
    raise_no_default("float", value)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1609, in raise_no_default
    raise ValueError(
ValueError: Template error: float got invalid input 'unknown' when rendering template '{{ ([ states('sensor.totale_channel_a_energy'),
      states('sensor.totale_channel_b_energy'),
      states('sensor.totale_channel_c_energy') ]
      | map('float') | sum) | round(2) }}' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 684, in async_render_to_info
    render_info._result = self.async_render(variables, strict=strict, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 565, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: float got invalid input 'unknown' when rendering template '{{ ([ states('sensor.totale_channel_a_energy'),
      states('sensor.totale_channel_b_energy'),
      states('sensor.totale_channel_c_energy') ]
      | map('float') | sum) | round(2) }}' but no default was specified
2023-07-14 22:27:19.383 ERROR (MainThread) [homeassistant.helpers.template_entity] TemplateError('ValueError: Template error: float got invalid input 'unknown' when rendering template '{{ ([ states('sensor.totale_channel_a_energy'),
      states('sensor.totale_channel_b_energy'),
      states('sensor.totale_channel_c_energy') ]
      | map('float') | sum) | round(2) }}' but no default was specified') while processing template 'Template<template=({{ ([ states('sensor.totale_channel_a_energy'),
      states('sensor.totale_channel_b_energy'),
      states('sensor.totale_channel_c_energy') ]
      | map('float') | sum) | round(2) }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.office_total_kwh'
2023-07-14 22:51:35.794 ERROR (MainThread) [homeassistant.config_entries] Error importing platform config_flow from integration tapo to set up tapo configuration entry: No module named 'custom_components.tapo.options_flow_handler'
**

```

## Describe the bug

In home assistant getting following error 
<img width="641" alt="image" src="https://github.com/petretiandrea/home-assistant-tapo-p100/assets/5760635/c47c3f06-1cea-4a24-acdf-931d0b8e14d0">

## Debug log

```text

Add your logs here.

```

**Comment by petretiandrea** [comment]
`midea_beautiful.lan` Not related to this integration
