### ISSUE TITLE
light effects not saved in scenes/automations

### ISSUE THREAD

**Issue by stevenazari** [petretiandrea/home-assistant-tapo-p100#454]
## Configuration

Device Name: Office Kallax
Firmware: 1.0.9 build 220727 rel.150045

```yaml
Not sure what logs you refer to, HA logs are below.

```

## Describe the bug

Trying to create an automation that will turn on the Tapo light strip that is on my ikea Kallax shelf, turning on isn't the problem, however when trying to use the effects of the light strip, it will not save and produces the below error, the options also does not indicate an effect has been chosen, the only way to know is to look at the light that switches to the effect. 

Although the scene asks to set the lights to the desired setting, doing so does not prompt the user to save.

## Debug log

```text

Logger: homeassistant.components.automation.office_lights_20
Source: custom_components/tapo/light.py:169
Integration: Automation (documentation, issues)
First occurred: 8 July 2023 at 12:42:01 (26 occurrences)
Last logged: 22:14:04

Office lights 20: Error executing script. Unexpected error for call_service at pos 1: 'rainbow'
While executing automation automation.office_lights_20
Traceback (most recent call last):
  File "/usr/src/h
[home-assistant_tapo_2023-07-20T21-15-58.477Z.log](https://github.com/petretiandrea/home-assistant-tapo-p100/files/12114237/home-assistant_tapo_2023-07-20T21-15-58.477Z.log)
omeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 703, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 665, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1957, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1997, in _execute_service
    return await cast(
           ^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 845, in entity_service_call
    response_data = task.result()  # pop exception if have
                    ^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1192, in async_request_call
    return await coro
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 889, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/scene/__init__.py", line 114, in _async_activate
    await self.async_activate(**kwargs)
  File "/usr/src/homeassistant/homeassistant/components/homeassistant/scene.py", line 334, in async_activate
    await async_reproduce_state(
  File "/usr/src/homeassistant/homeassistant/helpers/state.py", line 115, in async_reproduce_state
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/helpers/state.py", line 109, in worker
    await platform.async_reproduce_states(
  File "/usr/src/homeassistant/homeassistant/components/light/reproduce_state.py", line 195, in async_reproduce_states
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/components/light/reproduce_state.py", line 182, in _async_reproduce_state
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1957, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1997, in _execute_service
    return await cast(
           ^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 845, in entity_service_call
    response_data = task.result()  # pop exception if have
                    ^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1192, in async_request_call
    return await coro
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 889, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 582, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/config/custom_components/tapo/light.py", line 169, in async_turn_on
    self._effects[effect].to_effect()
    ~~~~~~~~~~~~~^^^^^^^^
KeyError: 'rainbow'

```
[home-assistant_tapo_2023-07-20T21-15-58.477Z.log](https://github.com/petretiandrea/home-assistant-tapo-p100/files/12114238/home-assistant_tapo_2023-07-20T21-15-58.477Z.log)

**Comment by darkmatter24** [comment]
I had exactly the same problem after recently upgrading, for me it turned out that the effect name needed to start with a capital letter.
So...

```
service: light.turn_on  
data:
  effect: rainbow
target:
  entity_id: light.light_name
```

gave the error you're getting, and

```
service: light.turn_on
data:
  effect: Rainbow
target:
  entity_id: light.light_name
```
works as expected

**Comment by stevenazari** [comment]
My friend, thank you so much for taking the time to post this fix, that indeed corrects the problem.
________________________________
