### ISSUE TITLE
Support for TS 15 Matter enabled switch

### ISSUE THREAD

**Issue by blacktrails** [petretiandrea/home-assistant-tapo-p100#456]
I was trying to integrate 2 TP-Link Tapo TS-15 light switches. I received an error stating "failed to set up". When I checked the logs it appears that they are not supported. Is there a work around or should I just get rid of them and get Kasa's?

```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/tapo/tapo_device.py:32
Integration: TP-Link Tapo (documentation, issues)
First occurred: 3:52:30 PM (3 occurrences)
Last logged: 3:55:14 PM

Error setting up entry Porch Lights for tapo
Error setting up entry Foyer Light for tapo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/__init__.py", line 40, in async_setup_entry
    raise error
  File "/config/custom_components/tapo/__init__.py", line 38, in async_setup_entry
    return await device.initialize_device(hass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/tapo_device.py", line 32, in initialize_device
    raise DeviceNotSupported(f"Device {host} not supported!")
custom_components.tapo.errors.DeviceNotSupported: Device 192.168.0.37 not supported!
```

**Comment by petretiandrea** [comment]
Actually, TS-15 is not supported. I don't have the device to test an integration with HA

**Comment by petretiandrea** [comment]
2.9.0 support it experimentally
