### ISSUE TITLE
Device not supported at random (Could API be rate-limited?)

### ISSUE THREAD

**Issue by IIV-NATHAN-VII** [petretiandrea/home-assistant-tapo-p100#459]
I have a theory as to why this may be happening https://github.com/petretiandrea/home-assistant-tapo-p100/issues/459#issuecomment-1657188530

Same issue as before only 4 of my devices remain connected, I've made 0 changes to tapo account or app (all tapo have static IP) I've no idea what's going on, when I try to re-add the missing devices I get invalid credentials again.

Original issue #448 

"Was working fine today, all of a sudden my setup stopped connecting to my bulbs as another user seems to have posted."
https://github.com/petretiandrea/home-assistant-tapo-p100/issues/447

-snip-

_Originally posted by @IIV-NATHAN-VII in https://github.com/petretiandrea/home-assistant-tapo-p100/issues/448_

**Comment by IIV-NATHAN-VII** [comment]
My P110 out of nowhere:

Error setting up entry Air Conditioner for tapo

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/__init__.py", line 40, in async_setup_entry
    raise error
  File "/config/custom_components/tapo/__init__.py", line 38, in async_setup_entry
    return await device.initialize_device(hass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/tapo_device.py", line 32, in initialize_device
    raise DeviceNotSupported(f"Device {host} not supported!")
custom_components.tapo.errors.DeviceNotSupported: Device 192.168.1.107 not supported!

**Comment by IIV-NATHAN-VII** [comment]
I have a feeling this may occur when home-assistant is restarted and (I'm thiniking), when home assistant starts and the Tapo devices are off at the power, it kicks them off and throws an error.

This is the only reason I can think 4 of my bulbs still work and all others are facing Device not supported and then invalid auth when attemping to re-add. (even though some are the same model).

Could this be a thing?

**Comment by IIV-NATHAN-VII** [comment]
08:33:37.346 INFO (MainThread) [custom_components.tapo.coordinators] Login to 192.168.1.107, success: Left: Returned error_code: TapoError.INVALID_CREDENTIAL: Invalid credentials
2023-07-30 08:33:37.372 INFO (MainThread) [custom_components.tapo.coordinators] Login to 192.168.1.131, success: Right True
2023-07-30 08:33:37.387 INFO (MainThread) [custom_components.tapo.coordinators] Detected model of 192.168.1.107: None
2023-07-30 08:33:37.388 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Air Conditioner for tapo
Traceback (most recent call last):

This device is always powered on though weirdly.

**Comment by Alaskapclos** [comment]
exactly what happens here in my system. My 8 P110 randomly disappear, most of the time every 8 disappear at the same time. 
Today there was a short circuit and the fuse blew. Only my dedicated Home Assistant server was affected. After restarting the server, 5 of the 8 P110s were no longer deployed, 3 ran without problems. When I tried to reload the Tap integration, the message "Error setting up" always came up. If I want to set up the plugs again, it says the credentials are wrong. Only deleting and re-adding in the Tapo app fixes the error.

**Comment by IIV-NATHAN-VII** [comment]
Could it be that the plugin is sending out an API query to get device info PER device? Perhaps TP-Link rate limits their API?
@petretiandrea 

I haven't dived into the code enough to see how get device info is handled but if it's requesting it per device my home assistant is gonna query tp-link 11 times at the same time, could be interpreted by their systems as DDoS.

I just imagine Home-assistant coming online and immediately sending (API Requests to get info x the number of devices you have).
This would make sense as to why we keep having to re-add devices to tapo as it'd likely reset this limit / block put in place if they see it as an unusually high amount of requests in a short amount of time.

It'd also explain why some devices stay connected then others randomly disconnect (hit the limit).

Do you know what I'm saying?

Get info for all devices at once if possible?

**Comment by IIV-NATHAN-VII** [comment]
Is each of these a query to TP-Link's Cloud API?
If so, I think a rate-limit is the issue we're all running into here. (they're all done in the same second).

`2023-07-30 08:33:35.473 DEBUG (MainThread) [custom_components.tapo.setup_helpers] Creating new API to create a coordinator for 8022-snip-
2023-07-30 08:33:35.574 DEBUG (MainThread) [custom_components.tapo.setup_helpers] Creating new API to create a coordinator for 8023-snip-
2023-07-30 08:33:35.653 DEBUG (MainThread) [custom_components.tapo.setup_helpers] Creating new API to create a coordinator for 8023-snip-
2023-07-30 08:33:35.758 DEBUG (MainThread) [custom_components.tapo.setup_helpers] Creating new API to create a coordinator for 8023-snip-
2023-07-30 08:33:35.895 DEBUG (MainThread) [custom_components.tapo.setup_helpers] Creating new API to create a coordinator for 8023-snip-
2023-07-30 08:33:35.986 DEBUG (MainThread) [custom_components.tapo.setup_helpers] Creating new API to create a coordinator for 8023-snip-
2023-07-30 08:33:36.078 DEBUG (MainThread) [custom_components.tapo.setup_helpers] Creating new API to create a coordinator for 8023-snip-
2023-07-30 08:33:36.215 DEBUG (MainThread) [custom_components.tapo.setup_helpers] Creating new API to create a coordinator for 8023-snip-
2023-07-30 08:33:36.320 DEBUG (MainThread) [custom_components.tapo.setup_helpers] Creating new API to create a coordinator for 8023-snip-
2023-07-30 08:33:36.393 DEBUG (MainThread) [custom_components.tapo.setup_helpers] Creating new API to create a coordinator for 8023-snip-`
Rest of log
`2023-07-30 08:33:37.346 INFO (MainThread) [custom_components.tapo.coordinators] Login to 192.168.1.107, success: Left: Returned error_code: TapoError.INVALID_CREDENTIAL: Invalid credentials
2023-07-30 08:33:37.372 INFO (MainThread) [custom_components.tapo.coordinators] Login to 192.168.1.131, success: Right True
2023-07-30 08:33:37.387 INFO (MainThread) [custom_components.tapo.coordinators] Detected model of 192.168.1.107: None
2023-07-30 08:33:37.388 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Air Conditioner for tapo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/__init__.py", line 40, in async_setup_entry
    raise error
  File "/config/custom_components/tapo/__init__.py", line 38, in async_setup_entry
    return await device.initialize_device(hass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/tapo_device.py", line 32, in initialize_device
    raise DeviceNotSupported(f"Device {host} not supported!")
custom_components.tapo.errors.DeviceNotSupported: Device 192.168.1.107 not supported!
2023-07-30 08:33:37.442 INFO (MainThread) [custom_components.tapo.coordinators] Detected model of 192.168.1.131: l630
2023-07-30 08:33:37.680 INFO (MainThread) [custom_components.tapo.coordinators] Login to 192.168.1.146, success: Right True
2023-07-30 08:33:37.688 INFO (MainThread) [custom_components.tapo.coordinators] Login to 192.168.1.194, success: Right True
2023-07-30 08:33:37.696 INFO (MainThread) [custom_components.tapo.coordinators] Login to 192.168.1.175, success: Right True
2023-07-30 08:33:37.770 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.327 seconds (success: True)
2023-07-30 08:33:37.777 INFO (MainThread) [custom_components.tapo.coordinators] Detected model of 192.168.1.146: l630
2023-07-30 08:33:37.895 INFO (MainThread) [custom_components.tapo.coordinators] Detected model of 192.168.1.175: l630
2023-07-30 08:33:37.905 INFO (MainThread) [custom_components.tapo.coordinators] Detected model of 192.168.1.194: l630
2023-07-30 08:33:37.973 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.196 seconds (success: True)
2023-07-30 08:33:37.983 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.063 seconds (success: True)
2023-07-30 08:33:37.994 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.089 seconds (success: True)
2023-07-30 08:33:38.000 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.105 seconds (success: True)
2023-07-30 08:33:38.053 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.052 seconds (success: True)
2023-07-30 08:33:38.064 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.041 seconds (success: True)
2023-07-30 08:33:38.071 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.055 seconds (success: True)
`

**Comment by petretiandrea** [comment]
> 

Thanks for hint, I will dive in

**Comment by IIV-NATHAN-VII** [comment]
Sweet, I'd have made a contribution myself but I couldn't find where the API requests were being called.

**Comment by petretiandrea** [comment]
I've create a PR for my library to allow to set different terminal uuid. https://github.com/petretiandrea/plugp100/pull/100

**Comment by IIV-NATHAN-VII** [comment]
> I've create a PR for my library to allow to set different terminal uuid. https://github.com/petretiandrea/plugp100/pull/100

Sweet, can I just drop these files/ replace in the custom_components folder?

I will test later / tomorrow and post back.

**Comment by petretiandrea** [comment]
> > I've create a PR for my library to allow to set different terminal uuid. [petretiandrea/plugp100#100](https://github.com/petretiandrea/plugp100/pull/100)
> 
> Sweet, can I just drop these files/ replace in the custom_components folder?
> 
> I will test later / tomorrow and post back if so.

No, I will release a new version of integration

**Comment by petretiandrea** [comment]
v2.4.0 should fix
