### ISSUE TITLE
Unable to add P100 plugs to integration

### ISSUE THREAD

**Issue by mobonez** [petretiandrea/home-assistant-tapo-p100#466]
I am unable to add any P100 plugs into the integration. I have successfully added P110 and L530 Bulbs with the exact same credentials. Its only the P100 plugs that give the 'Invalid Credentials' error.

I have confirmed I am able to Ping the P100 plugs from HA and also my HA Host so it is accessible on the network, it just will not add into HA.

## Version of the integration
2.4.0

## Configuration
P100 Plug on FW: 1.4.18 Build 20230711 rel. 55651

```
2023-08-04 22:17:12.369 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.093 seconds (success: True)
2023-08-04 22:17:33.535 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.172 seconds (success: True)
2023-08-04 22:17:39.324 ERROR (MainThread) [custom_components.tapo.config_flow] Tapo exception -1501
2023-08-04 22:17:39.326 ERROR (MainThread) [custom_components.tapo.config_flow] Failed to setup, invalid auth
Traceback (most recent call last):
File "/config/custom_components/tapo/config_flow.py", line 175, in _try_setup_api
return value_or_raise(
^^^^^^^^^^^^^^^
File "/config/custom_components/tapo/helpers.py", line 11, in value_or_raise
raise value_or_error
plugp100.responses.tapo_exception.TapoException: Returned error_code: TapoError.INVALID_CREDENTIAL: Invalid credentials
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/config/custom_components/tapo/config_flow.py", line 88, in async_step_user
api = await self._try_setup_api(user_input)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/tapo/config_flow.py", line 179, in _try_setup_api
self._raise_from_tapo_exception(error)
File "/config/custom_components/tapo/config_flow.py", line 186, in _raise_from_tapo_exception
raise InvalidAuth from exception
custom_components.tapo.errors.InvalidAuth
2023-08-04 22:17:42.368 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.092 seconds (success: True)
```

**Comment by Der-Isy** [comment]
After updating to 2.4.0 I get something similar.. All my Tapo P110 plugs work fine and all P100 don't.. The log says, that the device is not supported!?

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/__init__.py", line 39, in async_setup_entry
    raise error
  File "/config/custom_components/tapo/__init__.py", line 37, in async_setup_entry
    return await device.initialize_device(hass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/tapo_device.py", line 31, in initialize_device
    raise DeviceNotSupported(f"Device {host} not supported!")
custom_components.tapo.errors.DeviceNotSupported: Device 192.168.200.15 not supported!`

**Comment by JRobbo92** [comment]
I'm getting the same errors as Der-Isy is, Unable to add any Tapo devices.

Main ones are P100 Plugs. Just receiving invalid authentication.

2023-08-10 15:03:23.027 ERROR (MainThread) [custom_components.tapo.config_flow] Tapo exception -1501
2023-08-10 15:03:24.102 ERROR (MainThread) [custom_components.tapo.config_flow] Failed to setup, invalid auth
Traceback (most recent call last):
File "/config/custom_components/tapo/config_flow.py", line 175, in _try_setup_api
return value_or_raise(
^^^^^^^^^^^^^^^
File "/config/custom_components/tapo/helpers.py", line 11, in value_or_raise
raise value_or_error
plugp100.responses.tapo_exception.TapoException: Returned error_code: TapoError.INVALID_CREDENTIAL: Invalid credentials
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/config/custom_components/tapo/config_flow.py", line 88, in async_step_user
api = await self._try_setup_api(user_input)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/tapo/config_flow.py", line 179, in _try_setup_api
self._raise_from_tapo_exception(error)
File "/config/custom_components/tapo/config_flow.py", line 186, in _raise_from_tapo_exception
raise InvalidAuth from exception
custom_components.tapo.errors.InvalidAuth

**Comment by TommisGR** [comment]
> After updating to 2.4.0 I get something similar.. All my Tapo P110 plugs work fine and all P100 don't.. The log says, that the device is not supported!?
> 
> ```
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 388, in async_setup
>     result = await component.async_setup_entry(hass, self)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/tapo/__init__.py", line 39, in async_setup_entry
>     raise error
>   File "/config/custom_components/tapo/__init__.py", line 37, in async_setup_entry
>     return await device.initialize_device(hass)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/tapo/tapo_device.py", line 31, in initialize_device
>     raise DeviceNotSupported(f"Device {host} not supported!")
> custom_components.tapo.errors.DeviceNotSupported: Device 192.168.200.15 not supported!
> ```
> 
> EDIT: After updating the P100 devices to 1.4.18 Build 20230711 Rel. 55651 and reloading the integration, it seems to work again.. Maybe it should be noted in the patch notes, that a specific firmware version is needed..

I am having issues with 2 older P100 
Hardware 1.0
Firmware 1.3.7 Build 20230711 Rel. 61904

a newer one with same firm as above install with no issues

**Comment by TommisGR** [comment]
and some logs
```
2023-08-24 23:28:46.900 ERROR (MainThread) [custom_components.tapo.config_flow] Failed to setup cannot connect 
Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 180, in _try_setup_api
    (await client.login(user_input[CONF_HOST]))
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_client.py", line 47, in login
    return await self.login_with_url(f"http://{ip_address}/app")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_client.py", line 56, in login_with_url
    login_result = await self._login_with_version(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_client.py", line 253, in _login_with_version
    token = (await self._send_safe_passthrough(login_request)).map(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_client.py", line 209, in _send_safe_passthrough
    response = await self._passthrough.send(request, self._session)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/common/transport/securepassthrough_transport.py", line 126, in send
    response_encrypted = await self._http.async_make_post_cookie(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/common/utils/http_client.py", line 25, in async_make_post_cookie
    async with self.session.post(
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 894, in start
    with self._timer:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 87, in async_step_user
    api = await self._try_setup_api(user_input)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/config_flow.py", line 187, in _try_setup_api
    raise CannotConnect from error
custom_components.tapo.errors.CannotConnect
2023-08-24 23:29:59.383 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.114 seconds (success: True)
2023-08-24 23:30:29.383 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.116 seconds (success: True)
2023-08-24 23:30:44.162 DEBUG (MainThread) [custom_components.tapo.setup_helpers] Re-using setup API to create a coordinator
2023-08-24 23:30:59.388 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.120 seconds (success: True)
2023-08-24 23:31:29.380 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.113 seconds (success: True)
2023-08-24 23:31:59.385 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.117 seconds (success: True)
2023-08-24 23:32:29.386 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.120 seconds (success: True)
2023-08-24 23:32:59.383 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.116 seconds (success: True)
2023-08-24 23:33:29.388 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.120 seconds (success: True)
2023-08-24 23:33:59.395 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.128 seconds (success: True)
2023-08-24 23:34:29.377 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.110 seconds (success: True)
2023-08-24 23:34:59.389 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.123 seconds (success: True)
2023-08-24 23:35:29.315 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.049 seconds (success: True)
2023-08-24 23:35:44.901 WARNING (MainThread) [homeassistant.config_entries] Config entry '5 Yannis Smart Plug' for tapo integration not ready yet; Retrying in background
2023-08-24 23:35:50.275 DEBUG (MainThread) [custom_components.tapo.setup_helpers] Re-using setup API to create a coordinator
```

**Comment by 10n** [comment]
I was able to fix this kind of issue by doing the following:

1. remove the device from HA, 
2. remove the device from Tapo app  
3. re-add the plug into tapo app, 
4. re-add the device to HA

(there may be a simple procedure, but this has worked for me).

**Comment by petretiandrea** [comment]
Upgrade to 2.8.2
