### ISSUE TITLE
No sensors or devices created for L930

### ISSUE THREAD

**Issue by deepschiff** [petretiandrea/home-assistant-tapo-p100#474]
## Version of the integration
 2.5

## Configuration
L930  1.0.9 

## Describe the bug

Entry created for L930, but no devices, sensors, or entities. 
It looks like get_device_info is returning None.

## Debug log

2023-08-16 14:32:46.007 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up tapo platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 362, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tapo/sensor.py", line 59, in async_setup_entry
    _setup_from_coordinator(hass, data.coordinator, async_add_entities)
  File "/config/custom_components/tapo/sensor.py", line 67, in _setup_from_coordinator
    sensors = [TapoSensor(coordinator, SignalSensorSource())]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/sensor.py", line 90, in __init__
    super().__init__(coordinator)
  File "/config/custom_components/tapo/entity.py", line 22, in __init__
    self._base_data = coordinator.get_device_info()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/coordinators.py", line 199, in get_device_info
    return self.data.info
           ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'info'
2023-08-16 14:32:46.013 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up tapo platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 362, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tapo/binary_sensor.py", line 15, in async_setup_entry
    sensors = [TapoSensor(data.coordinator, OverheatSensorSource())]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/sensor.py", line 90, in __init__
    super().__init__(coordinator)
  File "/config/custom_components/tapo/entity.py", line 22, in __init__
    self._base_data = coordinator.get_device_info()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/coordinators.py", line 199, in get_device_info
    return self.data.info
           ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'info'
2023-08-16 14:32:46.020 ERROR (MainThread) [homeassistant.components.light] Error while setting up tapo platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 362, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tapo/light.py", line 55, in async_setup_entry
    _setup_from_coordinator(hass, data.coordinator, async_add_entities)
  File "/config/custom_components/tapo/light.py", line 64, in _setup_from_coordinator
    model = get_short_model(coordinator.get_device_info().model)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/coordinators.py", line 199, in get_device_info
    return self.data.info
           ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'info'

**Comment by deepschiff** [comment]
Found the issue. The device was set to an effect by google that wasn't in the default effect list. This caused the sensor type to return none. I changed the effect to one in the Tapo app and it integrated without an issue. I'll close the issue, but will look at adding a check to see if the effect returned is supported and if not, removing that effect so it doesn't break the rest of the integration.
