### ISSUE TITLE
Unable to control L530 after upgrade to 1.1.0 Build 230721

### ISSUE THREAD

**Issue by petretiandrea** [petretiandrea/home-assistant-tapo-p100#482]
## Version of the integration

v2.6.1

## Configuration

L530, fw: 1.1.0 Build 230721 hw: 2.0

## Describe the bug

TP link has added a new procotol KLAP which is not supported by my library `plugp100` see https://github.com/petretiandrea/plugp100/issues/113

**Comment by jackmawer** [comment]
Is it possible to downgrade these lights in the meantime? I have the bad luck of having bought several that have arrived today and of course the new firmware is forcibly updated on them during setup.

**Comment by ohiomedic** [comment]
This explains why my lights weren't working today. Mine must have autoupdated the firmware overnight.

**Comment by woodlair** [comment]
Here I thought it was just me.  I updated several components today and suddenly my l530 bulbs would not initialize.  Thank you for being so quick to identify the problem.

**Comment by Evanito** [comment]
Likely related news: https://hothardware.com/news/researchers-discover-vulnerabilities-in-tp-link-smart-bulbs-to-steal-passwords

**Comment by DOSirl** [comment]
I have also noticed that I've woken up to my L530's and L510's no longer controllable. 
I only just got the L530's.
Is there anything that can be done to get them working again?

**Comment by matteovisotto** [comment]
Same problem, I removed my L530 from home assistant thinking it was an ip problem and now I cannot add it again. 
Hope for un update asap

**Comment by DOSirl** [comment]
> Same problem, I removed my L530 from home assistant thinking it was an ip problem and now I cannot add it again. Hope for un update asap

I removed my 2 x L510's for the same reason and now can't add again. Hopefully it can be resolved.
If I could help, I would, but I know nothing about this stuff unfortunately.

**Comment by DavideBoschi** [comment]
I had the same problem this morning, I got up and my L530 bulbs doesn't work anymore from home assistant... I checked the firmware and they are updated to the 1.1.0 Build 230721. What it means?! with this new version of firmware they are not anymore suitable from home assistant?

**Comment by ahthief** [comment]
Same problem. After removing L530, I can not add it again anymore.

**Comment by Carlosbro5** [comment]
just adding in that all 5 of my L530 bulbs not working. My tapo light strip works fine however not the bulbs. Hopefully a fix comes soon

**Comment by naamah75** [comment]
Same problem...

Thinking it was an IP address issue I tried to uninstall the integration. But now I can't reconnect the bulbs, here is the error

```
Failed to setup cannot connect
Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 175, in _try_setup_api
    return value_or_raise(
           ^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/helpers.py", line 11, in value_or_raise
    raise value_or_error
plugp100.responses.tapo_exception.TapoException: Returned unknown error_code: 1003  msg: No message

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 88, in async_step_user
    api = await self._try_setup_api(user_input)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/config_flow.py", line 179, in _try_setup_api
    self._raise_from_tapo_exception(error)
  File "/config/custom_components/tapo/config_flow.py", line 188, in _raise_from_tapo_exception
    raise CannotConnect from exception
custom_components.tapo.errors.CannotConnect
```

**Comment by Messelweg** [comment]
Same problem. Hopefully a fix comes soon.

**Comment by ItsMeRitch** [comment]
Also affected, hopefully a solution can be found quick :( 

@petretiandrea is there anything we can do to help support this?

**Comment by petretiandrea** [comment]
I'm working on It. I've already a working version of plugp100, but I need a way to known when to use klap protocol instead of actual protocol

**Comment by ItsMeRitch** [comment]
> I'm working on It. I've already a working version of plugp100, but I need a way to known when to use klap protocol instead of actual protocol

You’re an absolute star. Doing some digging, seems these folk have been able to implement it for KASA Tp link products if it helps 

https://github.com/python-kasa/python-kasa/issues/115

I’m not very good working with API and what not but If you want someone to test stuff, just give me a shout and I’ll do my best.

**Comment by liquidv** [comment]
My L630 and L510 also stopped working after updating in Tapo in HACS

**Comment by liquidv** [comment]
Nevermind I downgraded back to v2.6.0 :)

**Comment by ItsMeRitch** [comment]
How’d you manage to downgrade? On 24 Aug 2023, at 20:22, liquidv ***@***.***> wrote:﻿
Nevermind I downgraded back to v2.6.0 :)

**Comment by ItsMeRitch** [comment]
@liquidv howd you manage to downgrade?

**Comment by liquidv** [comment]
Sorry ignore me, I don't know what I'm talking about, I'm confusing things.....

**Comment by lasercheesecake** [comment]
same problem, all of a sudden, all my bulbs were showing not available.

**Comment by jaymunro** [comment]
For this very reason I have my devices set to **not** autoupdate firmware. Yet by L530 bulb updated anyway.

**Comment by StefanoFrazzetto** [comment]
@jaymunro it's possible they have a way to force devices to update then, regardless of that setting

Anyway, I'm also happy to help with code or testing. Let us know if there's anything we can do to get this fixed asap

**Comment by sdb9696** [comment]
> I'm working on It. I've already a working version of plugp100, but I need a way to known when to use klap protocol instead of actual protocol

If you can't get that info via the api you could probably get a discovery response and look inside for KLAP if you query the device on udp to port 20002 with a magic number.  I believe this worked for TAPO devices pre the update so I'd imagine it still does.  You can see an example for kasa devices here: https://github.com/python-kasa/python-kasa/pull/488

**Comment by Giuseppe197575** [comment]
Same problem

**Comment by derailius** [comment]
same issues here

**Comment by DavideBoschi** [comment]
Hi @petretiandrea, thank you for your job!! 
I have a question, maybe stupid.. 
I just reinstalled the tapo control integration, but I still not able to add again may L530.. Where I wrong?! how can I update the  plugp100 python library on my HA??
Thank you in advance for the help!

**Comment by matteovisotto** [comment]
> Hi @petretiandrea, thank you for your job!!
> I have a question, maybe stupid..
> I just reinstalled the tapo control integration, but I still not able to add again may L530.. Where I wrong?! how can I update the plugp100 python library on my HA??
> Thank you in advance for the help!

@DavideBoschi He update the core library at the moment, I think he will also update home assistant integration soon.

**Comment by DavideBoschi** [comment]
> > Hi @petretiandrea, thank you for your job!!
> > I have a question, maybe stupid..
> > I just reinstalled the tapo control integration, but I still not able to add again may L530.. Where I wrong?! how can I update the plugp100 python library on my HA??
> > Thank you in advance for the help!
> 
> @DavideBoschi He update the core library at the moment, I think he will also update home assistant integration soon.

Ok, thank you very much!!

**Comment by dave2000gray** [comment]
> I'm releasing plugp100 v3.9.0 which support KLAP protocol 🥳 special thanks to `python-kasa`. I will integration my new library version in HA

Hero! Thank you for all your hard work. Coffee's inbound!

**Comment by Valiante** [comment]
Yep, buying a coffee right now to support this great integration.

**Comment by petretiandrea** [comment]
v2.7.0 support klap protocol try it, and re-open issue if problem persists

**Comment by Pugwash69** [comment]
2.7.0 is working perfectly. Thanks!

**Comment by Valiante** [comment]
> v2.7.0 support klap protocol try it, and re-open issue if problem persists

Working a treat, thanks for your support 👍

**Comment by v966732** [comment]
Working again, thank-you very much

**Comment by matteovisotto** [comment]
Thank you so much. It works

**Comment by Messelweg** [comment]
Thank you so much, it works and i am happy again.

**Comment by not1q84-1** [comment]
There still seems to be a bug in the klap_protocol.py. I have two L530 light bulbs, where off one is working fine but the other one produces an error **in some** switch events. Difficult to trace when exactly it is failing. But the error message in the HA log seems to be quite clear: 

2023-08-27 08:49:05.116 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140512203478720] 'utf-8' codec can't decode byte 0x81 in position 15: invalid start byte
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 226, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 870, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 942, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 591, in async_handle_light_off_service
    await light.async_turn_off(**filter_turn_off_params(light, params))
  File "/config/custom_components/tapo/light.py", line 179, in async_turn_off
    (await self.coordinator.device.off()).get_or_raise()
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/light_device.py", line 41, in off
    return await self._api.set_device_info(SetPlugInfoParams(False))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_client.py", line 126, in set_device_info
    return await self._set_device_info(dataclass_encode_json(device_info))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_client.py", line 195, in _set_device_info
    response = await self._protocol.send_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/klap_protocol.py", line 48, in send_request
    response = await self._send_request(request, retry)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/klap_protocol.py", line 88, in _send_request
    self._klap_session.chiper.decrypt(response_data)
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/klap_protocol.py", line 323, in decrypt
    return plaintextbytes.decode()
           ^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x81 in position 15: invalid start byte
2023-08-27 08:49:05.166 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140512203478720] 'utf-8' codec can't decode byte 0x82 in position 15: invalid start byte
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 226, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 870, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 942, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 591, in async_handle_light_off_service
    await light.async_turn_off(**filter_turn_off_params(light, params))
  File "/config/custom_components/tapo/light.py", line 179, in async_turn_off
    (await self.coordinator.device.off()).get_or_raise()
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/light_device.py", line 41, in off
    return await self._api.set_device_info(SetPlugInfoParams(False))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_client.py", line 126, in set_device_info
    return await self._set_device_info(dataclass_encode_json(device_info))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_client.py", line 195, in _set_device_info
    response = await self._protocol.send_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/klap_protocol.py", line 48, in send_request
    response = await self._send_request(request, retry)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/klap_protocol.py", line 88, in _send_request
    self._klap_session.chiper.decrypt(response_data)
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/klap_protocol.py", line 323, in decrypt
    return plaintextbytes.decode()
           ^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 15: invalid start byte
2023-08-27 08:49:39.411 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140512203478720] Could not load a dict; the given string is not valid JSON.: line 1 column 16 (char 15)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/jsons/_load_impl.py", line 150, in loads
    obj = json.loads(str_, **jdkwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 16 (char 15)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 226, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1974, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2011, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 870, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 942, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 580, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/config/custom_components/tapo/light.py", line 174, in async_turn_on
    (await self.coordinator.device.on()).get_or_raise()
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/light_device.py", line 34, in on
    return await self._api.set_device_info(SetPlugInfoParams(True))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_client.py", line 126, in set_device_info
    return await self._set_device_info(dataclass_encode_json(device_info))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_client.py", line 195, in _set_device_info
    response = await self._protocol.send_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/klap_protocol.py", line 48, in send_request
    response = await self._send_request(request, retry)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/klap_protocol.py", line 87, in _send_request
    decrypted_response = jsons.loads(
                         ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jsons/_load_impl.py", line 152, in loads
    raise DecodeError('Could not load a dict; the given string is not '
jsons.exceptions.DecodeError: Could not load a dict; the given string is not valid JSON.: line 1 column 16 (char 15)
