### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'today_runtime'

### ISSUE THREAD

**Issue by Elarion245** [petretiandrea/home-assistant-tapo-p100#487]
I receive above AttributeError starting with v2.6.0 and persisting with 2.6.1 for my P115 devices. With 2.5.0 everything is still fine.

Firmware is 1.2.3 Build 230425 Rel 142542 on all plugs

## Debug log

```text
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 750, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1004, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 746, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 808, in _async_write_ha_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 752, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 479, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/sensor.py", line 117, in native_value
    return self._sensor_source.get_value(self.coordinator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/sensors/__init__.py", line 128, in get_value
    return coordinator.get_state_of(EnergyInfo).today_runtime
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'today_runtime'

```

**Comment by simonefiorini01** [comment]
I've a similar issue: the error message is equal execpt for the final part which is "'NoneType' object has no attribute '**map**'"
Log attached.
[home-assistant_tapo_2023-08-25T00-41-19.418Z.log](https://github.com/petretiandrea/home-assistant-tapo-p100/files/12434412/home-assistant_tapo_2023-08-25T00-41-19.418Z.log)

**Comment by Graloth** [comment]
I am experiencing this exact issue ('NoneType' object has no attribute 'today_runtime'), and since I have several Tapo P110, it is spamming my log quite severely.

**Comment by jove01** [comment]
same error

**Comment by petretiandrea** [comment]
v2.7.0 should fix this
