### ISSUE TITLE
l530 Light Failed to call service light/turn_on. After 2.7.0

### ISSUE THREAD

**Issue by xertux** [petretiandrea/home-assistant-tapo-p100#498]
During the beta phase, I installed version 2.7.0 to address the problem that had occurred with the communication on the L530 device. However, I have since re-downloaded the regular version of 2.7.0.

The L530 device is currently running the necessary latest version, even though the auto-update feature is turned off.

The functionality to turn the light on/off operates as expected. However, when attempting to adjust parameters like brightness, color, or temperature, I encounter the following error message: "Failed to call service light/turn_on. Could not load a dict; the given string is not valid JSON.: line 1 column 16 (char 15)." This error causes the device to become momentarily unavailable.

Even after attempting to resolve the issue by deleting and then re-adding the device, the problem still persists.

**Comment by jcbrownratby** [comment]
I am experiencing the same. though it appears random. sometimes changing the brightness works, other times it fails with the ""Call-service error. Could not load a dict; the given string is not valid JSON.: line 1 column 16 (char 15)" error. I've also tried deleting and re adding, but to no avail

**Comment by petretiandrea** [comment]
Please upgrade to 2.8.2

**Comment by xertux** [comment]
Upgraded to 2.8.2 but the problem continues.

**Comment by xertux** [comment]
Hi, i know you are working on many different topics but is there any update on this? I'm having constant dissconnects which takes exactly 30secs (polling rate) a few times a day and i think the source of that problem is also about that line.

**Comment by tomwrgriff** [comment]
Hi, I'm having the same problem with L530 bulbs only. It's the same error message as reported above, but it's intermittent. Sometimes the adjustments work and sometimes not but with no obvious pattern. I was experimenting setting up a new dashboard with Bubble Card elements and wondered if that was causing conflicts, but the error is also happening on my native HA dashboard controls.

I'm on HA OS 2023.10 and v2.9.1 stable of tapo integration.

Here are some log entries that looks relevant, but I'm new to this so not sure if it helps.

```
This error originated from a custom integration.

Logger: custom_components.tapo.coordinators
Source: helpers/update_coordinator.py:322
Integration: TP-Link Tapo (documentation, issues)
First occurred: 5 October 2023 at 16:27:53 (15 occurrences)
Last logged: 10:13:03

Error fetching tapo data: Unexpected exception:
Error fetching tapo data: Unexpected exception: Invalid padding bytes.
Error fetching tapo data: Unexpected exception: Could not load a dict; the given string is not valid JSON.: line 1 column 16 (char 15)
Error fetching tapo data: Unexpected exception: 'device_id'
```
```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:226
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 00:00:42 (20 occurrences)
Last logged: 10:02:17

[546829172160] Could not load a dict; the given string is not valid JSON.: line 1 column 16 (char 15)
[546829163328] Could not load a dict; the given string is not valid JSON.: line 1 column 16 (char 15)
[547230774848] Could not load a dict; the given string is not valid JSON.: line 1 column 16 (char 15)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/jsons/_load_impl.py", line 150, in loads
    obj = json.loads(str_, **jdkwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 16 (char 15)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 226, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2012, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2049, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 876, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 578, in async_handle_light_on_service
    await async_handle_light_off_service(light, call)
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 591, in async_handle_light_off_service
    await light.async_turn_off(**filter_turn_off_params(light, params))
  File "/config/custom_components/tapo/light.py", line 179, in async_turn_off
    (await self.coordinator.device.off()).get_or_raise()
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/light_device.py", line 41, in off
    return await self._api.set_device_info(SetPlugInfoParams(False))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_client.py", line 126, in set_device_info
    return await self._set_device_info(dataclass_encode_json(device_info))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_client.py", line 195, in _set_device_info
    response = await self._protocol.send_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/klap_protocol.py", line 48, in send_request
    response = await self._send_request(request, retry)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/klap_protocol.py", line 87, in _send_request
    decrypted_response = jsons.loads(
                         ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jsons/_load_impl.py", line 152, in loads
    raise DecodeError('Could not load a dict; the given string is not '
jsons.exceptions.DecodeError: Could not load a dict; the given string is not valid JSON.: line 1 column 16 (char 15)

```

```
This error originated from a custom integration.

Logger: plugp100.protocol.klap_protocol
Source: custom_components/tapo/coordinators.py:197
Integration: TP-Link Tapo (documentation, issues)
First occurred: 5 October 2023 at 16:38:22 (2 occurrences)
Last logged: 07:32:04

Query failed after succesful authentication at XXX6520302.034368. Host is 192.168.XX.XXX, Available attempts count is 3, Sequence is XXX648077, Response status is 403, Request was <plugp100.requests.tapo_request.TapoRequest object at 0x7f527d0XXX>
Query failed after succesful authentication at XXX6573924.1663828. Host is 192.168.XX.XXX, Available attempts count is 3, Sequence is -XXX2880739, Response status is 403, Request was <plugp100.requests.tapo_request.TapoRequest object at 0x7f5783cXXX>
```

**Comment by tomwrgriff** [comment]
Quick update:

I uninstalled the Bubble Card integration and deleted those dashboards. I'm only using HA native dashboard elements now. The problem still occurs occasionally, but much, much less frequently. It's now most pronounced when changing colours.

**Comment by mstrlc** [comment]
Facing the same issue, Tapo L530E (HW v 3.0), running FW 1.1.0, Home Assistant 2023.9.2, Tapo integration v2.9.1. Switching lights on/off works 100% so far, but changing colors is what triggers this.

**Comment by kevin52408** [comment]
If you are needing a reliable way to induce the error, what seems to be same issue happens every time I run this sunrise simulator https://community.home-assistant.io/t/sunrise-simulator-wake-up-gently-to-light/493778 . I just set my duration to 1 minute to ease testing.

**Comment by xertux** [comment]
v2.10.2 right now, cuz v2.11.0 introduced another issue that when you change brightness the light flicks. (light goes off and on in an instant). This issue is only present for L510, L530 doesn't flick.

Just tried v2.12.0 now, the issue on the topic and flick continues. Switching back to v2.10.2.
