### ISSUE TITLE
Error after 2.8.0 update:ModuleNotFoundError: No module named 'custom_components.migrations'

### ISSUE THREAD

**Issue by jaspov** [petretiandrea/home-assistant-tapo-p100#503]
## Version of the integration
2.8.0

## Configuration
Tapo P100, 1.2.3 Build 23045 rel 142542

## Describe the bug
-it was working
-saw update and updated
-got error after reboor

Logger: homeassistant.setup
Source: custom_components/tapo/__init__.py:7
Integration: TP-Link Tapo ([documentation](https://github.com/petretiandrea/home-assistant-tapo-p100), [issues](https://github.com/petretiandrea/home-assistant-tapo-p100/issues))
First occurred: 10:57:01 (1 occurrences)
Last logged: 10:57:01
Setup failed for custom integration tapo: Unable to import component: No module named 'custom_components.migrations'

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 813, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/tapo/__init__.py", line 7, in <module>
    from custom_components.migrations import migrate_entry_to_v3
ModuleNotFoundError: No module named 'custom_components.migrations'

**Comment by petretiandrea** [comment]
I've been re-tagged 2.8.0 please retry to install it

**Comment by jaspov** [comment]
Thanks reinstalled and error is gone!
