### ISSUE TITLE
P110 switches missing

### ISSUE THREAD

**Issue by rogerfawbert** [petretiandrea/home-assistant-tapo-p100#522]
## Version of the integration
Latest HA 2023.9.2 and Tapo version 2.8.2

## Configuration

Tapo devices running latest versikns

```yaml
Add your logs here.
```

## Describe the bug

Using latest HA version and Tapo version 2.8.2
Previously multiple P100 and P110 switches all worked fine. 
Now P100 is still OK, but both P110 are missing the switch entity, so they cannot be turned off/on via HA. They now have 7 entities instead of 8. The power monitoring etc entities are still showing correctly.

## Debug log

```text

Add your logs here.
sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 367, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1002, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 730, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 830, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 771, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 736, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 473, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/sensor.py", line 105, in native_value
    return self._sensor_source.get_value(self.coordinator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/sensors/__init__.py", line 128, in get_value
    return coordinator.get_state_of(EnergyInfo).today_runtime
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'today_runtime'
2023-09-18 21:51:51.237 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.109 seconds (success: True)
2023-09-18 21:51:51.238 ERROR (MainThread) [homeassistant.components.switch] tapo: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 573, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 936, in async_device_update
    await self.async_update()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 511, in async_update
    await self.coordinator.async_request_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 242, in async_request_refresh
    await self._debounced_refresh.async_call()
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 93, in async_call
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 269, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 392, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 173, in async_update_listeners
    update_callback()
  File "/config/custom_components/tapo/entity.py", line 43, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 730, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 830, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 771, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 736, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 473, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/sensor.py", line 105, in native_value
    return self._sensor_source.get_value(self.coordinator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/sensors/__init__.py", line 128, in get_value
    return coordinator.get_state_of(EnergyInfo).today_runtime
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'today_runtime
```

**Comment by Diramu** [comment]
My first try with this integration, I hit this problem. With the P110.   I'll try a manual setup for the device as a work around....

**Comment by Diramu** [comment]
Manually added the P110 (as a light) did not work. No errors in the log.

**Comment by rogerfawbert** [comment]
I got a brand new p110 and added it with the mac tracking off and switch appears ok, however I cannot get the existing ones to do this, even after fully removing, rebooting, re,-adding etc. like the MACs are still cached somewhere?

Regards,
Roger Fawbert
+64 21 889 287
________________________________

**Comment by Diramu** [comment]
I just looked, I do now have the switch entity.  It might because I re-added after the manual addition did not work, but this  time, I also turned off the mac tracking.

**Comment by curlydingo** [comment]
Just added a new P110 and have the same problem. I did not have mac address tracking on as I've assigned a static lease, so I don't think the MAC tracking is the issue.

**Comment by curlydingo** [comment]
Hmm, the switch has now appeared, some time after originally adding the device. I added a second P110 also, and again it had no switch initially but this time the switch appeared within 2 minutes or so. Odd.

**Comment by rogerfawbert** [comment]
I notice when removing and re-adding, it remembers the old Entity name, so assume there is information retained even though it's deleted. Can't find where this info is held, so can't remove it to see if a fresh install may finally fix the issue with these ones.

**Comment by curlydingo** [comment]
I assume the entity name is something different to what they’re named in the Tapo app? In other words, it isn’t just pulling the name again from the Tapo ecosystem?

**Comment by rogerfawbert** [comment]
The device name was. Ended up removing again from Tapo, re-adding with a different name, waiting an hour then adding to HA and it seems OK now.  Have to keep the MAC tracking disabled though.
