### ISSUE TITLE
Failed to Connect / L530

### ISSUE THREAD

**Issue by idan** [petretiandrea/home-assistant-tapo-p100#531]
## Version of the integration

2.9.0

## Configuration

L530s with firmware 1.1.0

This is on a fresh HA install.

## Describe the bug

- I'm unable to add any of my Tapo lights. Errors out with `Failed to connect`
- They all have a static IP, I unchecked the MAC address tracking option
- Home Assistant on raspi is wired directly to the router.
- I am able to ping the IP addresses of the lights from terminal on my HA, so it's not a network visibility problem
- Right before the error message below, I am also seeing some errors in HA logs `Default protocol not working, fallback to KLAP ;)`

![Image](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/22723/11d35492-79d3-4a36-8203-4378d9b5406f)

![Image](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/22723/9b0bcf61-1160-4269-a3af-55bf7a012af6)

![Image](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/22723/297be6c5-c7eb-4b8b-a680-dc9160dae93c)

## Debug log

```text

This error originated from a custom integration.

Logger: custom_components.tapo.config_flow
Source: custom_components/tapo/config_flow.py:198
Integration: TP-Link Tapo (documentation, issues)
First occurred: September 21, 2023 at 11:42:59 PM (2 occurrences)
Last logged: 12:09:36 AM

Failed to setup cannot connect
Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 191, in _get_first_data_from_api
    (await tapo_client.get_device_info())
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_client.py", line 93, in get_device_info
    return (await self._protocol.send_request(get_info_request)).map(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/klap_protocol.py", line 48, in send_request
    response = await self._send_request(request, retry)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/klap_protocol.py", line 60, in _send_request
    if not self._klap_session.handshake_complete:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'handshake_complete'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 118, in async_step_user
    device_data = await self._get_first_data_from_api(tapo_client)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/config_flow.py", line 198, in _get_first_data_from_api
    raise CannotConnect from error
custom_components.tapo.errors.CannotConnect


```

**Comment by idan** [comment]
OK, after some digging around, I think was one of two problems: either symbols in the password, or 2FA being active.

I grabbed the sample code from https://github.com/petretiandrea/plugp100 and simplified:

```python
import asyncio
import os

from plugp100.api.tapo_client import TapoClient, AuthCredential


async def main():
    # create generic tapo api
    username = os.getenv('USERNAME', 'foo@bar.com')
    password = os.getenv('PASSWORD', 'not_my_actual_password')

    credential = AuthCredential(username, password)
    client = await TapoClient.connect(credential, "192.168.1.245")

    print(await client.get_device_info())

if __name__ == "__main__":
    loop = asyncio.new_event_loop()
    loop.run_until_complete(main())
    loop.run_until_complete(asyncio.sleep(0.1))
    loop.close()
```

Kept getting the same errors as in the HA integration:

```
  File "/Users/idan/src/tapotest/lib/python3.11/site-packages/plugp100/protocol/klap_protocol.py", line 63, in _send_request
    if not self._klap_session.handshake_complete:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'handshake_complete'
```

I reset my Tapo/Kasa password to something with just alphanumeric chars and turned off 2FA. This also messed up my Kasa integration but so be it
