### ISSUE TITLE
L900 strip: Error fetching tapo data: Unexpected exception: (with traceback logs)

### ISSUE THREAD

**Issue by noizo** [petretiandrea/home-assistant-tapo-p100#536]
## Version of the integration
v2.9.1

## Configuration
L900
by TP-Link
Firmware: 1.0.16 Build 220902 Rel.151030
Hardware: 1.0 

## Describe the bug

L900 light got disconnected status from time to time. It restores back after 30 seconds (which is a refresh time in lights configuration). Lights has static ip, they are using same AP. Signal is around -48 -55dBm.

## Debug log with traceback
```yaml
2023-09-27 13:22:02.380 WARNING (MainThread) [homeassistant.config_entries] Config entry 'prawe' for tapo integration not ready yet: Unexpected exception: ; Retrying in background
2023-09-27 13:22:59.465 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: tapo
2023-09-27 13:23:59.549 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: tapo
2023-09-27 13:24:12.504 ERROR (MainThread) [custom_components.tapo.coordinators] An error occurred: 
2023-09-27 13:24:12.509 ERROR (MainThread) [custom_components.tapo.coordinators] Exception traceback: Traceback (most recent call last):
  File "/config/custom_components/tapo/coordinators.py", line 148, in _async_update_data
    return await self._update_state()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/coordinators.py", line 210, in _update_state
    state = (await self.device.get_state()).get_or_raise()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/ledstrip_device.py", line 20, in get_state
    return (await self._api.get_device_info()).flat_map(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_client.py", line 93, in get_device_info
    return (await self._protocol.send_request(get_info_request)).map(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/passthrough_protocol.py", line 42, in send_request
    response = await self._send_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/passthrough_protocol.py", line 71, in _send_request
    return await self._passthrough.send(request, self._session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/securepassthrough_transport.py", line 128, in send
    response_encrypted = await self._http.async_make_post_cookie(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/common/utils/http_client.py", line 28, in async_make_post_cookie
    return await self._force_read_release(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/common/utils/http_client.py", line 34, in _force_read_release
    await response.read()
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1037, in read
    self._body = await self.content.read()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 375, in read
    block = await self.readany()
            ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 397, in readany
    await self._wait("readany")
  File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 304, in _wait
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/tapo/coordinators.py", line 147, in _async_update_data
    async with async_timeout.timeout(5):
  File "/usr/local/lib/python3.11/site-packages/async_timeout/__init__.py", line 141, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.11/site-packages/async_timeout/__init__.py", line 228, in _do_exit
    raise asyncio.TimeoutError
TimeoutError

2023-09-27 13:24:12.511 WARNING (MainThread) [homeassistant.config_entries] Config entry 'lewe' for tapo integration not ready yet: Unexpected exception: ; Retrying in background
2023-09-27 13:24:23.381 ERROR (MainThread) [custom_components.tapo.coordinators] An error occurred: 
2023-09-27 13:24:23.386 ERROR (MainThread) [custom_components.tapo.coordinators] Exception traceback: Traceback (most recent call last):
  File "/config/custom_components/tapo/coordinators.py", line 148, in _async_update_data
    return await self._update_state()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/coordinators.py", line 210, in _update_state
    state = (await self.device.get_state()).get_or_raise()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/ledstrip_device.py", line 20, in get_state
    return (await self._api.get_device_info()).flat_map(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_client.py", line 93, in get_device_info
    return (await self._protocol.send_request(get_info_request)).map(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/passthrough_protocol.py", line 42, in send_request
    response = await self._send_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/passthrough_protocol.py", line 71, in _send_request
    return await self._passthrough.send(request, self._session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/securepassthrough_transport.py", line 128, in send
    response_encrypted = await self._http.async_make_post_cookie(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/common/utils/http_client.py", line 28, in async_make_post_cookie
    return await self._force_read_release(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/common/utils/http_client.py", line 34, in _force_read_release
    await response.read()
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1037, in read
    self._body = await self.content.read()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 375, in read
    block = await self.readany()
            ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 397, in readany
    await self._wait("readany")
  File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 304, in _wait
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/tapo/coordinators.py", line 147, in _async_update_data
    async with async_timeout.timeout(5):
  File "/usr/local/lib/python3.11/site-packages/async_timeout/__init__.py", line 141, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.11/site-packages/async_timeout/__init__.py", line 228, in _do_exit
    raise asyncio.TimeoutError
TimeoutError

2023-09-27 13:24:23.388 ERROR (MainThread) [custom_components.tapo.coordinators] Error fetching tapo data: Unexpected exception: 
2023-09-27 13:25:23.050 ERROR (MainThread) [custom_components.tapo.coordinators] An error occurred: 
2023-09-27 13:25:23.055 ERROR (MainThread) [custom_components.tapo.coordinators] Exception traceback: Traceback (most recent call last):
  File "/config/custom_components/tapo/coordinators.py", line 148, in _async_update_data
    return await self._update_state()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/coordinators.py", line 210, in _update_state
    state = (await self.device.get_state()).get_or_raise()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/ledstrip_device.py", line 20, in get_state
    return (await self._api.get_device_info()).flat_map(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_client.py", line 93, in get_device_info
    return (await self._protocol.send_request(get_info_request)).map(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/passthrough_protocol.py", line 42, in send_request
    response = await self._send_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/passthrough_protocol.py", line 71, in _send_request
    return await self._passthrough.send(request, self._session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/securepassthrough_transport.py", line 128, in send
    response_encrypted = await self._http.async_make_post_cookie(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/common/utils/http_client.py", line 28, in async_make_post_cookie
    return await self._force_read_release(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/common/utils/http_client.py", line 34, in _force_read_release
    await response.read()
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1037, in read
    self._body = await self.content.read()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 375, in read
    block = await self.readany()
            ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 397, in readany
    await self._wait("readany")
  File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 304, in _wait
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/tapo/coordinators.py", line 147, in _async_update_data
    async with async_timeout.timeout(5):
  File "/usr/local/lib/python3.11/site-packages/async_timeout/__init__.py", line 141, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.11/site-packages/async_timeout/__init__.py", line 228, in _do_exit
    raise asyncio.TimeoutError
TimeoutError

2023-09-27 13:25:23.057 ERROR (MainThread) [custom_components.tapo.coordinators] Error fetching tapo data: Unexpected exception: 
```

Error is  repaired after 30 seconds of refresh interval. If i will set it to 5 seconds, it will repair in 5, but logbook will be filled with lights updates.

**Comment by noizo** [comment]
DEBUG Logging
```
2023-09-27 10:22:27.454 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.044 seconds (success: True)
2023-09-27 10:22:34.256 ERROR (MainThread) [custom_components.tapo.coordinators] An error occurred: 
2023-09-27 10:22:34.266 ERROR (MainThread) [custom_components.tapo.coordinators] Exception traceback: Traceback (most recent call last):
  File "/config/custom_components/tapo/coordinators.py", line 147, in _async_update_data
    return await self._update_state()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/coordinators.py", line 208, in _update_state
    state = (await self.device.get_state()).get_or_raise()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/ledstrip_device.py", line 20, in get_state
    return (await self._api.get_device_info()).flat_map(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_client.py", line 93, in get_device_info
    return (await self._protocol.send_request(get_info_request)).map(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/passthrough_protocol.py", line 42, in send_request
    response = await self._send_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/passthrough_protocol.py", line 71, in _send_request
    return await self._passthrough.send(request, self._session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/securepassthrough_transport.py", line 128, in send
    response_encrypted = await self._http.async_make_post_cookie(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/common/utils/http_client.py", line 28, in async_make_post_cookie
    return await self._force_read_release(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/common/utils/http_client.py", line 34, in _force_read_release
    await response.read()
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1037, in read
    self._body = await self.content.read()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 375, in read
    block = await self.readany()
            ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 397, in readany
    await self._wait("readany")
  File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 304, in _wait
    await waiter
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/tapo/coordinators.py", line 146, in _async_update_data
    async with async_timeout.timeout(10):
  File "/usr/local/lib/python3.11/site-packages/async_timeout/__init__.py", line 141, in __aexit__
    self._do_exit(exc_type)
  File "/usr/local/lib/python3.11/site-packages/async_timeout/__init__.py", line 228, in _do_exit
    raise asyncio.TimeoutError
TimeoutError

2023-09-27 10:22:34.267 ERROR (MainThread) [custom_components.tapo.coordinators] Error fetching tapo data: Unexpected exception: 
2023-09-27 10:22:34.268 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 10.013 seconds (success: False)
2023-09-27 10:22:51.051 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.045 seconds (success: True)
2023-09-27 10:22:57.449 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.039 seconds (success: True)
2023-09-27 10:23:04.302 INFO (MainThread) [custom_components.tapo.coordinators] Fetching tapo data recovered
2023-09-27 10:23:04.303 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.047 seconds (success: True)
```

**Comment by noizo** [comment]
@petretiandrea any ideas on this one?
