### ISSUE TITLE
TypeError: Union[arg, ...]: each arg must be a type. Got <module 'datetime' from '/usr/local/lib/python3.10/datetime.py'>.

### ISSUE THREAD

**Issue by logongas** [petretiandrea/home-assistant-tapo-p100#540]
## Version of the integration

Tapo Controller v2.9.1

## Configuration

Tapo P110
Firmware: 1.2.3 Build 230425 Rel.142542
Hardware: 1.0

```
Logger: homeassistant.loader
Source: custom_components/tapo/hub/sensor.py:65
Integration: TP-Link Tapo ([documentation](https://github.com/petretiandrea/home-assistant-tapo-p100), [issues](https://github.com/petretiandrea/home-assistant-tapo-p100/issues))
First occurred: 18:48:52 (4 occurrences)
Last logged: 18:49:55

Unexpected exception importing platform custom_components.tapo.sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 779, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 796, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/tapo/sensor.py", line 14, in <module>
    from custom_components.tapo.hub.sensor import (
  File "/config/custom_components/tapo/hub/sensor.py", line 41, in <module>
    class HumitidySensor(BaseTapoHubChildEntity, SensorEntity):
  File "/config/custom_components/tapo/hub/sensor.py", line 65, in HumitidySensor
    def native_value(self) -> Union[StateType, date, datetime]:
  File "/usr/local/lib/python3.10/typing.py", line 312, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.10/typing.py", line 403, in __getitem__
    return self._getitem(self, parameters)
  File "/usr/local/lib/python3.10/typing.py", line 515, in Union
    parameters = tuple(_type_check(p, msg) for p in parameters)
  File "/usr/local/lib/python3.10/typing.py", line 515, in <genexpr>
    parameters = tuple(_type_check(p, msg) for p in parameters)
  File "/usr/local/lib/python3.10/typing.py", line 176, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: Union[arg, ...]: each arg must be a type. Got <module 'datetime' from '/usr/local/lib/python3.10/datetime.py'>.
```

```
Logger: homeassistant.setup
Source: setup.py:347
First occurred: 18:48:52 (4 occurrences)
Last logged: 18:49:55

Unable to prepare setup for platform tapo.sensor: Platform not found (Exception importing custom_components.tapo.sensor).
```

## Describe the bug

The value of all entities appears as "Not available"

![tapo2](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/1575626/67b05c92-838f-47a9-b271-90077c59fc3d)

## Debug log

```text

Unable to prepare setup for platform tapo.sensor: Platform not found (Exception importing custom_components.tapo.sensor).
18:49:55 – (ERROR) setup.py - el mensaje se produjo por primera vez a las 18:48:52 y aparece 4 veces
Unexpected exception importing platform custom_components.tapo.sensor
18:49:55 – (ERROR) TP-Link Tapo (integración personalizada) - el mensaje se produjo por primera vez a las 18:48:52 y aparece 4 veces

```

**Comment by logongas** [comment]
Ya funciona en home assistant 2023.8.4
