### ISSUE TITLE
P115 switch is unavailable

### ISSUE THREAD

**Issue by pjannink** [petretiandrea/home-assistant-tapo-p100#547]
The P115 switch is showed as unavailable in my HA 2013.10 setup. The P110’s are OK.
Not sure since when this issue is there. I recall I saw it already in the latest 2023.9.x versions.
I run firmware 1.1.6 Build 221114 rel 20339 on the P115.
Also the latest version of the integration.
I see no log entries re the P115 switch.

**Comment by pjannink** [comment]
Edit: firmware seems to be 1.2.3 Build 230425 rel 142542. HW version is 1.0

**Comment by pjannink** [comment]
Readding the P115 goes perfectly well, but 1 entity is simply missing: the on/off switch. Can you please investigate??

**Comment by petretiandrea** [comment]
> Readding the P115 goes perfectly well, but 1 entity is simply missing: the on/off switch. Can you please investigate??

Reload the page, the entities are added asynchronously

**Comment by Will711990** [comment]
Hi !
I have the same behavior...

<img width="990" alt="image" src="https://github.com/petretiandrea/home-assistant-tapo-p100/assets/25400986/9fe51fbe-6b88-42f9-9188-0b66b457db7b">

**Comment by pjannink** [comment]
The issue seems intermittent. The switch was back some restarts ago. Now the switch is unavailable again. Running HA 2023.10.1, further all is up2date too. 
3 other settings seem to have issues also - hope that helps you to diagnose the issue:
![image](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/85283776/0b04105b-69b3-4b45-a756-d4eaf39f8c07)

**Comment by petretiandrea** [comment]
Are you using static IP for your devices?

**Comment by pjannink** [comment]
Yes, a static IP on all Home Assistant related stuff so including all TAPO’s. The P115 is recognized as some entities are ok as you can see in above screenshot

**Comment by brentk7** [comment]
I have the same issue with a new **P110 plug** I have just installed. This is the first Tapo device I have installed - all power monitoring sensors show correctly but there is no switch entity to control the plug. I've checked the logs and below are the only 2 entries mentioning tapo (the second was from when I unplugged the device):
`	Line   19: 2023-10-13 13:07:46.709 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tapo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
	Line 2227: 2023-10-13 13:28:18.967 ERROR (MainThread) [custom_components.tapo.coordinators] Error fetching tapo data: Unexpected exception: 
`
Firmware is 1.2.3 Build 230425 rel 142542. HW version is 1.0

**Comment by pjannink** [comment]
023-10-13 08:58:42.772 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform tapo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1057, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 820, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 785, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 475, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/sensor.py", line 111, in native_value
    return self._sensor_source.get_value(self.coordinator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/sensors/__init__.py", line 110, in get_value
    return coordinator.get_state_of(EnergyInfo).today_runtime
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'today_runtime'
2023-10-13 08:58:43.063 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up tapo platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 367, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1057, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 820, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 785, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 475, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/sensor.py", line 111, in native_value
    return self._sensor_source.get_value(self.coordinator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/sensors/__init__.py", line 110, in get_value
    return coordinator.get_state_of(EnergyInfo).today_runtime
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'today_runtime'
2023-10-13 08:58:44.542 ERROR (MainThread) [custom_components.tapo.coordinators] Unexpected exception from <bound method DataUpdateCoordinator.async_refresh of <custom_components.tapo.coordinators.PlugTapoCoordinator object at 0x7f99f1ac6550>>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 114, in _handle_timer_finish
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 266, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 389, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 172, in async_update_listeners
    update_callback()
  File "/config/custom_components/tapo/entity.py", line 43, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 820, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 785, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 475, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/sensor.py", line 111, in native_value
    return self._sensor_source.get_value(self.coordinator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/sensors/__init__.py", line 110, in get_value
    return coordinator.get_state_of(EnergyInfo).today_runtime
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'today_runtime'

**Comment by pjannink** [comment]
After restart P115  switch is unavailable again:

2023-10-13 12:09:54.062 ERROR (MainThread) [homeassistant.components.switch] tapo: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 573, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 991, in async_device_update
    await self.async_update()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 507, in async_update
    await self.coordinator.async_request_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 240, in async_request_refresh
    await self._debounced_refresh.async_call()
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 93, in async_call
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 266, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 389, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 172, in async_update_listeners
    update_callback()
  File "/config/custom_components/tapo/entity.py", line 43, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 779, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 820, in _async_generate_attributes
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 785, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 475, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/sensor.py", line 111, in native_value
    return self._sensor_source.get_value(self.coordinator)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/sensors/__init__.py", line 110, in get_value
    return coordinator.get_state_of(EnergyInfo).today_runtime
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'today_runtime'

**Comment by BDBAfH** [comment]
+1 for a P110 device

**Comment by robcsi** [comment]
Is a static IP address necessary for the Tapo P115 to be available?

HA cannot even ping the Tapo P115 on the external network (192.168.1.3), but it can ping the router (192.168.1.1) and itself. The Tapo P115 works correctly with the TP-Link Tapo App, showing the 192.168.1.3 IP, the router shows the same.

Could the fact that the P115 has a dynamic IP be the reason for all this?

**Comment by petretiandrea** [comment]
A static is necessary to avoid HA mark as unavailable due to router IP re-assignment to your tapo device

**Comment by pjannink** [comment]
Hi @petretiandrea , any update please? Issue with P115 is NOT resolved with your latest update of the integration. Can we somehow help you with the diagnosis of the issue??

**Comment by petretiandrea** [comment]
You can try to run this snippet
```python
import asyncio
import os

from plugp100.api.hub.hub_device import HubDevice
from plugp100.api.light_effect_preset import LightEffectPreset
from plugp100.api.tapo_client import TapoClient
from plugp100.common.credentials import AuthCredential


async def main():
    # create generic tapo api
    username = os.getenv("USERNAME", "<tapo_email>")
    password = os.getenv("PASSWORD", "<tapo_password>")

    credentials = AuthCredential(username, password)
    client = TapoClient(credentials, "<tapo_device_ip>")
    await client.initialize()

    print(await client.get_device_info())
    print(await client.get_energy_usage())
    print(await client.get_current_power())

    # plug = PlugDevice(TapoClient(username, password), "<tapo_device_ip>")
    # light = LightDevice(TapoClient(username, password), "<tapo_device_ip>")
    # ledstrip = LedStripDevice(TapoClient(username, password), "<tapo_device_ip>")

    # - hub example
    # hub = HubDevice(client)
    # print(await hub.get_children())
    # print(await hub.get_state_as_json())


if __name__ == "__main__":
    loop = asyncio.new_event_loop()
    loop.run_until_complete(main())
    loop.run_until_complete(asyncio.sleep(0.1))
    loop.close()
```

And report here the output

**Comment by pjannink** [comment]
Latest reboot of HA (due to some updated integrations somehow fixed the issue: the switch is working now. Obviously, I will keep you posted re the P115. 
To be honest, no idea how to run a snippet.

**Comment by joaofgf** [comment]
I have the same problem in several P110.

**Comment by petretiandrea** [comment]
Need to run my script

**Comment by pjannink** [comment]
Issue arose again. Running everything on latest versions.
