### ISSUE TITLE
Error executing script. Unexpected error for call_service at pos 1: 'Rainbow'

### ISSUE THREAD

**Issue by stevenazari** [petretiandrea/home-assistant-tapo-p100#582]
## Version of the integration
v2.10.1 stable

## Configuration

L930 - v1.0.9

```yaml
- id: "1682456037783"
  name: 3 Office pinks
  entities:
    switch.cat_water:
      device_class: outlet
      friendly_name: Office head
      state: "on"
    light.office_kallax:
      min_color_temp_kelvin: 2500
      max_color_temp_kelvin: 6500
      min_mireds: 153
      max_mireds: 400
      effect_list:
        - bubblingcauldron
        - aurora
        - candycane
        - christmas
        - flicker
        - christmaslight
        - hanukkah
        - hauntedmansion
        - icicle
        - lightning
        - ocean
        - rainbow
        - raindrop
        - spring
        - sunrise
        - sunset
        - valentines
      supported_color_modes:
        - brightness
        - color_temp
        - hs
        - onoff
      friendly_name: Office kallax
      supported_features: 4
      color_mode: hs
      brightness: 255
      hs_color:
        - 295
        - 99
      rgb_color:
        - 233
        - 2
        - 255
      xy_color:
        - 0.357
        - 0.142
      state: "on"
  metadata:
    light.office_kallax:
      entity_only: true
  icon: mdi:desktop-classic
- id: "1682456224579"
  name: 2 Office White
  entities:
    switch.cat_water:
      device_class: outlet
      friendly_name: Office head
      state: "on"
    light.office_kallax:
      min_color_temp_kelvin: 2500
      max_color_temp_kelvin: 6500
      min_mireds: 153
      max_mireds: 400
      effect_list:
        - bubblingcauldron
        - aurora
        - candycane
        - christmas
        - flicker
        - christmaslight
        - hanukkah
        - hauntedmansion
        - icicle
        - lightning
        - ocean
        - rainbow
        - raindrop
        - spring
        - sunrise
        - sunset
        - valentines
      supported_color_modes:
        - brightness
        - color_temp
        - hs
        - onoff
      color_mode: color_temp
      brightness: 255
      color_temp_kelvin: 6535
      color_temp: 153
      hs_color:
        - 54.768
        - 1.6
      rgb_color:
        - 255
        - 254
        - 250
      xy_color:
        - 0.326
        - 0.333
      friendly_name: Office kallax
      supported_features: 4
      state: "on"
  metadata:
    light.office_kallax:
      entity_only: true
  icon: mdi:desktop-classic
- id: "1697651778268"
  name: 1 Office Streamin
  entities:
    switch.cat_water:
      device_class: outlet
      friendly_name: Office head
      state: "on"
    light.office_kallax:
      min_color_temp_kelvin: 2500
      max_color_temp_kelvin: 6500
      min_mireds: 153
      max_mireds: 400
      effect_list:
        - bubblingcauldron
        - aurora
        - candycane
        - christmas
        - flicker
        - christmaslight
        - hanukkah
        - hauntedmansion
        - icicle
        - lightning
        - ocean
        - rainbow
        - raindrop
        - spring
        - sunrise
        - sunset
        - valentines
      supported_color_modes:
        - brightness
        - color_temp
        - hs
        - onoff
      friendly_name: Office kallax
      supported_features: 4
      color_mode: color_temp
      brightness: 255
      color_temp_kelvin: 2500
      color_temp: 400
      hs_color:
        - 28.874
        - 72.522
      rgb_color:
        - 255
        - 159
        - 70
      xy_color:
        - 0.546
        - 0.389
      effect: Rainbow
      state: "on"
  icon: mdi:desktop-classic
  metadata:
    light.office_kallax:
      entity_only: true

```

## Describe the bug

Trying to use the scene "1 office streamin" an effect breaks the integration with above error and a timeout. using a standard colour works, but effects break it. This used to happen if the effect wasn't named with a capital letter (Rainbow > rainbow). however this no longer resolves the issue.

Additionally, changing the scene with a different effect does not show the save button and you need to edit another field to force it through.

## Debug log

```text

Logger: homeassistant.components.automation.office_light_on
Source: helpers/script.py:468
Integration: Automation ([documentation](https://www.home-assistant.io/integrations/automation), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+automation%22))
First occurred: 19:40:41 (1 occurrences)
Last logged: 19:40:41

Office lights 100: Error executing script. Unexpected error for call_service at pos 1: 'Rainbow'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 704, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 666, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2012, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2049, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 876, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/scene/__init__.py", line 114, in _async_activate
    await self.async_activate(**kwargs)
  File "/usr/src/homeassistant/homeassistant/components/homeassistant/scene.py", line 334, in async_activate
    await async_reproduce_state(
  File "/usr/src/homeassistant/homeassistant/helpers/state.py", line 67, in async_reproduce_state
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/helpers/state.py", line 61, in worker
    await platform.async_reproduce_states(
  File "/usr/src/homeassistant/homeassistant/components/light/reproduce_state.py", line 195, in async_reproduce_states
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/components/light/reproduce_state.py", line 182, in _async_reproduce_state
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2012, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2049, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 876, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 580, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/config/custom_components/tapo/light.py", line 170, in async_turn_on
    self._effects[effect].to_effect()
    ~~~~~~~~~~~~~^^^^^^^^
KeyError: 'Rainbow'

```

**Comment by stevenazari** [comment]
The problem was the device being referenced as an entity not a device.
