### ISSUE TITLE
Error importing sensors for P110 socket

### ISSUE THREAD

**Issue by 8illy8o8** [petretiandrea/home-assistant-tapo-p100#583]
I have just tried to setup a new P110 energy monitoring plug which does install as a switch with temperature sensor but does not create the energy sensors with associated invalid configuration errors.:

## Version of the integration

2.10.1

## Configuration

Device: P110
Hardware version 1.0
Firmware version 1.2.3 Build 230425 Ref 142542

## Describe the bug

No energy sensors are available in HA after adding a Tapo P110 energy monitoring socket. The energy stats are available in the Tapo app. HA generates an invalid config notification with 2 logs:

Home Assistant Core

Unable to prepare setup for platform tapo.sensor: Platform not found (Exception importing custom_components.tapo.sensor).
2:54:11 PM – (ERROR) setup.py

Unexpected exception importing platform custom_components.tapo.sensor
2:54:11 PM – (ERROR) TP-Link Tapo (custom integration)

```text
First log error:

Logger: homeassistant.setup
Source: setup.py:347
First occurred: 2:54:11 PM (1 occurrences)
Last logged: 2:54:11 PM

Unable to prepare setup for platform tapo.sensor: Platform not found (Exception importing custom_components.tapo.sensor).

Second log error:

Logger: homeassistant.loader
Source: custom_components/tapo/hub/sensor.py:65
Integration: TP-Link Tapo ([documentation](https://github.com/petretiandrea/home-assistant-tapo-p100), [issues](https://github.com/petretiandrea/home-assistant-tapo-p100/issues))
First occurred: 2:54:11 PM (1 occurrences)
Last logged: 2:54:11 PM

Unexpected exception importing platform custom_components.tapo.sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 779, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 796, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/tapo/sensor.py", line 14, in <module>
    from custom_components.tapo.hub.sensor import (
  File "/config/custom_components/tapo/hub/sensor.py", line 41, in <module>
    class HumitidySensor(BaseTapoHubChildEntity, SensorEntity):
  File "/config/custom_components/tapo/hub/sensor.py", line 65, in HumitidySensor
    def native_value(self) -> Union[StateType, date, datetime]:
  File "/usr/local/lib/python3.10/typing.py", line 312, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.10/typing.py", line 403, in __getitem__
    return self._getitem(self, parameters)
  File "/usr/local/lib/python3.10/typing.py", line 515, in Union
    parameters = tuple(_type_check(p, msg) for p in parameters)
  File "/usr/local/lib/python3.10/typing.py", line 515, in <genexpr>
    parameters = tuple(_type_check(p, msg) for p in parameters)
  File "/usr/local/lib/python3.10/typing.py", line 176, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: Union[arg, ...]: each arg must be a type. Got <module 'datetime' from '/usr/local/lib/python3.10/datetime.py'>.

```

**Comment by 8illy8o8** [comment]
Updating HA to 2023.10.3 fixed the issue.
