### ISSUE TITLE
S505: Error during any interaction: TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

### ISSUE THREAD

**Issue by jonahwh** [petretiandrea/home-assistant-tapo-p100#593]
## Version of the integration

2.10.2

## Configuration

```yaml
S505
by TP-Link
Firmware: 1.0.4 Build 230822 Rel.101556
Hardware: 1.0
```

## Describe the bug

Whenever an S505 is interacted with, I receive the error shown below. This happens during periodic state updates or when turning the light on or off.

Turning the light on or off works, but then the error is thrown. 

## Debug log

```text
[36m2023-11-02 08:45:33.211 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.030 seconds (success: True)
[31m2023-11-02 08:45:33.211 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/update_coordinator.py", line 233, in _handle_refresh_interval
await self._async_refresh(log_failures=True, scheduled=True)
File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/update_coordinator.py", line 389, in _async_refresh
self.async_update_listeners()
File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/update_coordinator.py", line 172, in async_update_listeners
update_callback()
File "/config/custom_components/tapo/entity.py", line 43, in _handle_coordinator_update
self.async_write_ha_state()
File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 779, in async_write_ha_state
self._async_write_ha_state()
File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 879, in _async_write_ha_state
state, attr = self._async_generate_attributes()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/lsiopy/lib/python3.11/site-packages/homeassistant/helpers/entity.py", line 822, in _async_generate_attributes
attr.update(self.state_attributes or {})
^^^^^^^^^^^^^^^^^^^^^
File "/lsiopy/lib/python3.11/site-packages/homeassistant/components/light/__init__.py", line 1007, in state_attributes
color_mode = self._light_internal_color_mode
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/lsiopy/lib/python3.11/site-packages/homeassistant/components/light/__init__.py", line 842, in _light_internal_color_mode
if ColorMode.BRIGHTNESS in supported and self.brightness is not None:
^^^^^^^^^^^^^^^
File "/config/custom_components/tapo/light.py", line 100, in brightness
return round((self.coordinator.light_state.brightness * 255) / 100)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
```

**Comment by jonahwh** [comment]
It looks like the issue is

`"s505": [ColorMode.ONOFF, ColorMode.BRIGHTNESS],`

The s505 does not support brightness. The version that supports brightness is the [S505D](https://www.tapo.com/us/product/smart-switch/tapo-s505d/)

**Comment by petretiandrea** [comment]
New version fix ti
