### ISSUE TITLE
Unable to add P100 plugs after updating to release 2.12 from 2.11

### ISSUE THREAD

**Issue by Richtea82** [petretiandrea/home-assistant-tapo-p100#627]
In V2.11 I added a couple of plugs using the add device (rather than YAML) and it worked great.

Updated to V2.12, the already added plugs worked fine but I went to add a couple of other plugs (specifically P100, HW version 1.20.0, FW 1.5.5) with the same method and it failed.

Rolled back to V2.11 and was able to add the other plugs.

Some logs when the adding was failing:

2023-11-28 21:33:00.813 ERROR (MainThread) [custom_components.tapo.config_flow] Failed to setup cannot connect 
Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 192, in _get_first_data_from_api
    (await tapo_client.get_device_info())
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_client.py", line 96, in get_device_info
    return (await self._protocol.send_request(get_info_request)).map(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/klap_protocol.py", line 49, in send_request
    response = await self._send_request(request, retry)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/klap_protocol.py", line 59, in _send_request
    new_session = await self.perform_handshake()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/klap_protocol.py", line 102, in perform_handshake
    seeds = await self.perform_handshake1(new_local_seed)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/klap_protocol.py", line 174, in perform_handshake1
    "Server response doesn't match our expected hash on ip %s but an authentication with blank credentials matched"
TypeError: not all arguments converted during string formatting

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 119, in async_step_user
    device_data = await self._get_first_data_from_api(tapo_client)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/config_flow.py", line 199, in _get_first_data_from_api
    raise CannotConnect from error
custom_components.tapo.errors.CannotConnect

**Comment by juahan** [comment]
For me adding P110 with firmware 1.3.0 gives the same error, same with 2.12 and 2.11.

**Comment by jtizzel** [comment]
I am also unable to add (two separate) P100s, although I don’t know how to view the related system logs to provide more information. This applies to the current and previous versions of the integration.

**Comment by juahan** [comment]
I noticed that one of my plugs is still firmware 1.1.6 Build 221114 Rel.203339. When I try to add that, it weirdly does not accept my credentials, which are correct 100% certainty as I'm pasting it from my password manager. Also, I don't have the 2FA enabled.

With the 1.30 firmware there is a connection error.

**Comment by juahan** [comment]
It was very confusing, later it went from cannot connect to "invalid credentials. More information, in my case everything started working when I made a new account. I assume my email was in capital letters, even though it never showed like that. Another thing I wonder is that maybe the account has some security features as the old Tapo account was made in Germany and now I'm living in Finland. So I could now finally connect my plugs to Hassio. Anyway, now it works for me.

**Comment by petretiandrea** [comment]
Duplicate of #658
