### ISSUE TITLE
Default protocol not working, fallback to KLAP ;)

### ISSUE THREAD

**Issue by iz8mbw** [petretiandrea/home-assistant-tapo-p100#632]
Hello.
I have this message into "home-assistant.log":

`2023-12-02 14:44:45.576 WARNING (MainThread) [plugp100.api.tapo_client] Default protocol not working, fallback to KLAP ;)`

**Comment by pleasedtohavemetyou** [comment]
I have also received this error. 

`This error originated from a custom integration.

Logger: plugp100.api.tapo_client
Source: custom_components/tapo/setup_helpers.py:101
Integration: TP-Link Tapo (documentation, issues)
First occurred: 1 December 2023 at 11:00:34 (8 occurrences)
Last logged: 13:25:42

Default protocol not working, fallback to KLAP ;)`

**Comment by xavier-wong-hk** [comment]
These are the logs when the device was added into HA

2023-12-04 04:14:53.708 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.160 seconds (success: True)
2023-12-04 04:14:55.442 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.161 seconds (success: True)
2023-12-04 04:14:55.564 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.184 seconds (success: True)
2023-12-04 04:14:55.695 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.161 seconds (success: True)
2023-12-04 04:15:03.780 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.178 seconds (success: True)
2023-12-04 04:15:09.450 WARNING (MainThread) [plugp100.api.tapo_client] Default protocol not working, fallback to KLAP ;)
2023-12-04 04:15:09.552 INFO (MainThread) [custom_components.tapo.setup_helpers] Trying to track ip address of 5C-62-8B-B1-DC-91, last known ip is 192.168.3.18
2023-12-04 04:15:14.973 DEBUG (MainThread) [custom_components.tapo.setup_helpers] Re-using setup API to create a coordinator
2023-12-04 04:15:15.565 INFO (MainThread) [custom_components.tapo.coordinators] Detected model of 192.168.3.18: p110
2023-12-04 04:15:16.169 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.603 seconds (success: True)
2023-12-04 04:15:18.945 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 2.752 seconds (success: True)
2023-12-04 04:15:20.457 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.916 seconds (success: True)
2023-12-04 04:15:20.782 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.590 seconds (success: True)
2023-12-04 04:15:22.115 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.721 seconds (success: True)
2023-12-04 04:15:23.715 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.167 seconds (success: True)
2023-12-04 04:15:25.439 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.158 seconds (success: True)
2023-12-04 04:15:25.544 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.164 seconds (success: True)
2023-12-04 04:15:25.708 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.174 seconds (success: True)

**Comment by codyc1515** [comment]
Not sure what changed but I am facing this issue also since a few days. The devices appear to still be functional.

**Comment by tjorim** [comment]
As far as I know it's related to the latest firmware update. Happened with my P110 since it upgraded from 1.2.3 to 1.3.0. I disabled automatic firmware updates for now. Version 1.3.0 is available for my P115 plugs as well.

**Comment by codyc1515** [comment]
I agree it was likely related to that.

**Comment by xavier-wong-hk** [comment]
I got 9 P110 plugs are on 1.3.0 and 2 P100 on 1.2.1.
All of them are up and running normally except 1 of the P110 and 2 P100 (which newly added into HA) facing this issue

**Comment by iridium2001** [comment]
Also have this error for quite a while now. Several P100, P110 and KP115 plugs installed. Seems not to affect functionality, but I would really like to get this cleared from the logs.

**Comment by petretiandrea** [comment]
It's not an error, but a warning, I will convert it into info log

**Comment by ramza007** [comment]
![Screen Shot 2023-12-16 at 5 46 36 PM](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/36161184/673a2dd1-8273-4c43-ab59-3c40970eb710)

After auto update for the Tapo L930 to firmware v. 1.1.2  (didn't know I could turn it off) the integration fails to start. Ive tried restarting home assistant and the lightstrips and tried reinstalling the plugin. I cant log back in.

**Comment by ramza007** [comment]
> ![Screen Shot 2023-12-16 at 5 46 36 PM](https://private-user-images.githubusercontent.com/36161184/291018652-673a2dd1-8273-4c43-ab59-3c40970eb710.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3NzIxODQsIm5iZiI6MTcwMjc3MTg4NCwicGF0aCI6Ii8zNjE2MTE4NC8yOTEwMTg2NTItNjczYTJkZDEtODI3My00YzQzLWFiNTktM2M0MDk3MGViNzEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE3VDAwMTEyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlMDk3YTJhNTEyYmEzOTIwZTg0NmExYTQ3ZjZjYjdiMmY4NDcwMzZkZTAzYWI3NGM4YzFiMTczNjJkYzdjNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JB5XEpPwPUHhnOS9AWGGRtN4AQMfwleLIa1vu1JSDnU)
> 
> After auto update for the Tapo L930 to firmware v. 1.1.2 (didn't know I could turn it off) the integration fails to start. Ive tried restarting home assistant and the lightstrips and tried reinstalling the plugin. I cant log back in.

![Screen Shot 2023-12-16 at 7 15 17 PM](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/36161184/d2f32505-3f05-48e2-9dff-afc6699b96eb)

**Comment by petretiandrea** [comment]
I've a fix for this, is related to #652

**Comment by ramza007** [comment]
Works perfect now. Thanks!

**Comment by synfyi** [comment]
I am still getting this issue with my L510

**Comment by synfyi** [comment]
`2023-12-29 19:20:54.045 WARNING (MainThread) [plugp100.api.tapo_client] Default protocol not working, fallback to KLAP ;)
2023-12-29 19:20:54.065 ERROR (MainThread) [custom_components.tapo.config_flow] Failed to setup cannot connect 
Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 192, in _get_first_data_from_api
    (await tapo_client.get_device_info())
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_client.py", line 92, in get_device_info
    return await self.execute_raw_request(get_info_request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_client.py", line 78, in execute_raw_request
    return (await self._protocol.send_request(request)).map(lambda x: x.result)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/klap_protocol.py", line 49, in send_request
    response = await self._send_request(request, retry)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/klap_protocol.py", line 59, in _send_request
    new_session = await self.perform_handshake()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/klap_protocol.py", line 104, in perform_handshake
    seeds = await self.perform_handshake1(new_local_seed)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/klap_protocol.py", line 176, in perform_handshake1
    "Server response doesn't match our expected hash on ip %s but an authentication with blank credentials matched"
TypeError: not all arguments converted during string formatting

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 119, in async_step_user
    device_data = await self._get_first_data_from_api(tapo_client)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/config_flow.py", line 199, in _get_first_data_from_api
    raise CannotConnect from error
custom_components.tapo.errors.CannotConnect
2023-12-29 19:21:55.554 WARNING (MainThread) [plugp100.api.tapo_client] Default protocol not working, fallback to KLAP ;)
2023-12-29 19:21:55.584 ERROR (MainThread) [custom_components.tapo.config_flow] Failed to setup cannot connect 
Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 192, in _get_first_data_from_api
    (await tapo_client.get_device_info())
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_client.py", line 92, in get_device_info
    return await self.execute_raw_request(get_info_request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_client.py", line 78, in execute_raw_request
    return (await self._protocol.send_request(request)).map(lambda x: x.result)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/klap_protocol.py", line 49, in send_request
    response = await self._send_request(request, retry)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/klap_protocol.py", line 59, in _send_request
    new_session = await self.perform_handshake()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/klap_protocol.py", line 104, in perform_handshake
    seeds = await self.perform_handshake1(new_local_seed)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/klap_protocol.py", line 176, in perform_handshake1
    "Server response doesn't match our expected hash on ip %s but an authentication with blank credentials matched"
TypeError: not all arguments converted during string formatting

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 119, in async_step_user
    device_data = await self._get_first_data_from_api(tapo_client)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/config_flow.py", line 199, in _get_first_data_from_api
    raise CannotConnect from error
custom_components.tapo.errors.CannotConnect
2023-12-29 19:24:15.804 ERROR (MainThread) [custom_components.tapo.config_flow] Failed to setup cannot connect 
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 628, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 668, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('10.0.4.21', 80)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 192, in _get_first_data_from_api
    (await tapo_client.get_device_info())
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_client.py", line 92, in get_device_info
    return await self.execute_raw_request(get_info_request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_client.py", line 77, in execute_raw_request
    await self._initialize_protocol_if_needed()
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_client.py", line 71, in _initialize_protocol_if_needed
    await self._guess_protocol()
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_client.py", line 221, in _guess_protocol
    response = await self.get_component_negotiation()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_client.py", line 81, in get_component_negotiation
    return (await self.execute_raw_request(TapoRequest.component_negotiation())).map(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_client.py", line 78, in execute_raw_request
    return (await self._protocol.send_request(request)).map(lambda x: x.result)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/passthrough_protocol.py", line 41, in send_request
    response = await self._send_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/passthrough_protocol.py", line 61, in _send_request
    await self._login_with_version(self._credential)
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/passthrough_protocol.py", line 80, in _login_with_version
    session_or_error = await self._passthrough.handshake(self._url)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/securepassthrough_transport.py", line 70, in handshake
    response = await self._http.async_make_post(url, json=request_body)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/common/utils/http_client.py", line 18, in async_make_post
    async with self.session.post(
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1187, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 574, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 911, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1235, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1204, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1000, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 10.0.4.21:80 ssl:default [Connect call failed ('10.0.4.21', 80)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 119, in async_step_user
    device_data = await self._get_first_data_from_api(tapo_client)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/config_flow.py", line 199, in _get_first_data_from_api
    raise CannotConnect from error
custom_components.tapo.errors.CannotConnect`
