### ISSUE TITLE
Server response doesn't match our challenge on ip %s

### ISSUE THREAD

**Issue by Smoot178** [petretiandrea/home-assistant-tapo-p100#658]
Home Assistant Core 2023.12.3, Supervisor 2023.12.0, Operating System 11.2, Frontend 20231208.2
Tapo Controller 2.12.2
Tapo S500D 1.1.0 Build 230906 Rel. 141935

Unable to add my first Tapo device.  Receiving log entry:

```
Logger: homeassistant.components.switch
Source: helpers/entity_platform.py:361
Integration: Switch ([documentation](https://www.home-assistant.io/integrations/switch), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+switch%22))
First occurred: 9:58:41 PM (1 occurrences)
Last logged: 9:58:41 PM

Error while setting up tapo platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/tapo/switch.py", line 32, in async_setup_platform
    coordinator = await setup_from_platform_config(hass, config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/setup_helpers.py", line 74, in setup_from_platform_config
    return await create_coordinator(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/coordinators.py", line 67, in create_coordinator
    device_info = (await client.get_device_info()).map(lambda x: TapoDeviceInfo(**x))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_client.py", line 92, in get_device_info
    return await self.execute_raw_request(get_info_request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_client.py", line 78, in execute_raw_request
    return (await self._protocol.send_request(request)).map(lambda x: x.result)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/klap_protocol.py", line 49, in send_request
    response = await self._send_request(request, retry)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/klap_protocol.py", line 59, in _send_request
    new_session = await self.perform_handshake()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/klap_protocol.py", line 104, in perform_handshake
    seeds = await self.perform_handshake1(new_local_seed)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/klap_protocol.py", line 198, in perform_handshake1
    "Server response doesn't match our challenge on ip %s"
TypeError: not all arguments converted during string formatting
```

Also seeing the following:

```
Logger: plugp100.api.tapo_client
Source: custom_components/tapo/coordinators.py:67
Integration: TP-Link Tapo ([documentation](https://github.com/petretiandrea/home-assistant-tapo-p100), [issues](https://github.com/petretiandrea/home-assistant-tapo-p100/issues))
First occurred: 9:58:41 PM (1 occurrences)
Last logged: 9:58:41 PM

Default protocol not working, fallback to KLAP ;)

```

**Comment by michlalp** [comment]
Hi, same here...

**Comment by develeon** [comment]
Same here (P115)

**Comment by petretiandrea** [comment]
Solved in 2.13.0 with automatic retry

**Comment by RohanM** [comment]
On 2.13.0 I'm seeing something very similar. When I upgrade from 2.11.0, two of my L530B lights show the error "Failed setup, will retry", with the hover text "not all arguments converted during string formatting". Other lights of the same model continue working just fine.

When I remove one of the non-functioning light devices and attempt to re-add it, I see this error in the debug log:

```
2024-02-04 11:04:25.383 ERROR (MainThread) [custom_components.tapo.config_flow] Failed to setup cannot connect 
Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 192, in _get_first_data_from_api
    (await tapo_client.get_device_info())
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_client.py", line 92, in get_device_info
    return await self.execute_raw_request(get_info_request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_client.py", line 78, in execute_raw_request
    return (await self._protocol.send_request(request)).map(lambda x: x.result)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/klap_protocol.py", line 49, in send_request
    response = await self._send_request(request, retry)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/klap_protocol.py", line 59, in _send_request
    new_session = await self.perform_handshake()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/klap_protocol.py", line 104, in perform_handshake
    seeds = await self.perform_handshake1(new_local_seed)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/klap_protocol.py", line 176, in perform_handshake1
    "Server response doesn't match our expected hash on ip %s but an authentication with blank credentials matched"
TypeError: not all arguments converted during string formatting

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 119, in async_step_user
    device_data = await self._get_first_data_from_api(tapo_client)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/config_flow.py", line 199, in _get_first_data_from_api
    raise CannotConnect from error
custom_components.tapo.errors.CannotConnect
```

Device info:
- Tapo L530
- Hardware version 2.0
- Firmware version 1.1.0 Build 230721 Rel.224802

Puzzlingly, the lights that continued working show exactly the same device info as above.

Software info:
- Tapo Controller 2.13.0
- HACS 1.34.0
- Home Assistant Core 2024.1.6
- Supervisor 2023.12.1
- Operating System 11.4
- Frontend 20240104.0

**Comment by GitSlinger** [comment]
Has anyone had any success with this?
I'm not able to add any of my P100 or P110 and just get "Invalid authentication: Server response doesn't match our challenge on ip" any time I submit my login details when getting to add a device

**Comment by Budgiebrain994** [comment]
Same issue here. It was fine intiially, but after I switched the device's WiFi network and changed its name, I am no longer able to set up the device again.

**Comment by xerosilence** [comment]
have the same problem, getting error message:

 Invalid authentication: Server response doesn't match our challenge on ip 192.168.1.xxx

**Comment by Mandel82** [comment]
Budgiebrain994I also have the same problem as you. did you solve it?

**Comment by Budgiebrain994** [comment]
> Budgiebrain994I also have the same problem as you. did you solve it?

Yes, I solved this issue.

I reset my Tapo/TP-link password in their app, and used the new password to log in through Home Assistant again. It worked.

**Comment by Budgiebrain994** [comment]
Also, don't let the auto-discovery system add your device! Go manually into TP-Link, scroll down and tap "add device". On the setup page, don't add a host, just tap Submit and use those ones discovered.

**Comment by niveknow** [comment]
@p-afraz  suggestion above was the winner for me.  Changed password from current to current allowed HA to immediately Add my TP115 outlets.  Didn't need a reboot or anything.  Thanks.

**Comment by mtnman1000** [comment]
I have tried all of these suggestions to add 3 new Tapo P105 plugs and still get:

Invalid authentication: Server response doesn't match our challenge on ip 192.168.86.54

`2024-12-20 08:12:25.062 DEBUG (MainThread) [kasa.transports.klaptransport] Created KLAP transport for 192.168.86.54
2024-12-20 08:12:25.064 DEBUG (MainThread) [kasa.device] Initializing 192.168.86.54 of type <class 'kasa.smart.smartdevice.SmartDevice'>
2024-12-20 08:12:25.064 DEBUG (MainThread) [kasa.protocols.smartprotocol] 192.168.86.54 multi-request-batch-1-of-1 >> '{"method":"multipleRequest","request_time_milis":1734711145065,"terminal_uuid":REDACTED,"params":{"requests":[{"method":"component_nego"},{"method":"get_device_info"},{"method":"get_connect_cloud_state"}]}}'
2024-12-20 08:12:25.064 DEBUG (MainThread) [kasa.transports.klaptransport] Starting handshake with 192.168.86.54
2024-12-20 08:12:25.064 DEBUG (MainThread) [kasa.httpclient] Posting to http://192.168.86.54/app/handshake1
2024-12-20 08:12:25.079 DEBUG (MainThread) [kasa.transports.klaptransport] Handshake1 posted at 2024-12-20 08:12:25.079727. Host is 192.168.86.54, Response status is 200, Request was REDACTED
2024-12-20 08:12:25.081 DEBUG (MainThread) [kasa.transports.klaptransport] Handshake1 success at 2024-12-20 08:12:25.081007. Host is 192.168.86.54, Server remote_seed is: REDACTED, server hash is: REDACTED
2024-12-20 08:12:25.081 DEBUG (MainThread) [kasa.transports.klaptransport] Server response doesn't match our challenge on ip 192.168.86.54
2024-12-20 08:12:25.081 DEBUG (MainThread) [kasa.protocols.smartprotocol] Unable to authenticate with 192.168.86.54, not retrying: Server response doesn't match our challenge on ip 192.168.86.54`

All TP-Link devices are working fine. 

Any more suggestions?

**Comment by 1981mofo** [comment]
same issue and error with HS200 (HW 5.26, FW 1.0.3) & HS220 (HW 3.26, FW 1.1.1)
HA Core 2024.12.5, Supervisor 2024.12.0, OS 14.1, FE 20241127.8

2 FA is disabled

changed the password to remove special characters
reset password from current to current
reset switch; removed from app and rediscovered it

still no cigar 

i have several other KASA devices that don't require authentication and they registered fine in HA
