### ISSUE TITLE
Error executing service: <ServiceCall light.turn_on>

### ISSUE THREAD

**Issue by komOrmand** [petretiandrea/home-assistant-tapo-p100#66]
Sometimes when I when I want to change color there happens such bug:

Эта ошибка возникла в кастомной интеграции.

`Logger: homeassistant.core
Source: custom_components/tapo/tapo_entity.py:33
Integration: Tapo Controller (documentation, issues)
First occurred: 10:41:19 (3 occurrences)
Last logged: 18:47:35

Error executing service: <ServiceCall light.turn_on (c:83e4f5f4b3e68fc9ac93f88e5b545028): entity_id=['light.tapo_2'], params=hs_color=(120.0, 71.42857142857142)>
Error executing service: <ServiceCall light.turn_on (c:f5e7d4ed92b757320d88911ff520d9e7): entity_id=['light.tapo_2'], params=hs_color=(240.0, 85.71428571428571)>
Error executing service: <ServiceCall light.turn_on (c:1ca72b17a5689dfbf3b18148cf267970): entity_id=['light.tapo_2'], params=brightness=255>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect
    return await fut
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 528, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionResetError: [Errno 104] Connect call failed ('192.168.1.103', 80)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/tapo/tapo_entity.py", line 31, in _execute_with_fallback
    return await function()
  File "/usr/local/lib/python3.8/site-packages/plugp100/api.py", line 121, in set_hue_saturation
    return await self.set_device_info(LightParams(hue=hue, saturation=saturation))
  File "/usr/local/lib/python3.8/site-packages/plugp100/api.py", line 76, in set_device_info
    await self._set_device_info(device_params.as_dict(), terminal_uuid)
  File "/usr/local/lib/python3.8/site-packages/plugp100/api.py", line 94, in _set_device_info
    response = await self.http.async_make_post_cookie(f"{self.url}?token={self.token}", request_body,
  File "/usr/local/lib/python3.8/site-packages/plugp100/core/http_client.py", line 18, in async_make_post_cookie
    async with self.session.post(url, json=json, cookies=cookie) as response:
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 520, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 535, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 892, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1051, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1020, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 975, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.1.103:80 ssl:default [Connect call failed ('192.168.1.103', 80)]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1507, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1526, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 658, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 760, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 695, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 417, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/config/custom_components/tapo/light.py", line 94, in async_turn_on
    await self._change_color([hue, saturation])
  File "/config/custom_components/tapo/light.py", line 123, in _change_color
    await self._execute_with_fallback(
  File "/config/custom_components/tapo/tapo_entity.py", line 33, in _execute_with_fallback
    await self.coordinator.api.login()
  File "/usr/local/lib/python3.8/site-packages/plugp100/api.py", line 69, in login
    await self._handshake()
  File "/usr/local/lib/python3.8/site-packages/plugp100/api.py", line 146, in _handshake
    self.tp_link_cipher = self.encryption.decode_handshake_key(resp_dict['result']['key'], self.key_pair)
  File "/usr/local/lib/python3.8/site-packages/plugp100/core/encryption.py", line 38, in decode_handshake_key
    do_final = cipher.decrypt(decode, None)
  File "/usr/local/lib/python3.8/site-packages/Crypto/Cipher/PKCS1_v1_5.py", line 169, in decrypt
    m_int = self._key._decrypt(ct_int)
  File "/usr/local/lib/python3.8/site-packages/Crypto/PublicKey/RSA.py", line 154, in _decrypt
    raise ValueError("Ciphertext too large")
ValueError: Ciphertext too large`

Also this one:

`Эта ошибка возникла в кастомной интеграции.

Logger: custom_components.tapo
Source: helpers/update_coordinator.py:219
Integration: Tapo Controller (documentation, issues)
First occurred: 08:38:50 (215 occurrences)
Last logged: 18:57:06

Error fetching tapo data:`

![изображение](https://user-images.githubusercontent.com/87458360/130650945-5e008369-58f7-424b-8510-26cf744b977a.png)

**Comment by komOrmand** [comment]
Problem was solwed by removing an old repo from custom components.
