### ISSUE TITLE
P105: error_code: -1012 msg: No message

### ISSUE THREAD

**Issue by Tatooiner** [petretiandrea/home-assistant-tapo-p100#667]
## Version of the integration
2.12.2

## Configuration
1.3.6 Build 20230308 Rel. 52591

## Describe the bug

I am experiencing an issue with the "on/off" switch for P105.
If I turn it on or off from the TP-Link iOS app, I can see the status of the switch changing on Home Assistant, but if I try to turn the device on or off from Home Assistant, I receive this error:
**Failed to call service switch/turn_off. Returned unknown error_code: -1012 msg: No message**

## Debug log

```text

2024-01-01 19:43:46.495 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140180228175040] Returned unknown error_code: -1012  msg: No message
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2067, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2104, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 878, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/tapo/switch.py", line 74, in async_turn_on
    (await self.coordinator.device.on()).get_or_raise()
  File "/usr/local/lib/python3.11/site-packages/plugp100/common/functional/tri.py", line 159, in get_or_raise
    raise self.value
plugp100.responses.tapo_exception.TapoException: Returned unknown error_code: -1012  msg: No message

```

**Comment by Tatooiner** [comment]
Today the devices updated to Firmware: 1.4.1 Build 20231103 Rel. 36519 and that has fixed the issue 😊
