### ISSUE TITLE
Don't get Kasa Hub or Tapo Hub working after changing to static IP

### ISSUE THREAD

**Issue by whatamanoffical** [petretiandrea/home-assistant-tapo-p100#690]
@petretiandrea I hope you or somebody else can help me!

I had a working integration with 8 KE100 thermostats in HA. I use TAPO Hub and KASA hub at home on dynamic IPs, everything is integrated in the TAPO app and worked before I had to restart my router (due to another reason). Now, after the restart of the router, the integration stopped working for the KE100 via TAPO. I tried to remove, change IP adress etc. I decided to give the KASA and TAPO Hub static ips now but I do reach the host when adding into the integration and get the notorious failed to connect error:

![Screenshot 2024-01-31 at 11 09 15](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/157410409/ff71cdd4-018b-4bd9-a289-ce87b4922a7d)

Questions:

Should I connect as HOST to the Ip adress of the a) KASA HUB or the b) TAPO HUB (both integrated in TAPO app)
Do you recommend static or dynamic IP?
Any comments or hints would be highly appreciated!!! Thank you

Here comes my logs:

2024-01-31 11:07:39.775 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.052 seconds (success: True)
2024-01-31 11:08:09.768 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.045 seconds (success: True)
2024-01-31 11:08:39.776 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.053 seconds (success: True)
2024-01-31 11:09:09.767 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.043 seconds (success: True)
2024-01-31 11:09:39.782 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.058 seconds (success: True)
2024-01-31 11:09:48.648 ERROR (MainThread) [custom_components.tapo.config_flow] Failed to setup cannot connect 
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 628, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/selector_events.py", line 668, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 110] Connect call failed ('192.168.68.103', 80)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 192, in _get_first_data_from_api
    (await tapo_client.get_device_info())
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_client.py", line 92, in get_device_info
    return await self.execute_raw_request(get_info_request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_client.py", line 77, in execute_raw_request
    await self._initialize_protocol_if_needed()
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_client.py", line 71, in _initialize_protocol_if_needed
    await self._guess_protocol()
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_client.py", line 221, in _guess_protocol
    response = await self.get_component_negotiation()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_client.py", line 81, in get_component_negotiation
    return (await self.execute_raw_request(TapoRequest.component_negotiation())).map(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_client.py", line 78, in execute_raw_request
    return (await self._protocol.send_request(request)).map(lambda x: x.result)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/passthrough_protocol.py", line 41, in send_request
    response = await self._send_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/passthrough_protocol.py", line 61, in _send_request
    await self._login_with_version(self._credential)
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/passthrough_protocol.py", line 80, in _login_with_version
    session_or_error = await self._passthrough.handshake(self._url)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/securepassthrough_transport.py", line 70, in handshake
    response = await self._http.async_make_post(url, json=request_body)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/common/utils/http_client.py", line 18, in async_make_post
    async with self.session.post(
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1187, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 574, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 911, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1235, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1204, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1000, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.68.103:80 ssl:default [Connect call failed ('192.168.68.103', 80)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 119, in async_step_user
    device_data = await self._get_first_data_from_api(tapo_client)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/config_flow.py", line 199, in _get_first_data_from_api
    raise CannotConnect from error
custom_components.tapo.errors.CannotConnect

**Comment by whatamanoffical** [comment]
For me it solved after I rebooted the router again? 😳

**Comment by petretiandrea** [comment]
IP address changes can break the integration, you must create a DHCP reservation or try to enable IP Tracking feature of integration, but it's experimental and can fail

**Comment by whatamanoffical** [comment]
Yes, if you don't reserve IPs in DHCP and reboot router the device till not be found again. Even if you fill in the updated corrected new IP of the HUB in the Configuration Submenue it will fail to integrate. Tho, it works that you remove the device and re-integrate it from the scratch (tested now several times), but @petretiandrea maybe check on this with the IP adress update via configuration was router reboot -maybe this is a bug to chase- TY
