### ISSUE TITLE
Server response doesn't match our expected hash (L530, 2.13.0)

### ISSUE THREAD

**Issue by RohanM** [petretiandrea/home-assistant-tapo-p100#696]
On 2.13.0 I'm seeing something very similar to #658. When I upgrade from 2.11.0, two of my L530B lights show the error "Failed setup, will retry", with the hover text "not all arguments converted during string formatting". Other lights of the same model continue working just fine.

When I remove one of the non-functioning light devices and attempt to re-add it, I see this error in the debug log:

```
2024-02-04 11:04:25.383 ERROR (MainThread) [custom_components.tapo.config_flow] Failed to setup cannot connect 
Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 192, in _get_first_data_from_api
    (await tapo_client.get_device_info())
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_client.py", line 92, in get_device_info
    return await self.execute_raw_request(get_info_request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/api/tapo_client.py", line 78, in execute_raw_request
    return (await self._protocol.send_request(request)).map(lambda x: x.result)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/klap_protocol.py", line 49, in send_request
    response = await self._send_request(request, retry)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/klap_protocol.py", line 59, in _send_request
    new_session = await self.perform_handshake()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/klap_protocol.py", line 104, in perform_handshake
    seeds = await self.perform_handshake1(new_local_seed)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plugp100/protocol/klap_protocol.py", line 176, in perform_handshake1
    "Server response doesn't match our expected hash on ip %s but an authentication with blank credentials matched"
TypeError: not all arguments converted during string formatting

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 119, in async_step_user
    device_data = await self._get_first_data_from_api(tapo_client)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/config_flow.py", line 199, in _get_first_data_from_api
    raise CannotConnect from error
custom_components.tapo.errors.CannotConnect
```

Device info:
- Tapo L530
- Hardware version 2.0
- Firmware version 1.1.0 Build 230721 Rel.224802

Puzzlingly, the lights that continued working show exactly the same device info as above.

Software info:
- Tapo Controller 2.13.0
- HACS 1.34.0
- Home Assistant Core 2024.1.6
- Supervisor 2023.12.1
- Operating System 11.4
- Frontend 20240104.0

**Comment by patzobil** [comment]
Same exact issue here.... It actually acts up on all my tapo devices under the same firmware.
