### ISSUE TITLE
Auth failure on the plugin

### ISSUE THREAD

**Issue by ArMaTeC** [petretiandrea/home-assistant-tapo-p100#710]
## Version of the integration

2.14.0

## Configuration

Smart hub 2 1.5.6 Build 24202 Rel. 164142

## Describe the bug
Plugin showing its in an errored state and the sensor data is not showing this was working a week ago.
I've attempted to troubleshoot by removing the integration and then re-adding it. Initially, this action displays both the hub and the assigned sensor. However, upon subsequent checks, an error message appears, indicating a retry attempt. Unfortunately, this cycle perpetuates, leaving the system in a perpetually errored state. I've meticulously verified that my username and password match, and I've even reset my password to an alternative one, but the error persists.

## Debug log

2024-03-04 07:16:24.257 ERROR (MainThread) [custom_components.tapo_control] [initOnvifEvents] Initiating onvif connection failed.
2024-03-04 07:16:24.258 ERROR (MainThread) [custom_components.tapo_control] Authority failure
2024-03-04 07:16:27.688 ERROR (MainThread) [custom_components.tapo_control] [initOnvifEvents] Initiating onvif connection failed.
2024-03-04 07:16:27.688 ERROR (MainThread) [custom_components.tapo_control] Authority failure
2024-03-04 07:16:31.040 ERROR (MainThread) [custom_components.tapo_control] [initOnvifEvents] Initiating onvif connection failed.
2024-03-04 07:16:31.040 ERROR (MainThread) [custom_components.tapo_control] Authority failure
2024-03-04 07:16:34.652 ERROR (MainThread) [custom_components.tapo_control] [initOnvifEvents] Initiating onvif connection failed.
2024-03-04 07:16:34.652 ERROR (MainThread) [custom_components.tapo_control] Authority failure
2024-03-04 07:16:38.054 ERROR (MainThread) [custom_components.tapo_control] [initOnvifEvents] Initiating onvif connection failed.
2024-03-04 07:16:38.054 ERROR (MainThread) [custom_components.tapo_control] Authority failure
2024-03-04 07:16:41.577 ERROR (MainThread) [custom_components.tapo_control] [initOnvifEvents] Initiating onvif connection failed.
2024-03-04 07:16:41.577 ERROR (MainThread) [custom_components.tapo_control] Authority failure
2024-03-04 07:16:43.014 ERROR (MainThread) [custom_components.tapo.config_flow] Tapo exception -1501
2024-03-04 07:16:43.014 ERROR (MainThread) [custom_components.tapo.config_flow] Failed to setup, invalid auth 
Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 192, in _get_first_data_from_api
    (await tapo_client.get_device_info())
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/plugp100/api/tapo_client.py", line 92, in get_device_info
    return await self.execute_raw_request(get_info_request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/plugp100/api/tapo_client.py", line 77, in execute_raw_request
    await self._initialize_protocol_if_needed()
  File "/usr/local/lib/python3.12/site-packages/plugp100/api/tapo_client.py", line 71, in _initialize_protocol_if_needed
    await self._guess_protocol()
  File "/usr/local/lib/python3.12/site-packages/plugp100/api/tapo_client.py", line 232, in _guess_protocol
    raise error
plugp100.responses.tapo_exception.TapoException: Returned error_code: TapoError.INVALID_CREDENTIAL: Invalid credentials

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 119, in async_step_user
    device_data = await self._get_first_data_from_api(tapo_client)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/config_flow.py", line 197, in _get_first_data_from_api
    self._raise_from_tapo_exception(error)
  File "/config/custom_components/tapo/config_flow.py", line 224, in _raise_from_tapo_exception
    raise InvalidAuth from exception
custom_components.tapo.errors.InvalidAuth
2024-03-04 07:16:43.654 ERROR (MainThread) [custom_components.cloudflare_tunnel_monitor.sensor] Error fetching Cloudflare tunnels: 400, Bad Request
2024-03-04 07:16:43.654 ERROR (MainThread) [custom_components.cloudflare_tunnel_monitor.sensor] Error fetching data: Error fetching Cloudflare tunnels
2024-03-04 07:16:44.874 ERROR (MainThread) [custom_components.tapo_control] [initOnvifEvents] Initiating onvif connection failed.
2024-03-04 07:16:44.874 ERROR (MainThread) [custom_components.tapo_control] Authority failure
2024-03-04 07:16:48.466 ERROR (MainThread) [custom_components.tapo_control] [initOnvifEvents] Initiating onvif connection failed.
2024-03-04 07:16:48.467 ERROR (MainThread) [custom_components.tapo_control] Authority failure
2024-03-04 07:16:51.876 ERROR (MainThread) [custom_components.tapo_control] [initOnvifEvents] Initiating onvif connection failed.
2024-03-04 07:16:51.877 ERROR (MainThread) [custom_components.tapo_control] Authority failure
2024-03-04 07:16:55.103 ERROR (MainThread) [custom_components.tapo_control] [initOnvifEvents] Initiating onvif connection failed.
2024-03-04 07:16:55.103 ERROR (MainThread) [custom_components.tapo_control] Authority failure
2024-03-04 07:16:58.807 ERROR (MainThread) [custom_components.tapo_control] [initOnvifEvents] Initiating onvif connection failed.
2024-03-04 07:16:58.808 ERROR (MainThread) [custom_components.tapo_control] Authority failure
2024-03-04 07:17:02.139 ERROR (MainThread) [custom_components.tapo_control] [initOnvifEvents] Initiating onvif connection failed.
2024-03-04 07:17:02.139 ERROR (MainThread) [custom_components.tapo_control] Authority failure
2024-03-04 07:17:03.772 ERROR (MainThread) [custom_components.cloudflare_tunnel_monitor.sensor] Error fetching Cloudflare tunnels: 400, Bad Request
2024-03-04 07:17:03.772 ERROR (MainThread) [custom_components.cloudflare_tunnel_monitor.sensor] Error fetching data: Error fetching Cloudflare tunnels
2024-03-04 07:17:05.519 ERROR (MainThread) [custom_components.tapo_control] [initOnvifEvents] Initiating onvif connection failed.
2024-03-04 07:17:05.520 ERROR (MainThread) [custom_components.tapo_control] Authority failure
2024-03-04 07:17:09.147 ERROR (MainThread) [custom_components.tapo_control] [initOnvifEvents] Initiating onvif connection failed.
2024-03-04 07:17:09.147 ERROR (MainThread) [custom_components.tapo_control] Authority failure
2024-03-04 07:17:12.465 ERROR (MainThread) [custom_components.tapo_control] [initOnvifEvents] Initiating onvif connection failed.
2024-03-04 07:17:12.465 ERROR (MainThread) [custom_components.tapo_control] Authority failure
2024-03-04 07:17:15.901 ERROR (MainThread) [custom_components.tapo_control] [initOnvifEvents] Initiating onvif connection failed.
2024-03-04 07:17:15.901 ERROR (MainThread) [custom_components.tapo_control] Authority failure
2024-03-04 07:17:19.937 ERROR (MainThread) [custom_components.tapo_control] [initOnvifEvents] Initiating onvif connection failed.
2024-03-04 07:17:19.937 ERROR (MainThread) [custom_components.tapo_control] Authority failure
2024-03-04 07:17:22.719 ERROR (MainThread) [custom_components.tapo_control] [initOnvifEvents] Initiating onvif connection failed.
2024-03-04 07:17:22.719 ERROR (MainThread) [custom_components.tapo_control] Authority failure
2024-03-04 07:17:23.906 ERROR (MainThread) [custom_components.cloudflare_tunnel_monitor.sensor] Error fetching Cloudflare tunnels: 400, Bad Request
2024-03-04 07:17:23.906 ERROR (MainThread) [custom_components.cloudflare_tunnel_monitor.sensor] Error fetching data: Error fetching Cloudflare tunnels
2024-03-04 07:17:26.108 ERROR (MainThread) [custom_components.tapo_control] [initOnvifEvents] Initiating onvif connection failed.
2024-03-04 07:17:26.108 ERROR (MainThread) [custom_components.tapo_control] Authority failure
2024-03-04 07:17:30.316 ERROR (MainThread) [custom_components.tapo_control] [initOnvifEvents] Initiating onvif connection failed.
2024-03-04 07:17:30.316 ERROR (MainThread) [custom_components.tapo_control] Authority failure
2024-03-04 07:17:33.018 ERROR (MainThread) [custom_components.tapo_control] [initOnvifEvents] Initiating onvif connection failed.
2024-03-04 07:17:33.018 ERROR (MainThread) [custom_components.tapo_control] Authority failure
2024-03-04 07:17:36.411 ERROR (MainThread) [custom_components.tapo_control] [initOnvifEvents] Initiating onvif connection failed.
2024-03-04 07:17:36.412 ERROR (MainThread) [custom_components.tapo_control] Authority failure
2024-03-04 07:17:37.565 DEBUG (MainThread) [custom_components.tapo.setup_helpers] Re-using setup API to create a coordinator
2024-03-04 07:17:37.631 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.032 seconds (success: True)
2024-03-04 07:17:37.677 INFO (MainThread) [custom_components.tapo.hub.tapo_hub] Found 1 children associated to hub 802D0FAFF70E31EF23680C18D46F33292182D949
2024-03-04 07:17:40.669 ERROR (MainThread) [custom_components.tapo_control] [initOnvifEvents] Initiating onvif connection failed.
2024-03-04 07:17:40.669 ERROR (MainThread) [custom_components.tapo_control] Authority failure
2024-03-04 07:17:43.459 ERROR (MainThread) [custom_components.tapo_control] [initOnvifEvents] Initiating onvif connection failed.
2024-03-04 07:17:43.459 ERROR (MainThread) [custom_components.tapo_control] Authority failure
2024-03-04 07:17:44.004 ERROR (MainThread) [custom_components.cloudflare_tunnel_monitor.sensor] Error fetching Cloudflare tunnels: 400, Bad Request
2024-03-04 07:17:44.004 ERROR (MainThread) [custom_components.cloudflare_tunnel_monitor.sensor] Error fetching data: Error fetching Cloudflare tunnels
2024-03-04 07:17:46.664 ERROR (MainThread) [custom_components.tapo_control] [initOnvifEvents] Initiating onvif connection failed.
2024-03-04 07:17:46.664 ERROR (MainThread) [custom_components.tapo_control] Authority failure
2024-03-04 07:17:47.678 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 10.001 seconds (success: False)
2024-03-04 07:17:51.093 ERROR (MainThread) [custom_components.tapo_control] [initOnvifEvents] Initiating onvif connection failed.
2024-03-04 07:17:51.094 ERROR (MainThread) [custom_components.tapo_control] Authority failure
2024-03-04 07:17:53.042 DEBUG (MainThread) [custom_components.tapo.setup_helpers] Re-using setup API to create a coordinator
2024-03-04 07:17:53.104 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.032 seconds (success: True)
2024-03-04 07:17:53.152 INFO (MainThread) [custom_components.tapo.hub.tapo_hub] Found 1 children associated to hub 802D0FAFF70E31EF23680C18D46F33292182D949
2024-03-04 07:17:53.722 ERROR (MainThread) [custom_components.tapo_control] [initOnvifEvents] Initiating onvif connection failed.
2024-03-04 07:17:53.722 ERROR (MainThread) [custom_components.tapo_control] Authority failure
2024-03-04 07:17:56.919 ERROR (MainThread) [custom_components.tapo_control] [initOnvifEvents] Initiating onvif connection failed.
2024-03-04 07:17:56.919 ERROR (MainThread) [custom_components.tapo_control] Authority failure
2024-03-04 07:18:01.723 ERROR (MainThread) [custom_components.tapo_control] [initOnvifEvents] Initiating onvif connection failed.
2024-03-04 07:18:01.723 ERROR (MainThread) [custom_components.tapo_control] Authority failure
2024-03-04 07:18:03.154 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 10.001 seconds (success: False)
2024-03-04 07:18:04.093 ERROR (MainThread) [custom_components.cloudflare_tunnel_monitor.sensor] Error fetching Cloudflare tunnels: 400, Bad Request
2024-03-04 07:18:04.094 ERROR (MainThread) [custom_components.cloudflare_tunnel_monitor.sensor] Error fetching data: Error fetching Cloudflare tunnels
2024-03-04 07:18:04.150 ERROR (MainThread) [custom_components.tapo_control] [initOnvifEvents] Initiating onvif connection failed.
2024-03-04 07:18:04.151 ERROR (MainThread) [custom_components.tapo_control] Authority failure
2024-03-04 07:18:07.130 ERROR (MainThread) [custom_components.tapo_control] [initOnvifEvents] Initiating onvif connection failed.
2024-03-04 07:18:07.130 ERROR (MainThread) [custom_components.tapo_control] Authority failure

**Comment by ZeroDotNet** [comment]
I was dealing with a similar issue while trying to add a Tapo C200 camera. A comment with the source was left here: #122 

https://github.com/petretiandrea/home-assistant-tapo-p100/issues/122#issuecomment-2008628551

I deal with it by removing my device from the cloud service. (or by removing  the SD card if your device has one)

**Comment by tayanov** [comment]
+1
