### ISSUE TITLE
P115 & P300 - Failed to Connect to devices 

### ISSUE THREAD

**Issue by delize** [petretiandrea/home-assistant-tapo-p100#721]
Same issues, with a P115 and a P300 EU.

## Version of the integration

v3.0.0

## Configuration

```yaml
$ cat /mnt/docker/homeassistant/configuration.yaml                                                                                                                                                                                      [21:17:43]

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  internal_url: "http://192.168.50.2:8123"
  external_url: "https://homeassistant.domain.com"

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.16.0.0/12
    - 162.158.0.0/15
    - 192.168.0.0/16
  ip_ban_enabled: true
  login_attempts_threshold: 3



```

## Describe the bug

When attempting to connect, I get "Failed to connect", username/email is all lowercase. 
Unable to add Tapo devices. 
<img width="380" alt="Screenshot 2024-03-08 at 7 40 41 PM" src="https://github.com/petretiandrea/home-assistant-tapo-p100/assets/4028612/fed5d6e7-b12e-4fc6-b8f5-b9284ebaf68a">

P115
Device Firmware: 1.3.0 Build 230905 Rel. 152200
Hardware Version 1.0 

P300
Hardware Version 1.0
Firmware Version: 1.0.15 Build 231130 Rel 122554

## Debug log

```text


2024-03-08 19:36:33.881 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.120 seconds (success: True)
2024-03-08 19:36:35.023 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.119 seconds (success: True)
2024-03-08 19:37:17.783 ERROR (MainThread) [custom_components.tapo.config_flow] Failed to setup cannot connect 
Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 309, in _async_get_device_info
    .get_or_raise()
     ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/plugp100/common/functional/tri.py", line 159, in get_or_raise
    raise self.value
Exception: Server response doesn't match our challenge on ip ('http', '192.168.50.206', 80)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 231, in async_step_discovery_auth_confirm
    device_info = await self._async_get_device_info_from_discovered(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/config_flow.py", line 294, in _async_get_device_info_from_discovered
    return await self._async_get_device_info(config | {CONF_HOST: discovered.ip})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/config_flow.py", line 314, in _async_get_device_info
    raise CannotConnect from error
custom_components.tapo.errors.CannotConnect


```

The above is when clicking "Enable Logging", then attempting to login using the username and password combo.

**Comment by petretiandrea** [comment]
Fixed by [3.1.0](https://github.com/petretiandrea/home-assistant-tapo-p100/tree/3.1.0)
