### ISSUE TITLE
Tapo H100 hub wont connect after update 3.1.1

### ISSUE THREAD

**Issue by boule3** [petretiandrea/home-assistant-tapo-p100#745]
Hello, 
Since 3.1.1 update my tapo H100 is not working and impossible to reconnect to it
"authentication issue"

No problem when a reload a 3.0.0 backup, problem is only since 3.1.1

**Comment by petretiandrea** [comment]
I have a working H100 integration with 3.1.1. Have you tried to reload the config entry?
![aaaa](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/25798293/20c90d26-31e6-4f4c-970d-b4afb1463aeb)

**Comment by boule3** [comment]
Yes of course,, the result is the same "authentication issue"

**Comment by Halfthibs** [comment]
Hello, I did try that too and it says "authentication issue" too. I deleted it. And added it again and I have "failed to connect" when I entered email and password.

**Comment by sayam93** [comment]
Stopped working for me as well. Tried reloading a couple of times but nothing.

**Comment by sayam93** [comment]
Deleted and installed 3.0 and it works fine now. Guess am gonna skip 3.1.1 for now.

**Comment by mc-flash** [comment]
Same problem here. Came from working 3.0.0.
3.1.1 not working. Went back to 3.1.0 -> not working
Went back again to 3.0.0 -> everything is fine

**Comment by DanCyberSK** [comment]
Same issue. Version 3.0.0 work fine.

**Comment by Dee-san** [comment]
I can confirm this bug - my e-mail has no capital letters and also rolling back to 3.0.0 fixed the problem.
Will wait for a version that fixes this issue

**Comment by petretiandrea** [comment]
Sorry guys, there was an error on manifest.json, please try 3.1.2

**Comment by solidforce** [comment]
After update to 3.1.2 still Failed to connect:
Logger: custom_components.tapo.config_flow
Source: custom_components/tapo/config_flow.py:143
integration: TP-Link Tapo (documentation, issues)
First occurred: 22:40:58 (1 occurrences)
Last logged: 22:40:58

Failed to setup cannot connectTraceback (most recent call last): File "/config/custom_components/tapo/config_flow.py", line 317, in _async_get_device await device.update() File "/usr/local/lib/python3.12/site-packages/plugp100/new/tapodevice.py", line 79, in update await component.update(state) File "/usr/local/lib/python3.12/site-packages/plugp100/new/components/hub_children_component.py", line 47, in update await child_device.update() File "/usr/local/lib/python3.12/site-packages/plugp100/new/tapodevice.py", line 79, in update await component.update(state) File "/usr/local/lib/python3.12/site-packages/plugp100/new/components/smart_door_component.py", line 15, in update self.is_open = current_state["is_open"] ~~~~~~~~~~~~~^^^^^^^^^^^ KeyError: 'is_open' The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/config/custom_components/tapo/config_flow.py", line 143, in async_step_user device = await self._async_get_device(user_input) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/tapo/config_flow.py", line 322, in _async_get_device raise CannotConnect from error custom_components.tapo.errors.CannotConnect

**Comment by boule3** [comment]
> Sorry guys, there was an error on manifest.json, please try 3.1.2

Hello, sorry but it's still not working, even after reload
<img width="522" alt="Capture" src="https://github.com/petretiandrea/home-assistant-tapo-p100/assets/57114821/ad66a4b6-7794-4ef9-bc14-e69e730aafdd">

**Comment by seba1337** [comment]
Same here (3.1.2. and 3.1.1.).

**Comment by User-Frodolin** [comment]
I also get the same error. Only version 3.0.0 works.

**Comment by Halfthibs** [comment]
Same here. I upgraded in version 3.1.2 and I got the same error.

**Comment by ferdisahin** [comment]
Not working 3.1.1 & 3.1.2

**Comment by iambenmitchell** [comment]
Same here.

**Comment by boule3** [comment]
@petretiandrea 
Hi, Do you have any news about a correction ? for the moment i stay on 3.0.0 witch is the latest version with H100 working

**Comment by Ashleyde42** [comment]
I am on Tpao 3.2.902 and the problem still occurs.

**Comment by joshje** [comment]
Same issue here. Working fine on 3.0.0 but not working on any later versions.

**Comment by K3str3l** [comment]
Something "odd" happened for me this morning- I was having the same issues as others have mentioned here (on 3.1.2). Today I restarted HA as I was updating a Hikvision integration, andd all Tapo authentication errors are gone! And have remained gone for the past two hours.
All my devices are plugs....

**Comment by seba1337** [comment]
> Something "odd" happened for me this morning- I was having the same issues as others have mentioned here (on 3.1.2). Today I restarted HA as I was updating a Hikvision integration, andd all Tapo authentication errors are gone! And have remained gone for the past two hours. All my devices are plugs....

Plugs work for me. The only issue is with the hub, but it works now through Matter.

**Comment by boule3** [comment]
> Something "odd" happened for me this morning- I was having the same issues as others have mentioned here (on 3.1.2). Today I restarted HA as I was updating a Hikvision integration, andd all Tapo authentication errors are gone! And have remained gone for the past two hours. All my devices are plugs....

No problem on plugs, problem is only on H100 hub

**Comment by eprompc** [comment]
> > Algo "extraño" me sucedió esta mañana: estaba teniendo los mismos problemas que otros han mencionado aquí (en 3.1.2). Hoy reinicié HA mientras actualizaba una integración de Hikvision, ¡y todos los errores de autenticación de Tapo han desaparecido! Y han permanecido ausentes durante las últimas dos horas. Todos mis dispositivos son enchufes....
> 
> Los enchufes funcionan para mí. El único problema es con el hub, pero ahora funciona a través de Matter.

How do you did it?? Thanks

**Comment by boule3** [comment]
Still no news of correction, so i've followed other user and have uninstalled this extension and use MATTER instead, i've lost battery informations but it perfectly works

**Comment by eprompc** [comment]
> Still no news of correction, so i've followed other users and have uninstalled this extension and use MATTER instead, i've lost battery informations but it perfectly works

Yes, I also did the same as you and everything is working. It’s a shame that this repository is not updated.

**Comment by DanCyberSK** [comment]
Switching to Matter would be nice, but I use the siren from the H100 as a doorbell, which Matter cannot use. So I'm still waiting for a fix and until then I'm using version 3.0.0.

**Comment by DanCyberSK** [comment]
> > Switching to Matter would be nice, but I use the siren from the H100 as a doorbell, which Matter cannot use. So I'm still waiting for a fix and until then I'm using version 3.0.0.
> 
> I'm sorry for this question, but can anyone tell me or put a link to follow how can I rollback to version 3.0.0 ? I was able to swich to Matter but I need to use the siren from the H100 too. Cheers.

Delete the addon, then add it again from HACS, but first select version 3.0.0 in the installation window. Then ignore the prompts to update.

**Comment by Halfthibs** [comment]
> > > Switching to Matter would be nice, but I use the siren from the H100 as a doorbell, which Matter cannot use. So I'm still waiting for a fix and until then I'm using version 3.0.0.
> > 
> > 
> > I'm sorry for this question, but can anyone tell me or put a link to follow how can I rollback to version 3.0.0 ? I was able to swich to Matter but I need to use the siren from the H100 too. Cheers.
> 
> Delete the addon, then add it again from HACS, but first select version 3.0.0 in the installation window. Then ignore the prompts to update.

Ok I didn't thought it will be as simple as that. Thank's a lot.

**Comment by leah-potato** [comment]
> Delete the addon, then add it again from HACS, but first select version 3.0.0 in the installation window. Then ignore the prompts to update.

For anyone struggling to rollback to a specific version make sure you have adblocker turned off. When I selected redownload nothing happened. I incorrectly assumed that something was happenning in the background but the expected behaviour is that a window should pop up like this: 

<img width="587" alt="image" src="https://github.com/petretiandrea/home-assistant-tapo-p100/assets/128001814/cbb3b609-ad2f-4a0b-840b-4337e96b7607">

Turn off adblocker if you don't see it.

**Comment by ledow** [comment]
Whenever I update from v2.14.0 to anything, I lose my H100 and all connected devices completely.  Not just "haven't read the sensor yet" (which is common) but there are no H100-connected entities or devices anywhere to be found and all my cards break.

Just tried it again - same thing.  Had to restore from backup.

I've now got to the point where I'm staying at 2.14 until I see H100 is fixed in the Changelog.

**Comment by tallackn** [comment]
Same thing for me.  But I can't get the "matter workaround" working for me (matter has never worked for some reason).

Any idea when this will be fixed?

**Comment by ItsMeRitch** [comment]
Can confirm that I also encountered this issue. I tested with version 3.1.1 and 3.1.2 and it breaks connecting to a H100 Hub. 

Unfortunately, I didn't get a chance to capture the logs of the original error before I removed the hub but this is the error I received when trying to re-add it (unsuccessfully):

`Logger: custom_components.tapo.config_flow
Source: custom_components/tapo/config_flow.py:231
integration: TP-Link Tapo (documentation, issues)
First occurred: 10:14:36 PM (1 occurrences)
Last logged: 10:14:36 PM

Failed to setup cannot connect
Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 317, in _async_get_device
    _LOGGER.error("Tapo exception %s", str(exception.error_code))
        ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/plugp100/new/tapodevice.py", line 79, in update
    await component.update(state)
  File "/usr/local/lib/python3.12/site-packages/plugp100/new/components/hub_children_component.py", line 47, in update
    await child_device.update()
  File "/usr/local/lib/python3.12/site-packages/plugp100/new/tapodevice.py", line 79, in update
    await component.update(state)
  File "/usr/local/lib/python3.12/site-packages/plugp100/new/components/smart_door_component.py", line 15, in update
    self.is_open = current_state["is_open"]
                   ~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'is_open'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 231, in async_step_discovery_auth_confirm
    device_info = await self._async_get_device_info_from_discovered(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/config_flow.py", line 295, in _async_get_device_from_discovered
  File "/config/custom_components/tapo/config_flow.py", line 322, in _async_get_device
custom_components.tapo.errors.CannotConnect


`

If I recall correctly, I think the self.is_open was returning as type Null. 

If I'm correct, the error stems from [this](https://github.com/petretiandrea/home-assistant-tapo-p100/commit/e7b58ff79636deef7df1ddc81a5eb3b8f9d76b4b#diff-ba0511babf56d70cbf89a00b19ce5503585b579f2a14d3d24d6a64977455aae8R55) commit. If you look at line 55 (green), this is where my error comes from. I don't have the skills to be able to trace this further back but it could be stemming from a KLAP auth error which results in the query is_open returning Null. This was the only difference in the releases that could be causing the error from what I could find. Screenshot of the code in question attached:

<img width="660" alt="Screenshot 2024-06-07 at 23 09 18" src="https://github.com/petretiandrea/home-assistant-tapo-p100/assets/55960162/f418f4f8-1d8f-4c6c-9e94-b1b0de23306e">


I was going to try to add a try-catch in there to see if that resolved the issue but I've been working on this for hours now and can't see straight anymore. If you need a hand with anything @petretiandrea, just let me know. Thanks again for all your hard work with this.

**Comment by ItsMeRitch** [comment]
Not stale, not upgrading cause of this issue

**Comment by ItsMeRitch** [comment]
> Not stale, not upgrading cause of this issue 

Not stale as above. Not upgrading because of this issue

**Comment by iambenmitchell** [comment]
+1

**Comment by sibowden** [comment]
FTR there's a proposed fix in #759 (but no activity on reviewing it). Unfortunately manually applying it is difficult if you have HAOS managed OS.

**Comment by sibowden** [comment]
I've just noticed that the official "TP-Link Smart Home" integration has fairly recently got support for the H100 hub and a number of attached sensors (for me, attached light switches, temperature sensors, water alarm and door/contact sensor are all working).

Consequently this custom integration is perhaps obsolete for some, and you can fix the H100 issue by configuring it in the core tp-link integration. The only caveat is that entity IDs change, so you need to remove the old devices and connect automations to the new entity.

**Comment by iambenmitchell** [comment]
Good News! Home Assistant and Kasa now support matter (beta). Successfully added mine to HA.

For the iOS kasa app:
Open App > Click your smart hub (mine is a KH100) > Setting icon in top right > Bind to matter
 <img width="1552" alt="image" src="https://github.com/user-attachments/assets/1dde959c-3f65-403a-8d98-56250dc898e5">
 
<img width="1552" alt="image" src="https://github.com/user-attachments/assets/b81b0d2b-0fa5-4369-9df7-97efd8c2fa3b">

**Comment by MakaanPL** [comment]
Yes, I wrote about it here: https://github.com/petretiandrea/home-assistant-tapo-p100/discussions/799
But for me, Matter integration is broken due to incorrect reporting of heating status.

**Comment by iambenmitchell** [comment]
> Yes, I wrote about it here: #799 But for me, Matter integration is broken due to incorrect reporting of heating status.

Strange, anecdotally it works fine for me. Two ways too, I can control the TRVs from HA and it updates in Kasa and Apple Home, and if I control them from Kasa or Apple Home it updates in HA. Allowing my automation to turn the boiler on to work

**Comment by MakaanPL** [comment]
Depends on how the automation is configured. I prefer to keep valves "on" (idle) all the time and then change only the temperature, so heating status is important. Andrea's integration shows "idle" as "off" (which is fine), while the TP-Link one (from HA repo) implemented idle status too. Matter is broken as it shows "heating" regardless if TRV is actually open or idle.

**Comment by iambenmitchell** [comment]
> Matter is broken as it shows "on(heating)" regardless if TRV is actually open or idle.

Not sure why you do it the way you do, but doing it the correct way works fine. 

In automations I monitor the states of all the TRVs and if any of them change then it triggers the automation, which checks if any of the TRVs are set to heat and if so, turns the google nest on, else turns it off. Pretty simple. 

On the google nest I have it set to the max temp of 32ºc which means that regardless of if the fire is lit in the lounge, where the nest is, it will turn the boiler on if the rest of the house requests heat.

We had the Nest before we bought the TRVs, if I were to do it again, I'd just use a simple relay and not bother with the nest, but since we have it, no point replacing it. 

![image](https://github.com/user-attachments/assets/b4089284-34e5-48e9-a69f-424edcc15c65)

**Comment by Arkasha-P** [comment]
Обновил интеграцию на последнюю версию в ручную через ssh. 
Просто через git clone скачайте папку tapo в каталог /homeassistant/custom_components
