### ISSUE TITLE
HA doesn't see the device H100

### ISSUE THREAD

**Issue by tuliuliucroman** [petretiandrea/home-assistant-tapo-p100#752]
After updating Tapo Controller does not see devices
![таро](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/132389383/85b641b6-40b7-45f9-8a10-6ce1d14adc4c)
![таро1](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/132389383/a24657cf-45b8-4302-a184-3a825b7e7f06)
![image](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/132389383/49b019bd-558e-4e77-8e89-c83b1e489ac7)

**Comment by tuliuliucroman** [comment]
![image](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/132389383/ca4e9137-2cb2-45af-b3f4-37ec84274771)

**Comment by tuliuliucroman** [comment]
2024-04-17 08:02:13.549 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tapo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-04-17 08:02:13.550 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration yandex_smart_home which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-04-17 08:02:13.551 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-04-17 08:02:13.552 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration smart_irrigation which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-04-17 08:02:13.553 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tplink_router which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-04-17 08:02:13.554 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-04-17 08:02:13.555 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration vimar which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-04-17 08:02:13.556 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration huawei_mesh_router which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-04-17 08:02:13.557 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration yandex_station which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-04-17 08:02:13.558 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration smartir which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-04-17 08:02:13.558 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration alarmo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-04-17 08:02:13.559 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_cloud_map_extractor which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-04-17 08:02:13.561 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tapo_control which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-04-17 08:02:13.562 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration asterisk which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-04-17 08:02:13.563 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration dreame_vacuum which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-04-17 08:02:13.564 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration yandex_dialogs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-04-17 08:02:15.108 WARNING (ImportExecutor_0) [homeassistant.components.camera] SUPPORT_ON_OFF was used from xiaomi_cloud_map_extractor, this is a deprecated constant which will be removed in HA Core 2025.1. Use CameraEntityFeature.ON_OFF instead, please report it to the author of the 'xiaomi_cloud_map_extractor' custom integration
2024-04-17 08:02:15.110 WARNING (ImportExecutor_0) [homeassistant.components.camera] SUPPORT_ON_OFF was used from xiaomi_cloud_map_extractor, this is a deprecated constant which will be removed in HA Core 2025.1. Use CameraEntityFeature.ON_OFF instead, please report it to the author of the 'xiaomi_cloud_map_extractor' custom integration
2024-04-17 08:02:15.132 WARNING (MainThread) [homeassistant.helpers.entity] Entity camera.xiaomi_cloud_map_extractor (<class 'custom_components.xiaomi_cloud_map_extractor.camera.VacuumCamera'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <CameraEntityFeature.ON_OFF: 1>, please create a bug report at https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
2024-04-17 08:02:15.197 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] HVAC_MODE_OFF was used from smartir, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.OFF instead, please report it to the author of the 'smartir' custom integration
2024-04-17 08:02:15.199 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] HVAC_MODE_HEAT was used from smartir, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.HEAT instead, please report it to the author of the 'smartir' custom integration
2024-04-17 08:02:15.201 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] HVAC_MODE_COOL was used from smartir, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.COOL instead, please report it to the author of the 'smartir' custom integration
2024-04-17 08:02:15.204 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] HVAC_MODE_DRY was used from smartir, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.DRY instead, please report it to the author of the 'smartir' custom integration
2024-04-17 08:02:15.206 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] HVAC_MODE_FAN_ONLY was used from smartir, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.FAN_ONLY instead, please report it to the author of the 'smartir' custom integration
2024-04-17 08:02:15.208 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] HVAC_MODE_AUTO was used from smartir, this is a deprecated constant which will be removed in HA Core 2025.1. Use HVACMode.AUTO instead, please report it to the author of the 'smartir' custom integration
2024-04-17 08:02:15.210 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] SUPPORT_TARGET_TEMPERATURE was used from smartir, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.TARGET_TEMPERATURE instead, please report it to the author of the 'smartir' custom integration
2024-04-17 08:02:15.212 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] SUPPORT_FAN_MODE was used from smartir, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.FAN_MODE instead, please report it to the author of the 'smartir' custom integration
2024-04-17 08:02:15.214 WARNING (ImportExecutor_0) [homeassistant.components.climate.const] SUPPORT_SWING_MODE was used from smartir, this is a deprecated constant which will be removed in HA Core 2025.1. Use ClimateEntityFeature.SWING_MODE instead, please report it to the author of the 'smartir' custom integration
2024-04-17 08:02:17.929 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues
2024-04-17 08:02:18.064 WARNING (MainThread) [homeassistant.helpers.entity] Entity None (<class 'custom_components.smartir.climate.SmartIRClimate'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <ClimateEntityFeature.TARGET_TEMPERATURE|FAN_MODE: 9>, please report it to the author of the 'smartir' custom integration and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
2024-04-17 08:02:18.064 WARNING (MainThread) [homeassistant.components.climate] Entity None (<class 'custom_components.smartir.climate.SmartIRClimate'>) does not set ClimateEntityFeature.TURN_OFF but implements the turn_off method. Please report it to the author of the 'smartir' custom integration
2024-04-17 08:02:18.064 WARNING (MainThread) [homeassistant.components.climate] Entity None (<class 'custom_components.smartir.climate.SmartIRClimate'>) does not set ClimateEntityFeature.TURN_ON but implements the turn_on method. Please report it to the author of the 'smartir' custom integration
2024-04-17 08:02:18.064 WARNING (MainThread) [homeassistant.components.climate] Entity None (<class 'custom_components.smartir.climate.SmartIRClimate'>) implements HVACMode(s): off, cool, dry and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please report it to the author of the 'smartir' custom integration
2024-04-17 08:02:25.133 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.xiaomi_cloud_map_extractor is taking over 10 seconds
2024-04-17 08:03:02.664 ERROR (MainThread) [frontend.js.latest.202404042] Uncaught error from Chrome 123.0.0.0 on Windows 10
TypeError: Cannot read properties of null (reading 'removeEventListener')
renderHeading (src/components/ha-dialog.ts:53:24)
apply (src/scoped-custom-element-registry.js:262:44)
mainWindow.history.pushState (src/dialogs/make-dialog-manager.ts:129:7)
2024-04-17 08:04:45.160 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2024-04-17 08:18:50.314 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2024-04-17 08:18:55.314 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.xiaomi_cloud_map_extractor is taking over 10 seconds
2024-04-17 08:18:55.314 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2024-04-17 08:18:55.432 WARNING (SyncWorker_15) [custom_components.xiaomi_cloud_map_extractor.camera] Unable to retrieve map data
2024-04-17 08:19:05.316 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2024-04-17 08:33:10.463 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2024-04-17 08:33:15.463 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.xiaomi_cloud_map_extractor is taking over 10 seconds
2024-04-17 08:33:15.464 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2024-04-17 08:33:15.909 WARNING (SyncWorker_0) [custom_components.xiaomi_cloud_map_extractor.camera] Unable to retrieve map data
2024-04-17 08:33:25.466 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2024-04-17 08:45:15.599 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2024-04-17 08:45:20.599 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.xiaomi_cloud_map_extractor is taking over 10 seconds
2024-04-17 08:45:20.600 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2024-04-17 08:45:21.008 WARNING (SyncWorker_13) [custom_components.xiaomi_cloud_map_extractor.camera] Unable to retrieve map data
2024-04-17 08:45:30.601 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2024-04-17 09:00:45.783 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2024-04-17 09:00:50.783 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.xiaomi_cloud_map_extractor is taking over 10 seconds
2024-04-17 09:00:50.784 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2024-04-17 09:00:51.236 WARNING (SyncWorker_7) [custom_components.xiaomi_cloud_map_extractor.camera] Unable to retrieve map data
2024-04-17 09:01:00.786 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2024-04-17 09:10:55.900 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2024-04-17 09:11:00.899 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.xiaomi_cloud_map_extractor is taking over 10 seconds
2024-04-17 09:11:00.901 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2024-04-17 09:11:01.372 WARNING (SyncWorker_15) [custom_components.xiaomi_cloud_map_extractor.camera] Unable to retrieve map data
2024-04-17 09:11:10.903 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2024-04-17 09:21:51.041 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2024-04-17 09:21:56.041 WARNING (MainThread) [homeassistant.helpers.entity] Update of camera.xiaomi_cloud_map_extractor is taking over 10 seconds
2024-04-17 09:21:56.042 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2024-04-17 09:21:56.156 WARNING (SyncWorker_10) [custom_components.xiaomi_cloud_map_extractor.camera] Unable to retrieve map data
2024-04-17 10:09:06.561 WARNING (MainThread) [homeassistant.components.camera] Updating xiaomi_cloud_map_extractor camera took longer than the scheduled update interval 0:00:05
2024-04-17 10:19:53.504 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1155, in async_init
    flow, result = await self._async_init(flow_id, handler, context, data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1185, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 517, in _async_handle_step
    if result.get("preview") is not None:
       ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by tuliuliucroman** [comment]
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.4.3",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.12.2",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Chisinau",
    "os_name": "Linux",
    "os_version": "6.6.25-haos",
    "supervisor": "2024.04.0",
    "host_os": "Home Assistant OS 12.2",
    "docker_version": "25.0.5",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "tapo": {
      "version": "3.1.2",
      "requirements": [
        "plugp100==5.1.3"
      ]
    },
    "yandex_smart_home": {
      "version": "0.6.11",
      "requirements": []
    },
    "hacs": {
      "version": "1.34.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "smart_irrigation": {
      "version": "v2024.4.3",
      "requirements": []
    },
    "tplink_router": {
      "version": "1.13.1",
      "requirements": [
        "tplinkrouterc6u==4.0.0"
      ]
    },
    "nodered": {
      "version": "3.1.5",
      "requirements": []
    },
    "vimar": {
      "version": "2023.8.0",
      "requirements": []
    },
    "huawei_mesh_router": {
      "version": "0.9.2.1",
      "requirements": [
        "pycryptodome>=3.12.0"
      ]
    },
    "yandex_station": {
      "version": "3.15.1",
      "requirements": []
    },
    "smartir": {
      "version": "1.17.9",
      "requirements": [
        "aiofiles>=0.6.0"
      ]
    },
    "alarmo": {
      "version": "v1.10.0",
      "requirements": []
    },
    "xiaomi_cloud_map_extractor": {
      "version": "v2.2.0",
      "requirements": [
        "pillow",
        "pybase64",
        "python-miio",
        "requests",
        "pycryptodome"
      ]
    },
    "tapo_control": {
      "version": "5.4.13",
      "requirements": [
        "pytapo==3.3.19"
      ]
    },
    "asterisk": {
      "version": "1.0.3",
      "requirements": [
        "asterisk-ami==0.1.6"
      ]
    },
    "yandex_dialogs": {
      "version": "1.3.0",
      "requirements": []
    }
  },
  "integration_manifest": {
    "domain": "tapo",
    "name": "TP-Link Tapo",
    "config_flow": true,
    "version": "3.1.2",
    "iot_class": "local_polling",
    "documentation": "https://github.com/petretiandrea/home-assistant-tapo-p100",
    "issue_tracker": "https://github.com/petretiandrea/home-assistant-tapo-p100/issues",
    "requirements": [
      "plugp100==5.1.3"
    ],
    "dependencies": [
      "network"
    ],
    "dhcp": [
      {
        "registered_devices": true
      }
    ],
    "integration_type": "device",
    "codeowners": [
      "@petretiandrea"
    ],
    "is_built_in": false
  },
  "data": {
    "oui": "AC:15:A2",
    "protocol_name": "Passthrough",
    "raw_state": {
      "device_id": "8036564EBDDCF83DAA4473F107FE7C72208EB19F",
      "fw_ver": "1.5.6 Build 240202 Rel.164142",
      "hw_ver": "1.0",
      "type": "SMART.KASAHUB",
      "model": "KH100",
      "mac": "AC-15-A2-A3-D5-D6",
      "hw_id": "6D22656231DB621EDE3EA15AC83203AF",
      "fw_id": "00000000000000000000000000000000",
      "oem_id": "22ADFFE942A2C56C2ABC89549534BA85",
      "overheated": false,
      "ip": "192.168.0.142",
      "time_diff": 120,
      "ssid": "VmljdG9yaWE=",
      "rssi": -48,
      "signal_level": 3,
      "in_alarm": false,
      "in_alarm_source": "",
      "longitude": 288829,
      "latitude": 470402,
      "lang": "ru_RU",
      "avatar": "kasa_hub",
      "region": "Europe/Chisinau",
      "specs": "EU",
      "nickname": "0KPQvNC90YvQuSDRhtC10L3RgtGAIEthc2E=",
      "has_set_location_info": true
    },
    "components": {
      "__type": "<class 'plugp100.responses.components.Components'>",
      "repr": "Components(component_list={'device': 2, 'firmware': 2, 'quick_setup': 3, 'inherit': 1, 'time': 1, 'wireless': 1, 'account': 1, 'synchronize': 1, 'sunrise_sunset': 1, 'led': 1, 'cloud_connect': 1, 'iot_cloud': 1, 'child_device': 1, 'child_quick_setup': 1, 'child_inherit': 1, 'control_child': 1, 'alarm': 1, 'device_load': 1, 'device_local_time': 1, 'alarm_logs': 1, 'localSmart': 1})"
    },
    "children": []
  }
}

**Comment by Arkasha-P** [comment]
Обновил интеграцию на последнюю версию в ручную через ssh. 
Просто через git clone скачайте папку tapo в каталог /homeassistant/custom_components
