### ISSUE TITLE
No "hue" attribute for L530 bulb

### ISSUE THREAD

**Issue by JayUK** [petretiandrea/home-assistant-tapo-p100#757]
**Issue**
I'm currently experiencing an issue with an L530 bulb. When I turn it on or off I get an error in the HA log file about no "hue" attribute.

**Software Version**
I am running the following versions:
Bulb Firmware: 1.3.0
TP Link Tapo Integration: 3.1.2
HA Core: 2024.4.3
HA Supervisor: 2024.04.0
HA Operating System: 12.2

**Error Log**
2024-04-19 10:16:26.072 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 414, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
    update_callback()
  File "/config/custom_components/tapo/entity.py", line 45, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 998, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1119, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1058, in __async_calculate_state
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 1191, in state_attributes
    color_mode = self._light_internal_color_mode if _is_on else None
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 911, in _light_internal_color_mode
    if (color_mode := self.color_mode) is None:
                      ^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/light.py", line 63, in color_mode
    if ColorMode.HS in self.supported_color_modes and self.hs_color is not None:
                                                      ^^^^^^^^^^^^^
  File "/config/custom_components/tapo/light.py", line 84, in hs_color
    (hue, saturation) = (self.device.hs.hue, self.device.hs.saturation)
                         ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'hue'

**Comment by Petros15** [comment]
Same here. It's a v1 bulb and it suddenly became irresponsive. Updating to the latest integration version did not solve the problem.

**Comment by norbee37** [comment]
Here too. Both errors show up and at some point the device gets unavailable. Though strangely at least in the beginning it actually toggles it couple of times then stops working.

**Comment by Kisinu** [comment]
Same here. I guess it all started after last tapo integration update.

service light/turn_on. 'NoneType' object has no attribute 'hue'

**Comment by serin113** [comment]
This is probably a duplicate of #746: it has the same `NoneType`'d `self.device.hs` object error, and affects the same firmware (1.3.0) and hardware (L530 v1.0).

There's PR #748 which seems to fix the `NoneType` error, but doesn't fix the erratic behavior of the bulb: the "rate limit exceeded" error, and the color resetting to white when adjusting the brightness.
