### ISSUE TITLE
P300 Powerstrip only operates once and locks up after firmware upgrade

### ISSUE THREAD

**Issue by chrisp250** [petretiandrea/home-assistant-tapo-p100#765]
## Version of the integration
Latest: 3.1.2

## Configuration
P300 Powerstrip, upgraded to firmware 1.0.15

```yaml
{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2024.4.4",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.12.2",
    "docker": true,
    "arch": "aarch64",
    "timezone": "Australia/Sydney",
    "os_name": "Linux",
    "os_version": "6.6.25-haos",
    "supervisor": "2024.04.0",
    "host_os": "Home Assistant OS 12.2",
    "docker_version": "25.0.5",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "version": "1.34.0",
      "requirements": [
        "aiogithubapi>=22.10.1"
      ]
    },
    "growatt_server_api": {
      "version": "1.0.2",
      "requirements": [
        "growattServer==1.3.0"
      ]
    },
    "grott": {
      "version": "1.1.0",
      "requirements": []
    },
    "opennem": {
      "version": "2022.09.1",
      "requirements": []
    },
    "tapo": {
      "version": "3.1.2",
      "requirements": [
        "plugp100==5.1.3"
      ]
    },
    "frigate": {
      "version": "5.1.0",
      "requirements": [
        "pytz"
      ]
    },
    "philips_airpurifier_coap": {
      "version": "0.18.5",
      "requirements": [
        "aioairctrl==0.2.5",
        "getmac==0.9.4"
      ]
    }
  },
  "integration_manifest": {
    "domain": "tapo",
    "name": "TP-Link Tapo",
    "config_flow": true,
    "version": "3.1.2",
    "iot_class": "local_polling",
    "documentation": "https://github.com/petretiandrea/home-assistant-tapo-p100",
    "issue_tracker": "https://github.com/petretiandrea/home-assistant-tapo-p100/issues",
    "requirements": [
      "plugp100==5.1.3"
    ],
    "dependencies": [
      "network"
    ],
    "dhcp": [
      {
        "registered_devices": true
      }
    ],
    "integration_type": "device",
    "codeowners": [
      "@petretiandrea"
    ],
    "is_built_in": false
  },
  "data": {
    "oui": "A8:42:A1",
    "protocol_name": "Klap V2",
    "raw_state": {
      "device_id": "80223F247A03874725A1CFBD35991F3E21F8A272",
      "fw_ver": "1.0.15 Build 231130 Rel.122554",
      "hw_ver": "1.0",
      "type": "SMART.TAPOPLUG",
      "model": "P300",
      "mac": "A8-42-A1-2D-52-AF",
      "hw_id": "7A5F10591BB5524AF6539D890086FBEB",
      "fw_id": "00000000000000000000000000000000",
      "oem_id": "43C596CAD9CDFBE31D4785D4A4A7C760",
      "ip": "192.168.10.220",
      "time_diff": 600,
      "ssid": "RmFudGFzdGljRm91cg==",
      "rssi": -26,
      "signal_level": 3,
      "longitude": -1879048193,
      "latitude": -1879048193,
      "lang": "en_US",
      "avatar": "",
      "region": "Australia/Sydney",
      "specs": "",
      "nickname": "",
      "has_set_location_info": false
    },
    "components": {
      "__type": "<class 'plugp100.responses.components.Components'>",
      "repr": "Components(component_list={'device': 2, 'firmware': 2, 'quick_setup': 3, 'time': 1, 'wireless': 1, 'schedule': 2, 'countdown': 2, 'antitheft': 1, 'account': 1, 'synchronize': 1, 'sunrise_sunset': 1, 'led': 1, 'cloud_connect': 1, 'iot_cloud': 1, 'device_local_time': 1, 'default_states': 1, 'control_child': 2, 'child_device': 2, 'auto_off': 2, 'homekit': 2, 'overheat_protection': 1})"
    },
    "children": []
  }
}
```

## Describe the bug

The power strip has three outputs. After triggering an output (turning it on or off) it operates once and no longer responds. Restarting the integration will reset the issue and it will respond once, before locking up again.
The log doesn't seem to show what the issue is. I tried the TP-Kasa app and it works fine.

## Debug log

```text

2024-04-26 12:00:03.073 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-04-26 12:00:03.076 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration growatt_server_api which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-04-26 12:00:03.079 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration grott which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-04-26 12:00:03.084 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration opennem which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-04-26 12:00:03.087 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration tapo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-04-26 12:00:03.090 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration frigate which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-04-26 12:00:03.093 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration philips_airpurifier_coap which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-04-26 12:00:09.276 DEBUG (MainThread) [custom_components.tapo] Migrating from version 8
2024-04-26 12:00:11.011 INFO (MainThread) [Jellyfin] ---[ START JELLYFINCLIENT ]---
2024-04-26 12:00:13.106 INFO (MainThread) [custom_components.tapo.hass_tapo] Detected model of x.x.x.x: P300
2024-04-26 12:00:13.288 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.182 seconds (success: True)
2024-04-26 12:00:14.318 ERROR (MainThread) [homeassistant.components.daikin] Unexpected error creating device x.x.x.x
2024-04-26 12:00:16.263 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues
2024-04-26 12:00:21.115 ERROR (MainThread) [homeassistant.components.device_tracker] Platform asuswrt does not generate unique IDs. ID d0:73:d5:6b:f1:b1 already exists - ignoring device_tracker.lifi_labs_management_pty_ltd_5
2024-04-26 12:00:21.116 ERROR (MainThread) [homeassistant.components.device_tracker] Platform asuswrt does not generate unique IDs. ID d0:73:d5:3b:38:08 already exists - ignoring device_tracker.lifi_labs_management_pty_ltd_3
2024-04-26 12:00:21.116 ERROR (MainThread) [homeassistant.components.device_tracker] Platform asuswrt does not generate unique IDs. ID 78:11:dc:b8:c4:1b already exists - ignoring device_tracker.xiaomi_electronics_co_ltd
2024-04-26 12:00:21.116 ERROR (MainThread) [homeassistant.components.device_tracker] Platform asuswrt does not generate unique IDs. ID d0:ba:e4:ee:01:c9 already exists - ignoring device_tracker.shanghai_mxchip_information_tec
2024-04-26 12:00:21.116 ERROR (MainThread) [homeassistant.components.device_tracker] Platform asuswrt does not generate unique IDs. ID 18:fe:34:da:ba:8d already exists - ignoring device_tracker.espressif_inc_5
2024-04-26 12:00:21.116 ERROR (MainThread) [homeassistant.components.device_tracker] Platform asuswrt does not generate unique IDs. ID d0:73:d5:42:ad:f2 already exists - ignoring device_tracker.lifi_labs_management_pty_ltd
2024-04-26 12:00:21.117 ERROR (MainThread) [homeassistant.components.device_tracker] Platform asuswrt does not generate unique IDs. ID d0:73:d5:3e:ce:f4 already exists - ignoring device_tracker.lifi_labs_management_pty_ltd_4
2024-04-26 12:00:21.117 ERROR (MainThread) [homeassistant.components.device_tracker] Platform asuswrt does not generate unique IDs. ID a8:42:a1:2d:52:af already exists - ignoring device_tracker.tp_link_corporation_limited
2024-04-26 12:00:21.117 ERROR (MainThread) [homeassistant.components.device_tracker] Platform asuswrt does not generate unique IDs. ID f0:b4:29:b6:6d:d8 already exists - ignoring device_tracker.xiaomi_communications_co_ltd_3
2024-04-26 12:00:21.117 ERROR (MainThread) [homeassistant.components.device_tracker] Platform asuswrt does not generate unique IDs. ID f0:b4:29:0c:2c:60 already exists - ignoring device_tracker.guitars_spotlight
2024-04-26 12:00:21.117 ERROR (MainThread) [homeassistant.components.device_tracker] Platform asuswrt does not generate unique IDs. ID 78:11:dc:b7:8a:29 already exists - ignoring device_tracker.xiaomi_electronics_co_ltd_2
2024-04-26 12:00:21.118 ERROR (MainThread) [homeassistant.components.device_tracker] Platform asuswrt does not generate unique IDs. ID d0:73:d5:6b:f7:21 already exists - ignoring device_tracker.lifi_labs_management_pty_ltd_6
2024-04-26 12:00:21.118 ERROR (MainThread) [homeassistant.components.device_tracker] Platform asuswrt does not generate unique IDs. ID d0:73:d5:3b:59:19 already exists - ignoring device_tracker.lifi_labs_management_pty_ltd_7
2024-04-26 12:00:21.118 ERROR (MainThread) [homeassistant.components.device_tracker] Platform asuswrt does not generate unique IDs. ID a8:48:fa:dc:bb:1b already exists - ignoring device_tracker.garage_control
2024-04-26 12:00:21.118 ERROR (MainThread) [homeassistant.components.device_tracker] Platform asuswrt does not generate unique IDs. ID d8:bf:c0:da:9d:f4 already exists - ignoring device_tracker.espressif_inc_3
2024-04-26 12:00:21.118 ERROR (MainThread) [homeassistant.components.device_tracker] Platform asuswrt does not generate unique IDs. ID 48:3f:da:41:94:65 already exists - ignoring device_tracker.espressif_inc_4
2024-04-26 12:00:22.117 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 1.495 seconds (success: True)
2024-04-26 12:00:22.183 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 1.552 seconds (success: True)
2024-04-26 12:00:34.901 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({{ float(states.sensor.load_power_lumi_158d000283569f.state) / 1000.0 }}) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2208, in forgiving_float
    return float(value)
           ^^^^^^^^^^^^
ValueError: could not convert string to float: 'unavailable'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 586, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2545, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.12/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2211, in forgiving_float
    raise_no_default("float", value)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1849, in raise_no_default
    raise ValueError(
ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ float(states.sensor.load_power_lumi_158d000283569f.state) / 1000.0 }}' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 712, in async_render_to_info
    render_info._result = self.async_render(
                          ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 588, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ float(states.sensor.load_power_lumi_158d000283569f.state) / 1000.0 }}' but no default was specified
2024-04-26 12:00:34.912 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ float(states.sensor.load_power_lumi_158d000283569f.state) / 1000.0 }}' but no default was specified') while processing template 'Template<template=({{ float(states.sensor.load_power_lumi_158d000283569f.state) / 1000.0 }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.studio_energy'
2024-04-26 12:00:34.914 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'None' has no attribute 'attributes' when rendering '{{ states.switch.plug_158d000286453a.attributes.load_power }}'
2024-04-26 12:00:34.915 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({{ states.switch.plug_158d000286453a.attributes.load_power }}) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 586, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2545, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.12/site-packages/jinja2/sandbox.py", line 326, in getattr
    value = getattr(obj, attribute)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2580, in _fail_with_undefined_error
    raise ex
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2577, in _fail_with_undefined_error
    return super()._fail_with_undefined_error(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'None' has no attribute 'attributes'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 712, in async_render_to_info
    render_info._result = self.async_render(
                          ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 588, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: UndefinedError: 'None' has no attribute 'attributes'
2024-04-26 12:00:34.920 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'None' has no attribute 'attributes' when rendering '{{ states.switch.plug_158d000286453a.attributes.load_power }}'
2024-04-26 12:00:34.921 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('UndefinedError: 'None' has no attribute 'attributes'') while processing template 'Template<template=({{ states.switch.plug_158d000286453a.attributes.load_power }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.esx_server_power'
2024-04-26 12:00:34.922 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({{ float(states.sensor.housemeter_current_a.state) * 240.0 }}) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2208, in forgiving_float
    return float(value)
           ^^^^^^^^^^^^
ValueError: could not convert string to float: 'unavailable'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 586, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2545, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.12/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2211, in forgiving_float
    raise_no_default("float", value)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1849, in raise_no_default
    raise ValueError(
ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ float(states.sensor.housemeter_current_a.state) * 240.0 }}' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 712, in async_render_to_info
    render_info._result = self.async_render(
                          ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 588, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ float(states.sensor.housemeter_current_a.state) * 240.0 }}' but no default was specified
2024-04-26 12:00:34.934 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ float(states.sensor.housemeter_current_a.state) * 240.0 }}' but no default was specified') while processing template 'Template<template=({{ float(states.sensor.housemeter_current_a.state) * 240.0 }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.studio_power_m'
2024-04-26 12:00:34.939 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({{ float(states.sensor.housemeter_current_c.state) * 240.0 }}) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2208, in forgiving_float
    return float(value)
           ^^^^^^^^^^^^
ValueError: could not convert string to float: 'unavailable'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 586, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2545, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.12/site-packages/jinja2/sandbox.py", line 393, in call
    return __context.call(__obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2211, in forgiving_float
    raise_no_default("float", value)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1849, in raise_no_default
    raise ValueError(
ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ float(states.sensor.housemeter_current_c.state) * 240.0 }}' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 712, in async_render_to_info
    render_info._result = self.async_render(
                          ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 588, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ float(states.sensor.housemeter_current_c.state) * 240.0 }}' but no default was specified
2024-04-26 12:00:34.949 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('ValueError: Template error: float got invalid input 'unavailable' when rendering template '{{ float(states.sensor.housemeter_current_c.state) * 240.0 }}' but no default was specified') while processing template 'Template<template=({{ float(states.sensor.housemeter_current_c.state) * 240.0 }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.aircon_power_m'
2024-04-26 12:00:40.537 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.downer_precipitation (mm/h) cannot be converted to the unit of previously compiled statistics (mm). Generation of long term statistics will be suppressed unless the unit changes back to mm or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2024-04-26 12:00:41.086 WARNING (Recorder) [homeassistant.components.sensor.recorder] The unit of sensor.living_room_indoor_allergen_index (None) cannot be converted to the unit of previously compiled statistics (IAI). Generation of long term statistics will be suppressed unless the unit changes back to IAI or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
2024-04-26 12:00:52.245 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.142 seconds (success: True)
2024-04-26 12:01:09.031 WARNING (MainThread) [custom_components.philips_airpurifier_coap.config_flow] Timeout, host x.x.x.x looks like a Philips AirPurifier but doesn't answer, aborting
2024-04-26 12:01:17.066 WARNING (MainThread) [custom_components.philips_airpurifier_coap.config_flow] Timeout, host x.x.x.x looks like a Philips AirPurifier but doesn't answer, aborting
2024-04-26 12:01:22.233 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.128 seconds (success: True)
2024-04-26 12:01:47.095 ERROR (MainThread) [homeassistant.components.device_tracker] Platform asuswrt does not generate unique IDs. ID d0:73:d5:44:56:36 already exists - ignoring device_tracker.lifi_labs_management_pty_ltd_2
2024-04-26 12:01:47.097 ERROR (MainThread) [homeassistant.components.device_tracker] Platform asuswrt does not generate unique IDs. ID 74:da:88:aa:97:54 already exists - ignoring device_tracker.tp_link
2024-04-26 12:01:52.223 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.120 seconds (success: True)
2024-04-26 12:02:22.232 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.127 seconds (success: True)
2024-04-26 12:02:52.217 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.113 seconds (success: True)
2024-04-26 12:02:56.431 ERROR (MainThread) [coap] Connection loss was not expected.
2024-04-26 12:02:56.432 ERROR (MainThread) [coap] Connection loss was not expected.
2024-04-26 12:03:03.056 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.176 seconds (success: True)
2024-04-26 12:03:07.745 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.172 seconds (success: True)
2024-04-26 12:03:38.229 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.125 seconds (success: True)
2024-04-26 12:04:08.246 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.141 seconds (success: True)
2024-04-26 12:04:38.234 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.131 seconds (success: True)
2024-04-26 12:05:08.221 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.116 seconds (success: True)
2024-04-26 12:05:38.216 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.113 seconds (success: True)
2024-04-26 12:06:08.224 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.120 seconds (success: True)
2024-04-26 12:06:38.264 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.161 seconds (success: True)
2024-04-26 12:06:57.821 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.118 seconds (success: True)
2024-04-26 12:07:28.229 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.125 seconds (success: True)
2024-04-26 12:07:58.231 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.127 seconds (success: True)
2024-04-26 12:08:28.233 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.128 seconds (success: True)
2024-04-26 12:08:58.248 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.145 seconds (success: True)
2024-04-26 12:09:28.228 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.124 seconds (success: True)
2024-04-26 12:09:58.375 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.271 seconds (success: True)
2024-04-26 12:10:28.221 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.116 seconds (success: True)
2024-04-26 12:10:58.233 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.129 seconds (success: True)
2024-04-26 12:11:28.218 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.115 seconds (success: True)
2024-04-26 12:11:58.221 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.118 seconds (success: True)
2024-04-26 12:12:28.231 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.126 seconds (success: True)
2024-04-26 12:12:58.234 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.131 seconds (success: True)
2024-04-26 12:13:28.275 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.171 seconds (success: True)
2024-04-26 12:13:58.235 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.132 seconds (success: True)
2024-04-26 12:14:28.218 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.114 seconds (success: True)
2024-04-26 12:14:28.579 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.132 seconds (success: True)
2024-04-26 12:14:58.222 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.118 seconds (success: True)
2024-04-26 12:15:28.222 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.118 seconds (success: True)
2024-04-26 12:15:58.216 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.112 seconds (success: True)
2024-04-26 12:16:28.221 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.117 seconds (success: True)
2024-04-26 12:16:58.220 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.117 seconds (success: True)
2024-04-26 12:17:28.226 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.121 seconds (success: True)
2024-04-26 12:17:58.250 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.146 seconds (success: True)
2024-04-26 12:18:28.211 DEBUG (MainThread) [custom_components.tapo.coordinators] Finished fetching tapo data in 0.108 seconds (success: True)

```

**Comment by StephB67** [comment]
Hello,
I have the same problem.
Action ON/OFF : OK 
State : KO
And this for the 3 plug on the strip.

**Comment by chrisp250** [comment]
> Hello, I have the same problem. Action ON/OFF : OK State : KO And this for the 3 plug on the strip.

I ended moving to the "official" Tp-Link integration that recently added support for Tapo devices and it works fine.

**Comment by StephB67** [comment]
Thanks for your answer but could you explain to me exactly what you did because I don't understand.

**Comment by StephB67** [comment]
Just delete the P300.py file and reboot HA. That's all ?

**Comment by chrisp250** [comment]
> Thanks for your answer but could you explain to me exactly what you did because I don't understand.

From: Settings -> Devices & Integration, remove the P300 powerstrip from the Taco integration (this integration).
Use the TP Link integration included in Home Assistant to set up and configure the power strip: [https://www.home-assistant.io/integrations/tplink/](https://www.home-assistant.io/integrations/tplink/)

Don't delete any files manually.
Cheers

**Comment by StephB67** [comment]
Thank's for your help :)
I modify my setup from Tapo to TP Link and it's okay !!!

**Comment by Arkasha-P** [comment]
Обновил интеграцию на последнюю версию в ручную через ssh. 
Просто через git clone скачайте папку tapo в каталог /homeassistant/custom_components
