### ISSUE TITLE
H100 not connecting to HA

### ISSUE THREAD

**Issue by notarobot63** [petretiandrea/home-assistant-tapo-p100#772]
Hi,

I'm on version 3.1.2 and I can't add the H100 Hub to HA. Here is the error in the logs:

`Cette erreur provient d'une intégration personnalisée

Enregistreur: custom_components.tapo.config_flow
Source: custom_components/tapo/config_flow.py:143
intégration: TP-Link Tapo (documentation, problèmes)
S'est produit pour la première fois: 11:59:28 (1 occurrences)
Dernier enregistrement: 11:59:28

Failed to setup cannot connect
Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 317, in _async_get_device
    await device.update()
  File "/usr/local/lib/python3.12/site-packages/plugp100/new/tapodevice.py", line 79, in update
    await component.update(state)
  File "/usr/local/lib/python3.12/site-packages/plugp100/new/components/hub_children_component.py", line 47, in update
    await child_device.update()
  File "/usr/local/lib/python3.12/site-packages/plugp100/new/tapodevice.py", line 79, in update
    await component.update(state)
  File "/usr/local/lib/python3.12/site-packages/plugp100/new/components/smart_door_component.py", line 15, in update
    self.is_open = current_state["is_open"]
                   ~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'is_open'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 143, in async_step_user
    device = await self._async_get_device(user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/config_flow.py", line 322, in _async_get_device
    raise CannotConnect from error
custom_components.tapo.errors.CannotConnect`

Please let me know, which informations I can provide to help more.

Thanks

**Comment by blacc01** [comment]
I have the same issue since last Tapo update (was today morning). How can i revert to previous Tapo version?
![image](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/106952013/f3936474-a61b-4718-b95c-8a28966f6c6a)

**Comment by DarthSonic** [comment]
For me it is this error after upgrading to newest firmware of Tapo Smart Hub H100:

```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.tapo.coordinators
Quelle: helpers/update_coordinator.py:347
Integration: TP-Link Tapo (Dokumentation, Probleme)
Erstmals aufgetreten: 17:18:53 (4 Vorkommnisse)
Zuletzt protokolliert: 17:18:53

Error fetching tapo data: Error tapo exception: Returned unknown error_code: -1402 msg: curr ver:1.5.5 Build 20230927 Rel. 40646, cloud ver:.
```

**Comment by blacc01** [comment]
I could revert to a full system backup of 3 weeks before. Unfortunatelly partially backups did not help, as it restores only the items which were backuped (Tapo was not in them). After the full restore, there was of course a lot of modul and core updates, i let them do all, EXCEPT Tapo. So i'm now on version 3.0.0 and H100 is working fine as before. This means in short, that the Tapo upgrade messed up the H100 HUB. I'll skip Tapo upgrades until we have a version which will work fine with H100 aswell.

**Comment by blacc01** [comment]
> For me it is this error after upgrading to newest firmware of Tapo Smart Hub H100:
> 
> ```
> Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht
> 
> Logger: custom_components.tapo.coordinators
> Quelle: helpers/update_coordinator.py:347
> Integration: TP-Link Tapo (Dokumentation, Probleme)
> Erstmals aufgetreten: 17:18:53 (4 Vorkommnisse)
> Zuletzt protokolliert: 17:18:53
> 
> Error fetching tapo data: Error tapo exception: Returned unknown error_code: -1402 msg: curr ver:1.5.5 Build 20230927 Rel. 40646, cloud ver:.
> ```
> 
> I see this could also be related to my problem because I installed P110 sensor at the same time: #759

Wait, P110 or T110? P110 is smart connector and T110 is a smart sensor. I had a few P110 long time in my system, had never problems with them (latest firmware is on the units). I added today a T110 smart sensor. The upgrade of the Tapo was also today morning, resulting a crash, i mean the Tapo HUB was inaccessible by HA. I did a full system restore (as written above), and now everything is working, H100 and T110 and P110 also. Tapo version is 3.0.0. now, and skipped upgrade.

**Comment by DarthSonic** [comment]
> > For me it is this error after upgrading to newest firmware of Tapo Smart Hub H100:
> > ```
> > Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht
> > 
> > Logger: custom_components.tapo.coordinators
> > Quelle: helpers/update_coordinator.py:347
> > Integration: TP-Link Tapo (Dokumentation, Probleme)
> > Erstmals aufgetreten: 17:18:53 (4 Vorkommnisse)
> > Zuletzt protokolliert: 17:18:53
> > 
> > Error fetching tapo data: Error tapo exception: Returned unknown error_code: -1402 msg: curr ver:1.5.5 Build 20230927 Rel. 40646, cloud ver:.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I see this could also be related to my problem because I installed P110 sensor at the same time: #759
> 
> Wait, P110 or T110? P110 is smart connector and T110 is a smart sensor. I had a few P110 long time in my system, had never problems with them (latest firmware is on the units). I added today a T110 smart sensor. The upgrade of the Tapo was also today morning, resulting a crash, i mean the Tapo HUB was inaccessible by HA. I did a full system restore (as written above), and now everything is working, H100 and T110 and P110 also. Tapo version is 3.0.0. now, and skipped upgrade.

Sorry!! T110 door sensor.

**Comment by beeeeswax** [comment]
Same problem here with my H100.

`Failed to setup cannot connect
Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 317, in _async_get_device
    await device.update()
  File "/usr/local/lib/python3.12/site-packages/plugp100/new/tapodevice.py", line 79, in update
    await component.update(state)
  File "/usr/local/lib/python3.12/site-packages/plugp100/new/components/hub_children_component.py", line 47, in update
    await child_device.update()
  File "/usr/local/lib/python3.12/site-packages/plugp100/new/tapodevice.py", line 79, in update
    await component.update(state)
  File "/usr/local/lib/python3.12/site-packages/plugp100/new/components/smart_door_component.py", line 15, in update
    self.is_open = current_state["is_open"]
                   ~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'is_open'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 231, in async_step_discovery_auth_confirm
    device = await self._async_get_device_from_discovered(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/config_flow.py", line 295, in _async_get_device_from_discovered
    return await self._async_get_device(config | {CONF_HOST: discovered.ip}, discovered)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/config_flow.py", line 322, in _async_get_device
    raise CannotConnect from error
custom_components.tapo.errors.CannotConnect`

My HA info:

Core: 2024.5.4
Supervisor: 2024.05.1
Operating System: 12.3
Frontend: 20240501.1
Tapo integration: 3.1.2

**Comment by tallackn** [comment]
> Same problem here with my H100.
> 
> ```
> Failed to setup cannot connect
> Traceback (most recent call last):
>   File "/config/custom_components/tapo/config_flow.py", line 317, in _async_get_device
>     await device.update()
>   File "/usr/local/lib/python3.12/site-packages/plugp100/new/tapodevice.py", line 79, in update
>     await component.update(state)
>   File "/usr/local/lib/python3.12/site-packages/plugp100/new/components/hub_children_component.py", line 47, in update
>     await child_device.update()
>   File "/usr/local/lib/python3.12/site-packages/plugp100/new/tapodevice.py", line 79, in update
>     await component.update(state)
>   File "/usr/local/lib/python3.12/site-packages/plugp100/new/components/smart_door_component.py", line 15, in update
>     self.is_open = current_state["is_open"]
>                    ~~~~~~~~~~~~~^^^^^^^^^^^
> KeyError: 'is_open'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/config/custom_components/tapo/config_flow.py", line 231, in async_step_discovery_auth_confirm
>     device = await self._async_get_device_from_discovered(
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/tapo/config_flow.py", line 295, in _async_get_device_from_discovered
>     return await self._async_get_device(config | {CONF_HOST: discovered.ip}, discovered)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/tapo/config_flow.py", line 322, in _async_get_device
>     raise CannotConnect from error
> custom_components.tapo.errors.CannotConnect
> ```
> 
> My HA info:
> 
> Core: 2024.5.4 Supervisor: 2024.05.1 Operating System: 12.3 Frontend: 20240501.1 Tapo integration: 3.1.2

Same here for me.  Happened since firmware on H100 upgraded from Firmware: 1.5.10 Build 240207 Rel.175759 to Firmware: 1.5.12 Build 240320 Rel.123648 back in March.  :'(

**Comment by tallackn** [comment]
> Hi,
> 
> I'm on version 3.1.2 and I can't add the H100 Hub to HA. Here is the error in the logs:
> 
> ```
> 
> Enregistreur: custom_components.tapo.config_flow
> Source: custom_components/tapo/config_flow.py:143
> intégration: TP-Link Tapo (documentation, problèmes)
> S'est produit pour la première fois: 11:59:28 (1 occurrences)
> Dernier enregistrement: 11:59:28
> 
> Failed to setup cannot connect
> Traceback (most recent call last):
>   File "/config/custom_components/tapo/config_flow.py", line 317, in _async_get_device
>     await device.update()
>   File "/usr/local/lib/python3.12/site-packages/plugp100/new/tapodevice.py", line 79, in update
>     await component.update(state)
>   File "/usr/local/lib/python3.12/site-packages/plugp100/new/components/hub_children_component.py", line 47, in update
>     await child_device.update()
>   File "/usr/local/lib/python3.12/site-packages/plugp100/new/tapodevice.py", line 79, in update
>     await component.update(state)
>   File "/usr/local/lib/python3.12/site-packages/plugp100/new/components/smart_door_component.py", line 15, in update
>     self.is_open = current_state["is_open"]
>                    ~~~~~~~~~~~~~^^^^^^^^^^^
> KeyError: 'is_open'
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/config/custom_components/tapo/config_flow.py", line 143, in async_step_user
>     device = await self._async_get_device(user_input)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/config/custom_components/tapo/config_flow.py", line 322, in _async_get_device
>     raise CannotConnect from error
> custom_components.tapo.errors.CannotConnect
> ```
> 
> Please let me know, which informations I can provide to help more.
> 
> Thanks

Same here for me.  Happened since firmware on H100 upgraded from Firmware: 1.5.10 Build 240207 Rel.175759 to Firmware: 1.5.12 Build 240320 Rel.123648 back in March.  :'(

**Comment by Danconnolly** [comment]
KeyError 'is_open' is described here https://github.com/petretiandrea/home-assistant-tapo-p100/issues/759 and is fixed by pull request https://github.com/petretiandrea/plugp100/pull/189

**Comment by DarthSonic** [comment]
Official Tapo Smart Home integration (https://www.home-assistant.io/integrations/tplink_tapo/) now supports Tapo Hub and many more devices. So, I completely switched to that integration after upgrading HA core to 2024.7

**Comment by beeeeswax** [comment]
> Official Tapo Smart Home integration (https://www.home-assistant.io/integrations/tplink_tapo/) now supports Tapo Hub and many more devices. So, I completely switched to that integration after upgrading HA core to 2024.7

Thanks!  I've switched over to this integration too now and everything is working correctly.  I was surprised that after deleting all the Tapo devices and removing this custom integration that the official one picked everything up with it's proper names so it was really easy to plumb everything back in!

**Comment by MustafaKonur** [comment]
Does Official Tapo Smart Home Integration support Tapo H200 Hub, or only H100 Hub? I have Tapo H200 Hub and this official integration doesn't allow me to add Tapo Hub H200.

**Comment by DarthSonic** [comment]
@MustafaKonur you need to ask the developers of the TP Link Smart Home Integration: https://github.com/home-assistant/core/tree/dev/homeassistant/components/tplink

According to documentation it is not supported: https://www.home-assistant.io/integrations/tplink

**Comment by blacc01** [comment]
Today the version 3.1.4. came out, but this has also the HUB connection failure. No sensors are working on HA anymore. Last working version for me was the 3.0.0. So i again had to needed to revert to v3.0.0.

PLEASE correct this bug asap!

**Comment by ItsMeRitch** [comment]
Not stale.

**Comment by beeeeswax** [comment]
Not stale.  That said, this addon is.  I've switched to the official TP-Link integration that's now built into HA and that works fine with all devices, I suggest everyone else affected does the same.
