### ISSUE TITLE
[3.1.2] KE100 no longer recognized, integration crashes

### ISSUE THREAD

**Issue by jpirnay** [petretiandrea/home-assistant-tapo-p100#773]
The smart thermostats (Tapo KE100) are no longer recognized. The integration chokes on unknown responses.

Versions: 
Integration 3.1.2
Hub KH100 1.5.10
Thermostat KE100 2.8.0

```yaml
2024-05-27 05:52:52.007 ERROR (MainThread) [custom_components.tapo.coordinators] Error fetching tapo data: Unexpected exception: 
2024-05-27 06:17:01.173 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 350, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'\x16\x03\x01'
      ^
2024-05-27 06:17:01.414 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 350, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'\x16\x03\x01'
      ^
2024-05-27 18:16:43.153 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 350, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'MGLNDD_188.195.133.144_8123\n'
```

**Comment by jpirnay** [comment]
Update with Hub firmware 1.5.12 it no longer crashes but fully stops recognizing things:
```
2024-05-27 19:17:34.245 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-05-27 19:17:34.246 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-05-27 19:17:34.246 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration tapo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-05-27 19:17:35.321 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues
2024-05-27 19:17:44.618 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 642: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues
2024-05-27 19:19:27.834 INFO (MainThread) [custom_components.tapo.hass_tapo] Found discovered data, avoid to guess protocol
2024-05-27 19:19:32.987 INFO (MainThread) [custom_components.tapo.hass_tapo] Found discovered data, avoid to guess protocol
2024-05-27 19:19:35.939 INFO (MainThread) [custom_components.tapo.hass_tapo] Found discovered data, avoid to guess protocol
2024-05-27 19:19:43.152 INFO (MainThread) [custom_components.tapo.hass_tapo] Found discovered data, avoid to guess protocol
2024-05-27 19:19:56.185 INFO (MainThread) [custom_components.tapo.hass_tapo] Found discovered data, avoid to guess protocol
2024-05-27 19:20:23.263 INFO (MainThread) [custom_components.tapo.hass_tapo] Found discovered data, avoid to guess protocol
```

**Comment by jpirnay** [comment]
Unfortunately it is still relevant - the integration has become useless

**Comment by whyshouldi21** [comment]
I am also experiencing this issue. KE100 devices are not recognised. My KH100 hub is recognised however the KE100 thermostats which are linked to it are not.

**Comment by jpirnay** [comment]
Afaics this is still an issue within 3.1.4

**Comment by jpirnay** [comment]
It's unfortunately still unresolved

**Comment by Redgewell** [comment]
just *bumping* as I have the same problem.

**Comment by wehrmannit** [comment]
https://github.com/JurajNyiri/pytapo could it be related to the same issues here? Tapo changed their API authentication stuff, and this extension expects the same data (cloud user + pw)

**Comment by wehrmannit** [comment]
Issue identified... need to wait until this repository updates the p100 library and updates its requirements. But hey, simple fix :)

**Comment by jpirnay** [comment]
Still relevant

**Comment by wehrmannit** [comment]
I doubt that this issue has been fixed yet...

**Comment by MakaanPL** [comment]
It wasn't - it looks like the extension was abandoned and it's time to switch to the alternative TP-Link integration from HA repo.
