### ISSUE TITLE
Crashes after update due to error on super()

### ISSUE THREAD

**Issue by luixal** [petretiandrea/home-assistant-tapo-p100#779]
## Version of the integration

3.1.3

## Configuration

L530
por TP-Link
Firmware: 1.1.0
Hardware: 2.0

## Describe the bug

Error loading the integration. Obsviously, devices not working.

Messages in integration page:

```yaml
Error de configuración, se volverá a intentar: super() argument 1 must be a type, not str
```

translated to english:

```yaml
Configuration error, will try again: super() argument 1 must be a type, not str
```

## Debug log

Don't think is needed. Above message is quite clear to get started :)

**Comment by Timmy-Turnup** [comment]
Same here, when i tried to set up the switches as new devices i geht the following error:

```
Failed to setup cannot connect
Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 314, in _async_get_device
    device = await connect(config=config, session=session)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/plugp100/new/device_factory.py", line 43, in connect
    protocol = await _get_or_guess_protocol(config, session)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/plugp100/new/device_factory.py", line 65, in _get_or_guess_protocol
    return await _guess_protocol(config, session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/plugp100/new/device_factory.py", line 102, in _guess_protocol
    raise InvalidAuthentication(config.host, config.device_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/plugp100/new/errors/invalid_authentication.py", line 3, in __init__
    super(f"Invalid authentication error for ${host}, ${device_type}")
TypeError: super() argument 1 must be a type, not str

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 143, in async_step_user
    device = await self._async_get_device(user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/config_flow.py", line 322, in _async_get_device
    raise CannotConnect from error
custom_components.tapo.errors.CannotConnect
```

**Comment by alexlopezit** [comment]
I'm also getting the same on all my Tapo lights.

Home Assistant logs

```
This error originated from a custom integration.

Logger: DeviceFactory
Source: custom_components/tapo/hass_tapo.py:34
integration: TP-Link Tapo (documentation, issues)
First occurred: June 23, 2024 at 2:08:59 PM (3410 occurrences)
Last logged: 4:57:02 PM

None of available protocol is working, maybe invalid credentials
```

Error on each integration of my tapo lights
```
Failed setup, will retry super() argument 1 must be a type, not str
```

Also wondering if this has something to do with the issue the Homa Assistant integration for Tapo cameras [here](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/551) as this also started failing for me on the same week. (A bit late but I have now disabled automatic firmware updates on my devices)

**Comment by fcmircea** [comment]
Hello, is there an workaround for this issue?

Should I move to a different integration?

All my smart sockets are basically unusable atm with home assistant.

Thank you!

**Comment by 987654321000123456789** [comment]
Is there any solution/workaround on this?

**Comment by fcmircea** [comment]
I've managed to fix this by removing and re-adding the devices.

**Comment by kingy444** [comment]
I've got two plugs setup currently and started getting this error when adding a third. Latest releases and 2024.8.3

**Comment by kingy444** [comment]
Issue still appears to exist. Unable to add plugs of same model as existing

**Comment by kingy444** [comment]
> I've got two plugs setup currently and started getting this error when adding a third. Latest releases and 2024.8.3

@petretiandrea i've setup the integration in vscode and can setup 2/3 plugs no worries. All devices are P110m and all report the same firmware and hardware version, but looking at them physically, I can definitely notice at least a different font is used to print the info on the device that doesnt work (which leads me to believe there may be a slight revision and they didnt update the app for it)

I enabled debug and setup the integration, The third device goes through all the calls defined in `_guess_protocol` / `perform_handshake1` but fails them all and ultimately failing on `Server response doesn't match our challenge on url`

The logs would indicate the handshake fails and there is now a `klap_handshake_v3` we need to account for, but thats where i am stuck - is there any way to reverse engineer what that is amd how it would work ?

**Comment by kingy444** [comment]
Issue still exists - happy to try and help with the code if you can point in right direction 

Maybe there are new models that came out in AU that have a different cert attached 🤷 

I just don't know how to make the handshake work

**Comment by kingy444** [comment]
> Issue still exists - happy to try and help with the code if you can point in right direction 
> 
> Maybe there are new models that came out in AU that have a different cert attached 🤷 
> 
> I just don't know how to make the handshake work

Still an active issue

**Comment by kingy444** [comment]
> > Issue still exists - happy to try and help with the code if you can point in right direction
> > Maybe there are new models that came out in AU that have a different cert attached 🤷
> > I just don't know how to make the handshake work
> 
> Still an active issue

**Comment by irsl** [comment]
https://github.com/petretiandrea/home-assistant-tapo-p100/pull/901

**Comment by irsl** [comment]
If you encounter the same issue:
- Update the official Tapo smartphone app to the latest
- Go to Me / Third-Party Services / Third-Party Compatibility and turn it on

Wait a bit and the Home Assistant integration should work again

**Comment by joshwillcock** [comment]
> If you encounter the same issue:
> 
> * Update the official Tapo smartphone app to the latest
> * Go to Me / Third-Party Services / Third-Party Compatibility and turn it on
> 
> Wait a bit and the Home Assistant integration should work again

Any idea what 'a bit' is time wise... I enabled third-party compatibility over an hour ago and have seen no change in behaviour.

Update, if it doesn't activate within an hour, toggle it off & on again.
