### ISSUE TITLE
L900 LED strip error while setting hue values: Returned error_code: TapoError.ERR_PARAMS: Request params error 

### ISSUE THREAD

**Issue by oopiicaa** [petretiandrea/home-assistant-tapo-p100#783]
## Version of the integration

3.1.2

## Configuration

L900
by TP-Link
Firmware: 1.1.0
Hardware: 1.0 

Repo downloaded/installed through HACS and configured via UI.

## Describe the bug

Haven't used LED strip for a while (about 6 months). Before now it worked fine (no errors as far as I remember). I recently re-enabled the integration and I'm getting `Failed to call service light/turn_on. Returned error_code: TapoError.ERR_PARAMS: Request params error` while setting hue values for the light through default card for light entity: **changing color and temperatures** of the LED strip - some colors work okay, others not. I can set blue color without errors for an instance, but while setting different white hues doesn't work. Setting state (on/off), brightness and effect of the LED strip work okay.

![image](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/24246157/8f67f72b-0fa6-4cfe-8dc9-31215234950d)

## Debug log

```text

Logger: homeassistant.helpers.script.websocket_api_script
Source: helpers/script.py:526
First occurred: 07:20:50 (1 occurrences)
Last logged: 07:20:50
websocket_api script: Error executing script. Unexpected error for call_service at pos 1: Returned error_code: TapoError.ERR_PARAMS: Request params error

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 526, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 763, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 726, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2741, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2784, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 977, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1049, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 626, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/config/custom_components/tapo/light.py", line 127, in async_turn_on
    await self._set_state(
  File "/config/custom_components/tapo/light.py", line 174, in _set_state
    ).get_or_raise()
      ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/plugp100/common/functional/tri.py", line 159, in get_or_raise
    raise self.value
plugp100.responses.tapo_exception.TapoException: Returned error_code: TapoError.ERR_PARAMS: Request params error

```
Diagnostics file: [config_entry-tapo-19b0e47311008e0f2971a22b813488c7.json](https://github.com/user-attachments/files/16024596/config_entry-tapo-19b0e47311008e0f2971a22b813488c7.json)

**Comment by oopiicaa** [comment]
I believe this is the same as: https://github.com/petretiandrea/home-assistant-tapo-p100/issues/783 https://github.com/petretiandrea/home-assistant-tapo-p100/issues/758 https://github.com/petretiandrea/home-assistant-tapo-p100/issues/736 https://github.com/petretiandrea/home-assistant-tapo-p100/issues/727

**Comment by mazzone** [comment]
Confirming I have this issue too.

**Comment by oopiicaa** [comment]
Not stale

**Comment by oopiicaa** [comment]
Not stale

**Comment by oopiicaa** [comment]
Not stale

**Comment by oopiicaa** [comment]
Not stale

**Comment by gnicolasb** [comment]
Same problem here

**Comment by Danek309044** [comment]
Hi, the error is probably happening beacuse you are trying to set a white tempeture of the led strip, but if you use other colors it works just fine. I think the only fix has to be remove the tempeture settings and the presets from the card.

**Comment by oopiicaa** [comment]
Not stale

**Comment by oopiicaa** [comment]
> Same problem here. Fixed using oficial hass TPLink integration: https://www.home-assistant.io/integrations/tplink

Thanks, I didn't see this somehow :) it works with official integration.
