### ISSUE TITLE
Tapo Integration doesn't work anymore

### ISSUE THREAD

**Issue by daufinsyd** [petretiandrea/home-assistant-tapo-p100#812]
## Version of the integration

3.1.4 (from HACS)

## Configuration

P100
Firmware: 1.2.5 Build 240411 Rel.143808
Hardware: 2.0 

```yaml
Add your logs here.
```

## Describe the bug
Hello

Tapo Integration fail with:

```
Migration error:
Check the logs
```

## Debug log

```text

Logger: homeassistant.config_entries
Source: config_entries.py:978
First occurred: 12:04:08 (1 occurrences)
Last logged: 12:04:08

Error migrating entry Prise connectée Grange for tapo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 978, in async_migrate
    result = await component.async_migrate_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/__init__.py", line 73, in async_migrate_entry
    await migrate_entry_to_v8(hass, config_entry)
  File "/config/custom_components/tapo/migrations.py", line 20, in migrate_entry_to_v8
    config_entry.version = 8
    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 463, in __setattr__
    raise AttributeError(
AttributeError: version cannot be changed directly, use async_update_entry instead

```

Edit:
HomeAssistant-Tapo-Control  has a similar issue:
https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/issues/528

**Comment by Knutowskie** [comment]
try the tp-link integration that is default. it seems to show all my plugs and is able to read data.

**Comment by daufinsyd** [comment]
indeed it works flawlessly !
I didn't know it became an official integration

Thank you !

**Comment by techie-dreamer** [comment]
> try the tp-link integration that is default. it seems to show all my plugs (HS100 HS110 P100 P110) and is able to read data.

Likewise, my GU10 bulb broken with Jan 2025 HA release and now working switching integrations.

**Comment by CloCkWeRX** [comment]
Not stale
