### ISSUE TITLE
Rate limit exceeded in automations

### ISSUE THREAD

**Issue by qu4nd** [petretiandrea/home-assistant-tapo-p100#814]
Tapo integration v 3.1.2 on Homeassistant 2024.11.3 (and older) in a docker container on a Raspberry Pi.

I regularly experience the issue, that Tapo throws an error when I'm switching one of my devices (seems to affect P100 only) in automations:

`Error: Returned error_code: TapoError.ERR_DEVICE: Rate limit exceeded`

A second later It works again as if nothing happend.

That's one of the log entries I've found:
`2024-11-28 07:42:47.888 ERROR (MainThread) [homeassistant.components.automation.hausnummer_off] Auto - Lights off at 0:00 l sunrise : Error executing script. Unexpected error for device at pos 2: Returned error_code: TapoError.ERR_DEVICE: Rate limit exceeded
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 526, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 781, in _async_device_step
    await device_action.async_call_action_from_config(
  File "/usr/src/homeassistant/homeassistant/components/device_automation/action.py", line 72, in async_call_action_from_config
    await platform.async_call_action_from_config(hass, config, variables, context)
  File "/usr/src/homeassistant/homeassistant/components/switch/device_action.py", line 36, in async_call_action_from_config
    await toggle_entity.async_call_action_from_config(
  File "/usr/src/homeassistant/homeassistant/components/device_automation/toggle_entity.py", line 124, in async_call_action_from_config
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/tapo/switch.py", line 64, in async_turn_off
    (await self._plug.turn_off()).get_or_raise()
  File "/usr/local/lib/python3.12/site-packages/plugp100/common/functional/tri.py", line 159, in get_or_raise
    raise self.value
plugp100.responses.tapo_exception.TapoException: Returned error_code: TapoError.ERR_DEVICE: Rate limit exceeded
2024-11-28 07:42:47.896 ERROR (MainThread) [homeassistant.components.automation.hausnummer_off] While executing automation automation.hausnummer_off
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 743, in async_trigger
    return await self.action_script.async_run(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1801, in async_run
    return await asyncio.shield(create_eager_task(run.async_run()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 464, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 528, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 581, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 526, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 781, in _async_device_step
    await device_action.async_call_action_from_config(
  File "/usr/src/homeassistant/homeassistant/components/device_automation/action.py", line 72, in async_call_action_from_config
    await platform.async_call_action_from_config(hass, config, variables, context)
  File "/usr/src/homeassistant/homeassistant/components/switch/device_action.py", line 36, in async_call_action_from_config
    await toggle_entity.async_call_action_from_config(
  File "/usr/src/homeassistant/homeassistant/components/device_automation/toggle_entity.py", line 124, in async_call_action_from_config
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/tapo/switch.py", line 64, in async_turn_off
    (await self._plug.turn_off()).get_or_raise()
  File "/usr/local/lib/python3.12/site-packages/plugp100/common/functional/tri.py", line 159, in get_or_raise
    raise self.value
plugp100.responses.tapo_exception.TapoException: Returned error_code: TapoError.ERR_DEVICE: Rate limit exceeded`

**Comment by qu4nd** [comment]
Well, since it's still happening, I would love to see any progress on this 😅
![Screenshot_20241231-133145](https://github.com/user-attachments/assets/50680165-d2a8-49a5-af9e-5401e138d343)

**Comment by revidm** [comment]
I, too, have this issue with a switch device. Haven't yet worked out what causes it.

**Comment by andrix988** [comment]
I'm facing the same issue.
In my case the action is in any case performed, but:
1-HA didn't track that the action is performed by the automation;
2- The automation stops to work (the following actions aren't performed

Only 2 is a real problem to me, I will work on a workaround :)

![Image](https://github.com/user-attachments/assets/0ec60d3d-b1c0-4ecd-8a03-9ff394dea689)
![Image](https://github.com/user-attachments/assets/6e2a9a86-6dea-464f-aa40-44745f372335)

**Comment by lee-js** [comment]
I also have this problem when clicking one of the auto generated buttons in Home Assistant.

Failed to perform the action switch/turn_on. Returned error_code: TapoError.ERR_DEVICE: Rate limit exceeded
The device is a P100 running Firmware: 1.5.5 Hardware: 1.20.0
