### ISSUE TITLE
Changed PW in Tapo App - Nothing reachable anymore - cant change PW in HA Integration

### ISSUE THREAD

**Issue by skorpion1298** [petretiandrea/home-assistant-tapo-p100#817]
## Version of the integration
3.1.2

## Describe the bug

I Changed the PW to a more secure one and lost connection to my Tapos of course. Wanted to change the PW in the Integration but cant find a way to do that. Is there a Button I am not seeing for changing my PW? It may be missing and should be added please.
Is there maybe a different way wich I dont know to change it? I went the hardcore way and tried to edit the config file "core.config_entries" but without any luck.

## Debug log

```text

Logger: homeassistant.config_entries
Quelle: config_entries.py:978
Erstmals aufgetreten: 15:06:44 (2 Vorkommnisse)
Zuletzt protokolliert: 15:06:44

Error migrating entry Balkonlicht for tapo
Error migrating entry Büro Tisch for tapo
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1109, in _wrap_create_connection
    sock = await aiohappyeyeballs.start_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohappyeyeballs/impl.py", line 82, in start_connection
    sock = await _connect_sock(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohappyeyeballs/impl.py", line 174, in _connect_sock
    await loop.sock_connect(sock, address)
  File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 641, in sock_connect
    return await fut
           ^^^^^^^^^
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 663, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 538, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1050, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1384, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1353, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1106, in _wrap_create_connection
    async with ceil_timeout(
  File "/usr/local/lib/python3.12/asyncio/timeouts.py", line 115, in __aexit__
    raise TimeoutError from exc_val
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 978, in async_migrate
    result = await component.async_migrate_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tapo/__init__.py", line 73, in async_migrate_entry
    await migrate_entry_to_v8(hass, config_entry)
  File "/config/custom_components/tapo/migrations.py", line 15, in migrate_entry_to_v8
    device = await connect(config=create_device_config(config_entry), session=session)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/plugp100/new/device_factory.py", line 43, in connect
    protocol = await _get_or_guess_protocol(config, session)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/plugp100/new/device_factory.py", line 65, in _get_or_guess_protocol
    return await _guess_protocol(config, session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/plugp100/new/device_factory.py", line 94, in _guess_protocol
    info = await protocol.send_request(device_info_request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/plugp100/protocol/passthrough_protocol.py", line 45, in send_request
    response = await self._send_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/plugp100/protocol/passthrough_protocol.py", line 65, in _send_request
    await self._login_with_version(self._credential)
  File "/usr/local/lib/python3.12/site-packages/plugp100/protocol/passthrough_protocol.py", line 84, in _login_with_version
    session_or_error = await self._passthrough.handshake(self._url)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/plugp100/protocol/securepassthrough_transport.py", line 70, in handshake
    response = await self._http.async_make_post(url, json=request_body)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/plugp100/common/utils/http_client.py", line 18, in async_make_post
    async with self.session.post(
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 1360, in __aenter__
    self._resp: _RetType = await self._coro
                           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 667, in _request
    raise ConnectionTimeoutError(
aiohttp.client_exceptions.ConnectionTimeoutError: Connection timeout to host http://192.168.10.6/app


Another LOG Entry:
Dieser Fehler stammt von einer benutzerdefinierten Integration

Logger: DeviceFactory
Quelle: custom_components/tapo/hass_tapo.py:34
Integration: TP-Link Tapo (Dokumentation, Probleme)
Erstmals aufgetreten: 15:06:14 (321 Vorkommnisse)
Zuletzt protokolliert: 22:34:59

None of available protocol is working, maybe invalid credentials

```

**Comment by the-black-eagle** [comment]
Yeah, I had this issue too.  Rather than delving through the code to figure out where the pw is stored, I ended up removing the devices and re-adding them with the new password.  That worked instantly, but I would have thought that there should be some method of changing the stored password in the event that a user wants to do so other than deleting and re-adding devices.

**Comment by fsnuxer** [comment]
Same experience.
It would be nice to be able to change the password after the initial setup ; without having to remove / add again every tapo plug...
In the meantime, stopping ha ; editing the passwords in .storage/core.config_entries file and restarting ha worked for me.
