### ISSUE TITLE
Unexpected exception

### ISSUE THREAD

**Issue by gaelito17** [petretiandrea/home-assistant-tapo-p100#97]
When I entered my credentials (and host), I have an error (Unexpected).
I guess, this is linked to the new HA version. Here is my setup:

Home Assistant OS 7.0
core-2021.12.1

I have the following logs: 

Logger: custom_components.tapo.config_flow
Source: custom_components/tapo/config_flow.py:85
Integration: Tapo Controller (documentation, issues)
First occurred: 09:39:30 (1 occurrences)
Last logged: 09:39:30

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/tapo/config_flow.py", line 48, in async_step_user
    entry_metadata = await self._validate_input(user_input)
  File "/config/custom_components/tapo/config_flow.py", line 85, in _validate_input
    state = await tapo_api.get_state()
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 89, in get_state
    state=await self.get_state_as_dict(),
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 213, in get_state_as_dict
    return await self._execute_method_request(device_info_method)
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 238, in _execute_method_request
    self.__validate_response(resp_dict)
  File "/usr/local/lib/python3.9/site-packages/plugp100/api.py", line 257, in __validate_response
    raise TapoException.from_error_code(resp['error_code'])
plugp100.core.exceptions.TapoException.TapoException: Returned unknown error_code: 9999

Let me know if I can help

**Comment by gaelito17** [comment]
Working now without any change…. The only difference is I added the integration while the switch was OFF.
